import { MIN_RATED_ANSWERS } from './scoring.js';
import { CALIBRATION } from '../data/cardCalibration.js';
import { CLUB_NAME_TO_COMP } from '../data/clubPackColours.js';
// Ball IQ player-rating card — six "competition" face stats + a compiled overall
// + a Bronze / Silver / Gold tier.
//
// catStats shape (from saveStats): { [cat]: { c, a } } — c and a are
// DIFFICULTY-WEIGHTED and RECENCY-DECAYED (saveStats: DIFF_CREDIT / DIFF_MISS /
// CAT_DECAY), so c/a is "how well, lately, for how hard", not a raw ratio.
//
// ── THE 2026-09-09 REBUILD — three defects, one measured population ──────────
// 1. The overall was the MEAN OF THE SIX FACES, unplayed faces included at an
//    invented prior. Three dashes on the card, three invented numbers in the 71
//    above them.
// 2. The prior for every unplayed face was the player's OWN running accuracy.
//    Two early rights set all six to gold; every answer after was decay toward
//    the truth — a real player's "it keeps going down the more I play".
// 3. HALF OF ALL ANSWERS NEVER REACHED THE CARD. Club quiz re-tags every row
//    cat:"ClubQuiz" (the single biggest bucket in prod — 2,039 answers, ahead
//    of World Cup and PL), Survival is "chaos", and the theme categories
//    (History / Legends / Records / Managers / Transfers) feed no face. An
//    Arsenal fan who plays the Arsenal pack daily had an empty EPL stat.
// And the scale: 40 + 59·acc put the MEDIAN player (acc 0.58) at 74 and a third
// of everyone in gold, with 80% of players between 64 and 82. It could not tell
// good from great.
//
// NOW:
// - The overall is EVERY answer, all modes, smoothed toward the population
//   median with PRIOR_WEIGHT answers of weight — starts mid-table, moves in
//   both directions with evidence, and a steady player converges rather than
//   drifting.
// - The scale is CALIBRATED to the measured population (src/data/
//   cardCalibration.js, generated by scripts/calibrate-card.mjs): p50 → 65,
//   p75 → 75, so GOLD MEANS TOP QUARTER. Tiers stay 60 / 75.
// - Club play FEEDS THE FACES: faceCatFor() routes an answer by its real
//   category, or by its club's league (Arsenal → PL, Juventus → SerieA). The
//   saveStats writer files each answer under its face when it has one.
// - A face prints only from its own data (≥ MIN_RATED_ANSWERS); the overall
//   never derives from the faces.
// - THE NUMBER IS DIFFICULTY-WEIGHTED ACCURACY (Alex, later the same day):
//   a correct answer is worth 1.0 easy / 1.1 medium / 1.2 hard, a miss 0, the
//   rating is 100 × the mean. 61% on easy = 61, on medium = 67, on hard = 73.
//   It replaced a percentile-calibrated "score above expectation" model built
//   two hours earlier: that one was statistically right and could not be
//   explained on a card, and a number a player can verify beats one they
//   have to trust. catStats keys carry {s, n} beside the legacy {c, a}; a
//   record with no s/n converts as s = AVG_MULT·c (exact for average
//   difficulty). The population percentiles stay in the calibration file as
//   the reference for where the tiers fall: the measured median player rates
//   ~64, the 75th percentile ~74, the 90th ~79.

// The six face stats. `cat` maps to the question bank's cat field; `abbr` is the
// 3-letter card label (the competition's short code).
// `icon` uses country flags (license-safe, unlike the trademarked competition
// logos). England flag for the PL, a star for the UCL, a globe for international.
// `color` is the competition's own colour, and it must stay equal to the one
// LEAGUE_QUIZ_SECTIONS (App.jsx) uses for the same `cat` — the quiz picker and
// the rating card naming the same competition in two different colours is the
// drift this app keeps producing. Pinned by tests/unit/card-comp-colours.test.js.
// ⚠️ THE FACES MUST BE SHAPED LIKE THE BANK, NOT LIKE A LEAGUE TABLE.
// Re-cut 2026-09-10 after Alex, a Legend-XP player, opened his card and found
// two of six filled: "as a player in the legend xp league you mean to tell me
// only 2 out of 6 items on the card is filled out."
//
// He was not an outlier. Measured across all 105 accounts with real history:
// 67.6% saw ONE fully-rated face or none, and 11.4% saw all six. The cause was
// not the gate and not decay — lowering the gate from 10 to a reckless 3 still
// only reached 3.15 of 6, because the answers do not exist. The six faces were
// leagues; the bank is not. Only 47.3% of questions could EVER reach a face,
// while History, Legends, Records, Managers and Transfers — 47% of the bank —
// showed nothing, and the three thin league faces held 14% of it between them.
//
// These six cover 99.2% of the bank and 92.1% of all play recorded to date.
// ⚠️ Deleting the thin leagues outright (the obvious re-cut) measured WORSE on
// play than it looked on paper — 56.2% — because it drops those leagues AND
// still misses ClubQuiz, the single biggest bucket in prod at 2,049 answers.
// Folding them into one Clubs face is what carries club play onto the card.
export const CARD_COMPS = [
  // ⚠️ SLOT 0 IS THE PLAYER'S OWN LEAGUE, not the Premier League. This entry is
  // only the DEFAULT — see LEAGUE_FACES / cardCompsFor. Giving the Premier
  // League a permanent face while La Liga, Serie A and the Bundesliga shared
  // one was an English bias inherited from our bank's shape, not a fact about
  // the player: a Barcelona fan opened the card and saw EPL and no La Liga.
  // Alex, 2026-09-10: "we ditched the other leagues apart from premier league,
  // i am not sure where the logic in that is."
  { abbr: "EPL", cat: "PL",       name: "Premier League",     short: "Premier League",   icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#3D195B" },
  { abbr: "UCL", cat: "UCL",      name: "Champions League",   short: "Champions League", icon: "⭐", color: "#123A8F" },
  { abbr: "INT", cat: "WorldCup", name: "International",      short: "International",    icon: "🌍", color: "#8A6D1B" },
  // ⚠️ DO NOT INVENT ABBREVIATIONS. EPL, UCL and INT are abbreviations football
  // fans already know; CLB, LEG and REC were coined here and nobody has ever
  // seen them — "REC" reads as a record button and "LEG" reads as a leg. Alex,
  // on first sight of his own card: "i think if it is not that obvious to me
  // then it might be confusing to the actual users." Where a real abbreviation
  // exists, use it; where one does not, spell the word.
  // ⚠️ "WORLD", not "EUROPE" — and not by taste. This face holds nineteen club
  // packs and SIX are South American (Boca Juniors, River Plate, Flamengo,
  // Palmeiras, Corinthians, Santos), so "Europe" would be plainly wrong for
  // them — the same shape of error as the English bias the league slot just
  // shed: true for most, wrong for a real minority. The `cat` stays "Clubs"
  // because it is a STORAGE KEY with rows already written under it; only the
  // label changed.
  { abbr: "WORLD",   cat: "Clubs",    name: "Clubs worldwide",    short: "Club Football",    icon: "🛡️", color: "#EE8707" },
  { abbr: "LEGENDS", cat: "Legends",  name: "Legends & History",  short: "Legends",          icon: "📜", color: "#B03A2E" },
  { abbr: "RECORDS", cat: "Records",  name: "Records & Managers", short: "Records",          icon: "📊", color: "#1B7F79" },
];

// Bank categories that ARE a face under another name. `ChampionsLeague` is a
// legacy key still present in 46 prod profiles beside `UCL`; `Euros` is
// international football and belongs with the World Cup on the INT face.
// ⚠️ ALIASES ARE THE MIGRATION. computeCard folds these BEFORE reading, so
// every stored key keeps counting under its new face with no data migration
// and nothing lost: a player's LaLiga/Bundesliga/SerieA history becomes their
// Clubs face, History joins Legends, Managers and Transfers join Records.
// `ChampionsLeague` is a legacy key still live in 46 prod profiles beside
// `UCL`; `Euros` is international football and belongs with the World Cup.
export const FACE_ALIAS = {
  ChampionsLeague: "UCL",
  Euros: "WorldCup",
  // Clubs & Leagues — every club competition that is not the Premier League,
  // plus the club-quiz bucket itself (the biggest single key in prod).
  // Leagues are folded by computeCard against the player's own league, not from
  // this table — these entries are the fallback for any other reader.
  LaLiga: "Clubs", SerieA: "Clubs", Bundesliga: "Clubs",
  Ligue1: "Clubs", SuperLig: "Clubs", Primeira: "Clubs", ClubQuiz: "Clubs",
  // Legends & History
  History: "Legends",
  // Records & Managers
  Managers: "Records", Transfers: "Records",
};

// Every league that can occupy slot 0. Measured on all 105 accounts: picking
// the player's own most-played league costs nothing on fill (2.68 vs 2.61 of
// six rated) and shows La Liga to 17% of players, the Bundesliga to 5% and
// Serie A to 4% — the quarter of players the fixed card was slighting. It also
// makes the label explain itself: a Spaniard reads "LA LIGA", which needs no
// glossary. Auto-picked from play, never a setting — most people never open
// settings, and we already know the answer from what they play.
// `short` is the noun the Profile verdict says out loud ("<short> Specialist").
// The two thematic faces and the Clubs pool have names built for the card row
// ("Legends & History"), which read as nonsense in that sentence — "Legends &
// History Specialist". Three of six broke the moment the faces were re-cut.
export const LEAGUE_FACES = [
  { abbr: "EPL",        cat: "PL",         name: "Premier League", icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#3D195B" },
  { abbr: "LA LIGA",    cat: "LaLiga",     name: "La Liga",        icon: "🇪🇸", color: "#EE8707" },
  { abbr: "SERIE A",    cat: "SerieA",     name: "Serie A",        icon: "🇮🇹", color: "#0578D3" },
  { abbr: "BUNDESLIGA", cat: "Bundesliga", name: "Bundesliga",     icon: "🇩🇪", color: "#D20515" },
  { abbr: "LIGUE 1",    cat: "Ligue1",     name: "Ligue 1",        icon: "🇫🇷", color: "#1B2447" },
  { abbr: "SÜPER LIG",  cat: "SuperLig",   name: "Süper Lig",      icon: "🇹🇷", color: "#E30A17" },
  { abbr: "PRIMEIRA",   cat: "Primeira",   name: "Primeira Liga",  icon: "🇵🇹", color: "#046A38" },
];
export const LEAGUE_CATS = new Set(LEAGUE_FACES.map(l => l.cat));

/**
 * How big a face's label may be set, given how long it is.
 *
 * ⚠️ THE ROW IS HALF A CARD WIDE AND THE LABELS ARE NOT ONE LENGTH. Six of the
 * nine possible faces are 5-7 characters and fit at full size; "BUNDESLIGA" is
 * ten, "SÜPER LIG" nine, and the league slot also carries a chevron when it is
 * tappable. Left alone the two surfaces fail DIFFERENTLY, which is how this
 * kind of thing survives review: the React card ellipsises ("BUNDESLI…", seen
 * on device the moment a Bundesliga pin was tried) while the canvas share
 * render, which has no overflow handling at all, would run the label straight
 * under the rating.
 *
 * So the rule lives here and both surfaces read it — the React card at base 13,
 * the canvas at base 16. Shrinking the long ones is right rather than
 * abbreviating them: CARD_COMPS already forbids inventing abbreviations
 * ("where a real abbreviation exists, use it; where one does not, spell the
 * word"), and "BUN" is not a thing anyone calls the Bundesliga.
 */
export function faceLabelType(abbr, base) {
  const n = (abbr || "").length;
  if (n >= 10) return { size: +(base * 0.80).toFixed(2), tracking: 0.2 };
  if (n >= 8)  return { size: +(base * 0.88).toFixed(2), tracking: 0.4 };
  return { size: base, tracking: 1 };
}

/**
 * Which league owns slot 0 for this player: the one they have answered most,
 * Premier League when nothing separates them (it is the bank's largest league,
 * so it is the safest default rather than a privileged one).
 *
 * ⚠️ STICKY BY MARGIN. A face that swaps every time two leagues trade places
 * would read as the card losing data — the complaint this whole re-cut came
 * from. A challenger must beat the incumbent by more than a rounding error.
 */
export function pickLeagueFace(catStats = {}, pinned) {
  // ⚠️ AN EXPLICIT CHOICE IS ABSOLUTE, AND IS NOT REQUIRED TO HAVE EVIDENCE.
  // The whole reason the picker exists is the player the auto-pick CANNOT
  // serve: measured across the 112 rated cards, 8 (7%) have not answered a
  // single league-category question, so their slot falls back to the Premier
  // League by pure default — a German who watches the Bundesliga, wearing an
  // English badge because Daily 7 and club packs are all they have played.
  // Alex: "there might be germans people that mostly watch bundesliga or
  // spanish people that mostly watch la liga you know."
  //
  // So a pin does NOT feed the ranking and is NOT overridable by play. If you
  // choose the Bundesliga, twenty Premier League answers must not take it off
  // your card. An unrated pinned face simply prints no number, which is honest
  // and is the state the card already knows how to show.
  const chosen = pinned ? LEAGUE_FACES.find(l => l.cat === pinned) : null;
  if (chosen) return chosen;

  // Unpinned: the league you have actually answered most in. This already
  // works for 27% of players (La Liga 18%, Serie A 4%, Bundesliga 4%), and
  // club play feeds it — a Bayern fan playing the Bayern pack accumulates
  // Bundesliga through faceCatFor.
  //
  // ⚠️ A 20% STICKINESS RULE USED TO LIVE HERE AND WAS DEAD CODE. It took a
  // `current` argument to stop the slot changing hands when two leagues sit
  // close together — and NO CALLER EVER PASSED IT, so it never once ran. It is
  // gone rather than wired, because it needs state this function does not have
  // (the previously-shown league, persisted) and because pinning solves the
  // same problem outright for anyone who cares. 25 of 112 cards have their top
  // two leagues within 20% of each other; for those the slot still changes as
  // they play, which is CORRECT — it reflects what they answer — and they can
  // pin it if they would rather it did not.
  const own = (c) => rawAnswered((catStats || {})[c]);
  const ranked = LEAGUE_FACES.map(l => ({ l, n: own(l.cat) })).sort((a, b) => b.n - a.n);
  const top = ranked[0];
  if (!top || top.n <= 0) return LEAGUE_FACES[0];
  return top.l;
}

/** The six faces for THIS player, in card order. */
export function cardCompsFor(catStats = {}, pinned) {
  const league = pickLeagueFace(catStats, pinned);
  return [league, ...CARD_COMPS.slice(1)];
}

// ⚠️ NOT EVERY ANSWER BELONGS ON A KNOWLEDGE CARD. `chaos` is a 59-question
// pool answered 1,025 times — 17 plays per question — and it is the EASIEST
// category in the app by a distance (73.4% against a 37-73% range and a 58%
// median). It measures memory of 59 items, not football knowledge, and it has
// no honest face: it is quotes and moments, so nothing on the card is "how
// good you are at chaos".
//
// ⚠️ I FOLDED IT INTO Legends FIRST AND THAT WAS WORSE. It made the card
// arithmetically consistent by making one face lie: a player whose real
// Legends record is 0/7 and History 29% read LEGENDS 94, because 452 chaos
// answers were wearing a Legends label. Alex, immediately: "my hunch tells me
// 94 is way too high for legends... he would look at this card and think this
// really does not reflect his ability." Making the overall agree with the
// faces is worthless if the way you do it is to falsify a face.
//
// So chaos is dropped before anything is computed — from the faces AND from
// the overall. Playing it still earns XP and streaks; it just does not claim
// to measure knowledge.
export const EXCLUDED_CATS = new Set(["chaos"]);

const FACE_CATS = new Set(CARD_COMPS.map(c => c.cat));

// The four faces that name a COMPETITION. `Legends` and `Records` are the two
// thematic faces and are deliberately absent — see faceCatFor step 1.
const COMPETITION_FACES = new Set(["PL", "UCL", "WorldCup", "Clubs"]);

/**
 * Which face an answer feeds, or null (overall only).
 * Order: the answer's real category (club quiz carries it as `realCat` beside
 * the UI re-tag), then an alias, then the club's league.
 */
export function faceCatFor(ans) {
  if (!ans) return null;
  const cat = ans.realCat || ans.cat;
  // 1. A COMPETITION the answer names outright. Only competitions short-circuit
  //    here: a Champions League question inside an Arsenal round is a Champions
  //    League question, and that has always been the rule. The two THEMATIC
  //    faces do not, because they cut across every competition — "Legends" says
  //    nothing about which club's round you were playing, so it must not beat
  //    the club below. Without this split the rule was arbitrary: History in an
  //    Arsenal round reached EPL while Legends in a Juventus round reached LEG,
  //    for no reason except which of the two happened to be a face's canonical
  //    key and which an alias.
  if (COMPETITION_FACES.has(cat)) return cat;
  // ⚠️ A LEAGUE IS STORED AS ITSELF, NEVER PRE-POOLED. The card's league slot
  // is the player's own most-played league, so folding La Liga into "Clubs"
  // here would destroy the signal that slot reads — and it is irreversible:
  // once two leagues share a key their answers cannot be told apart again.
  // Pooling belongs at READ time (computeCard), where it can be undone.
  if (LEAGUE_CATS.has(cat)) return cat;
  // 2. ⚠️ THE CLUB BEFORE THE ALIAS, and the order matters now that the thin
  //    leagues are aliases rather than faces (2026-09-10). "Play your club,
  //    build your club's league" is an explicit promise — a History question
  //    inside an Arsenal round is still an Arsenal round, and before the
  //    re-cut it reached EPL only because History had no face. Aliasing
  //    History would have silently moved every one of those answers off the
  //    club's face. The club is the stronger signal whenever we have it.
  if (ans.club && CLUB_NAME_TO_COMP[ans.club]) return CLUB_NAME_TO_COMP[ans.club];
  // 3. Otherwise fold the category onto the face that now carries it — this is
  //    where a thematic category lands when there is no club to prefer.
  if (FACE_CATS.has(cat)) return cat;
  if (FACE_ALIAS[cat]) return FACE_ALIAS[cat];
  return null;
}

/**
 * The card face a QUIZ CATEGORY builds, as the abbreviation printed on the
 * card ("EPL", "INT"), or null when that category feeds no face.
 *
 * ⚠️ THE LEAGUE PICKER MUST NOT PROMISE A RATING THAT DOES NOT EXIST. Its
 * rows printed `Builds your ${abbr} rating` off the PICKER's own abbr for
 * every row, and the picker carries thirteen entries against the card's six
 * faces — so seven rows advertised an L1 / TSL / PRI / LEG / MGR / REC
 * rating that is nowhere in the app, and Euros promised "EUR" when its
 * answers land on INT. Only five of thirteen rows were true. Deriving the
 * copy from CARD_COMPS is what makes the picker's claim un-rottable: add a
 * league without a face and it now says the honest thing by itself.
 * (Found in the simulator 2026-09-09.)
 */
export function faceAbbrForCat(cat) {
  const face = FACE_CATS.has(cat) ? cat : (FACE_ALIAS[cat] || null);
  if (!face) return null;
  return (CARD_COMPS.find(c => c.cat === face) || {}).abbr || null;
}

// A face with fewer than MIN_RATED_ANSWERS but at least this many prints a
// PROVISIONAL number — muted, never the accented "best" — instead of a bar.
// Alex, 2026-09-09, seeing La Liga / Bundesliga / Serie A as three bars after
// they had carried numbers: "where is the rating? in the shadow realms? it
// can not vanish like this". He is right about the feel: a number that was
// there and then is not reads as a loss, whatever the gate's statistics. Three
// answers is where the number stops being pure prior; shrinkage toward the
// overall (weight 2) keeps it believable until ten.
export const PROVISIONAL_ANSWERS = 3;

// Prior weight, in answers, for the overall — how many answers the population
// median "counts as" before the player's own record takes over.
//
// TWENTY, NOT TEN, AND THE DIRECTION IS THE POINT. The calibrated scale is
// steep where players actually live (0.58 → 65, 0.82 → 93: 28 points across
// 0.24 of accuracy), so at ten answers the noise in a record is ±15 rating
// points. Simulated with weight 10, a lucky 8/10 start printed 79 · GOLD, then
// slid to 71 · SILVER over the next thirty answers at a true 65% — the exact
// "it keeps going down" a real player reported. With weight 20 the same run
// prints 73 and settles at 70: a three-point correction, no tier flip. And a
// STEADY above-median player now RISES toward their level (68 → 72 → 75)
// rather than starting above it and falling. Shrinkage toward the median is
// honest — with little evidence you are assumed near the middle — and it makes
// the common experience "the more I play, the more it reflects me", which is
// the only direction a rating should surprise in. Twenty ≈ two club quizzes.
export const PRIOR_WEIGHT = 20;

/** Multiplier a correct answer earns, by difficulty. Unknown labels count as medium. */
export const MULT = CALIBRATION.mult;
export const AVG_MULT = CALIBRATION.avgMult;
/** The measured median player's rating, as a fraction (≈0.64): where a card with no evidence starts. */
export const BASELINE = CALIBRATION.baseline;
export function multFor(diff) { return MULT[diff] ?? MULT.medium; }

/** Mean score (0…1.2) → 40-99. Linear: 0.61 → 61. Capped at 99 — perfect on hard is 120. */
export function ratingFromScore(mean) {
  const x = Number.isFinite(mean) ? mean : BASELINE;
  return Math.max(40, Math.min(99, Math.round(x * 100)));
}

/** Kept for the calibration tests and any caller that thinks in accuracy: an average-difficulty record. */
export function ratingFromAccuracy(acc) {
  return ratingFromScore((Number.isFinite(acc) ? acc : CALIBRATION.median) * AVG_MULT);
}

/**
 * A key's score record. New writes carry {s, n} (decayed score sum and
 * answer count). A legacy {c, a} converts as s = AVG_MULT·c — exact for a
 * record of average difficulty; both may be present after the upgrade.
 */
// Which raw bucket carries which weight. `u` is UNKNOWN difficulty — answers we
// have a real record of but no grade for, because Daily 7 only started storing
// `diff` on 2026-09-01. They are worth the average question, which is the
// honest thing to say about an answer whose difficulty we cannot look up.
const BUCKET_MULT = { e: MULT.easy, m: MULT.medium, h: MULT.hard, u: AVG_MULT };

/**
 * Raw, verifiable counts from `d` FIRST, with the decayed totals carrying only
 * whatever they claim beyond them.
 *
 * ⚠️ THE DECAYED TOTALS ARE NOT COUNTS AND CANNOT BE SHOWN TO ANYONE. `c` and
 * `a` are exponentially-weighted sums (CAT_DECAY per answer): `a` SATURATES AT
 * 200 no matter how much you play, and `c` comes out as 26.78. Alex, on a real
 * card: "how do you answer 26.78 questions right with decimals? ... this is all
 * really confusing and just looks wrong." He was right, and it was not only a
 * presentation problem — for one player the decayed totals said 46% at Premier
 * League while his 38 LOGGED Daily 7 answers said 61%. A scale built on a
 * number nobody can check will quietly disagree with the record.
 *
 * ⚠️ AND `d` ALONE IS NOT THE ANSWER EITHER — that is the same mistake as
 * rawAnswered's, which deleted a rating the moment someone played. `d` only
 * holds answers recorded since the rebuild, so it is a SUBSET of what c/a
 * claim. Both are used: the exact part from `d`, and the remainder the decayed
 * totals still assert, weighted as average difficulty and clearly the weaker
 * evidence. As real counts accumulate the remainder shrinks to nothing and the
 * whole rating becomes verifiable.
 */
export function scoreOf(cs) {
  if (!cs) return { s: 0, n: 0 };
  // A PRE-SUMMED record from computeCard's fold, which has already scored each
  // member and added them up. Only the fold writes s/n (recordAnswers stopped
  // on 2026-09-10), so this branch never sees a stored record.
  if (Number.isFinite(cs.s) && Number.isFinite(cs.n) && cs.n > 0) return { s: cs.s, n: cs.n };
  let s = 0, n = 0;
  const d = cs.d;
  if (d && typeof d === "object") {
    for (const k of ["e", "m", "h", "u"]) {
      const b = d[k];
      if (!Array.isArray(b)) continue;
      s += BUCKET_MULT[k] * (b[0] || 0);
      n += (b[1] || 0);
    }
  }
  const a = cs.a || 0, c = cs.c || 0;
  const extra = a - n;
  if (extra > 0 && a > 0) {
    // Same accuracy the decayed record claims, at average difficulty.
    s += AVG_MULT * (c / a) * extra;
    n += extra;
  }
  return { s, n };
}
// The name the writer imported earlier today; same function.
export const skillOf = scoreOf;

// A LEGACY RECORD IS TOPPED UP FROM THE LIFETIME TOTALS, ONCE. catStats began
// decaying on 2026-09-01 (0.98 per answer), so by the 9th every account's
// per-category record was its last ~100 answers — Alex's read 55/106, a 52%
// window, beside a Scouting Report saying "Accuracy 61%" from the same
// lifetime totals. Scored under the new model that window printed 58 ·
// BRONZE. Two true records, one card: until a record carries per-answer
// scores (s/n), the answers the window has forgotten are counted back in at
// the lifetime accuracy — as average difficulty, capped at LIFETIME_TOPUP so
// the card stays dynamic once new answers arrive. Once any key carries s/n
// the top-up stops: from there the card is the player's own scored answers.
export const LIFETIME_TOPUP = 300;

/** The lifetime top-up for a legacy record, or null. {s, n} in score units. */
export function legacyTopUp(catStats = {}, lifetime) {
  if (!lifetime || !(lifetime.a > 0) || !(lifetime.c >= 0) || lifetime.c > lifetime.a) return null;
  // ⚠️ A MISSING totalCorrect IS NOT ZERO CORRECT. 130 of 308 prod profiles
  // carry `totalAnswered` with `totalCorrect` NULL, and every caller writes
  // `stats.totalCorrect || 0` — so those cards topped themselves up with a
  // lifetime record asserting NONE RIGHT out of a thousand answered, and every
  // rating was dragged toward the floor. Alex, seeing a friend's card: "there
  // is no way he has all those stats under 50." He was right: that player read
  // 67 with faces 49/40/40/55/40/51, and 73 with 53/43/40/60/40/55 once this
  // stopped counting. A lifetime with answers but no correct count is MISSING
  // DATA — the only honest thing to do is not top up at all.
  if (lifetime.a >= 1 && !(lifetime.c > 0)) return null;
  let n = 0;
  for (const cs of Object.values(catStats || {})) n += scoreOf(cs).n;
  if (lifetime.a <= n) return null;
  const extra = Math.min(LIFETIME_TOPUP, lifetime.a - n);
  return { s: AVG_MULT * (lifetime.c / lifetime.a) * extra, n: extra };
}

/**
 * Spread a legacy record's lifetime top-up across its keys IN PROPORTION to
 * each key's own answers, returning a new map (c/a untouched). Alex, on build
 * 117: "the ratings on the card went down but the overall went up? the
 * individual ratings also have to be boosted". The top-up used to live on a
 * single overall-only key, so the overall carried ~200 answers the faces
 * never saw and sat ABOVE every rated league — arithmetic no player can
 * follow. Proportional spreading keeps overall = answers-weighted mean of the
 * keys, keeps each league's ORDER (the weak league stays weakest), and gates
 * stay on the key's OWN answers (`a`), so a four-answer league does not become
 * "rated" by borrowed ones.
 */
/**
 * The same spread, MATERIALISED as raw counts instead of a parallel score.
 *
 * Used by recordAnswers on the first write to a legacy record. withLegacyTopUp
 * above is a READ-TIME view: it writes s/n, which is right for computeCard
 * (transient, thrown away each render) and wrong to store, because since
 * 2026-09-10 s/n means "pre-summed by the fold" and outranks raw counts — a
 * stored top-up would win over every answer played afterwards and a perfect
 * round would LOWER the card. That is the "ten hard rights took me 65 → 63"
 * bug, and its unit test caught this the moment scoreOf changed.
 *
 * A top-up is by definition "this many more answers, at the player's lifetime
 * accuracy, at average difficulty" — which is precisely what the `u` bucket
 * says. Storing it there needs no second representation, and ROUNDS: `d` holds
 * whole questions, and keeping it integral is the point of the whole rebuild.
 */
export function materialiseLegacyTopUp(catStats = {}, lifetime) {
  const topped = withLegacyTopUp(catStats, lifetime);
  if (topped === catStats) return catStats;
  const out = {};
  for (const [k, cs] of Object.entries(topped)) {
    const own = scoreOf(catStats[k]);
    const dn = Math.round((cs.n || 0) - own.n);
    const dc = Math.round(((cs.s || 0) - own.s) / AVG_MULT);
    const { s: _s, n: _n, ...rest } = cs;
    if (dn <= 0) { out[k] = rest; continue; }
    const d = { ...(rest.d || {}) };
    const cur = Array.isArray(d.u) ? d.u : [0, 0];
    d.u = [(cur[0] || 0) + Math.max(0, Math.min(dn, dc)), (cur[1] || 0) + dn];
    out[k] = { ...rest, d };
  }
  return out;
}

export function withLegacyTopUp(catStats = {}, lifetime) {
  const top = legacyTopUp(catStats, lifetime);
  if (!top) return catStats;
  let N = 0;
  for (const cs of Object.values(catStats || {})) N += scoreOf(cs).n;
  if (!(N > 0)) return catStats;
  const out = {};
  for (const [k, cs] of Object.entries(catStats || {})) {
    const own = scoreOf(cs);
    const share = own.n / N;
    out[k] = { ...cs, s: own.s + top.s * share, n: own.n + top.n * share };
  }
  return out;
}

/**
 * A key's RAW answer count for the print gates. Since the writer keeps raw
 * per-difficulty counts in `d`, those are the truth; a legacy record falls
 * back to its (decayed) `a`. ⚠️ Gates must not read the decayed `a` on scored
 * records: with decay 0.995 the tenth answer leaves `a` at 9.78 and "10 to
 * get rated" never reaches zero.
 */
export function rawAnswered(cs) {
  if (!cs) return 0;
  const d = cs.d;
  let fromD = 0;
  if (d && typeof d === "object") {
    for (const k of ["e", "m", "h", "u"]) fromD += (Array.isArray(d[k]) ? (d[k][1] || 0) : 0);
  }
  // ⚠️ THE MAX OF BOTH, NEVER `d` ALONE. `d` counts only answers recorded
  // since the 2026-09-09 rebuild; `a` is the decayed running count and
  // carries everything before it. Preferring `d` the moment it existed meant
  // ONE new answer replaced a whole legacy history with "1" — so a face with
  // forty answers behind it, printing a rating, went to a DASH the moment its
  // owner played it. Alex on build 125: "4 of the items on the scorecard are
  // gone, this was never an issue in 1.7.2." Reproduced exactly: INT 72 → —
  // after a single CORRECT answer.
  //
  // Both terms are needed, which is why this is a max and not a swap back:
  //   · `a` alone never opens the gate for a NEW player — decay leaves it at
  //     9.78 after ten answers, so the tenth never rates them (the bug `d`
  //     was introduced to fix).
  //   · `d` alone discards every pre-rebuild answer, which is this bug.
  // max() satisfies both, and it makes the invariant structural: playing a
  // category can only ever raise its answer count.
  return Math.max(fromD, cs.a || 0);
}

/** True once any key carries per-answer scores (the record is no longer legacy). */
/**
 * Does this record carry per-category evidence of its own?
 *
 * The answer decides whether computeCard spreads the LIFETIME top-up across
 * the faces (a legacy record, where all we know is one global total) or reads
 * the record's own numbers. Get it wrong in the "no" direction and every
 * player's six faces print the same number forever.
 *
 * ⚠️ IT MUST TEST BOTH SCHEMES. This asked only about `s`/`n` and became
 * permanently false the moment recordAnswers stopped deriving them
 * (2026-09-10) — every card in the app would have fallen back to the top-up
 * for good, which is the "all six items read 55" shape Alex has already been
 * shown once. Raw `d` counts are now the primary evidence and s/n the legacy
 * one; either counts.
 */
export function isScored(catStats = {}) {
  return Object.values(catStats || {}).some(v =>
    (Number.isFinite(v?.s) && Number.isFinite(v?.n) && v.n > 0) ||
    (v?.d && typeof v.d === "object" && ["e", "m", "h", "u"].some(k => Array.isArray(v.d[k]) && (v.d[k][1] || 0) > 0))
  );
}

// Per-answer decay of every key's score record. 0.995: half-life ~140
// answers — the card reflects "you", moves within a fortnight of daily play.
export const CAT_DECAY = 0.995;

/**
 * THE WRITER. Folds a finished round's answers into catStats and returns the
 * new map. Lives here, not in App.jsx, so the arithmetic that decides every
 * card is unit-tested beside the model that reads it.
 *
 * - each answer adds 1 to its key's RAW `d` bucket for that difficulty. That
 *   is the whole write: {s,n} are no longer derived and {c,a} are frozen at
 *   whatever a legacy record already carried (see the note in the loop).
 * - a key is filed under the face it feeds (faceCatFor), else its real cat.
 * - ON THE FIRST SCORED WRITE a legacy record's lifetime top-up (see
 *   legacyTopUp) is MATERIALISED as the `_legacy` key and thereafter decays
 *   like every other key. Without this the top-up vanished at the first scored
 *   quiz and ten hard rights LOWERED a card from 65 to 63 — the exact
 *   "it goes down the more I play" this whole day was about.
 */
export function recordAnswers(prevCatStats = {}, answers = [], lifetime) {
  const catStats = { ...(prevCatStats || {}) };
  const list = (answers || []).filter(a => a && a.cat);
  if (!list.length) return catStats;
  // ON THE FIRST SCORED WRITE a legacy record's lifetime top-up is spread
  // into its keys (see withLegacyTopUp) — materialised, so it decays with
  // every later answer instead of vanishing. As a switch it vanished at the
  // first scored quiz and ten hard rights LOWERED a card 65 → 63.
  let base = catStats;
  if (!isScored(catStats)) base = materialiseLegacyTopUp(catStats, lifetime);
  const outStats = { ...base };
  for (const ans of list) {
    const key = faceCatFor(ans) || ans.cat;
    const cur = outStats[key] || { c: 0, a: 0 };
    const ok = ans.isCorrect ? 1 : 0;
    const diff = (ans.diff === "easy" || ans.diff === "hard") ? ans.diff : "medium";
    // ⚠️ ONLY `d` IS WRITTEN NOW — raw integer counts, no decay, no derived
    // s/n. The old writer fed scoreOf's output back through CAT_DECAY, which
    // is what produced "26.78 correct": a number that is not a count, cannot
    // be shown to a player, and SATURATES at 200 answers however much they
    // play. Alex: "how do you answer 26.78 questions right with decimals?"
    //
    // Existing c/a are left EXACTLY as they are. scoreOf reads the exact part
    // from `d` and lets the frozen decayed totals carry only whatever they
    // still claim beyond it, so the estimated share shrinks with every answer
    // and a card becomes fully verifiable on its own. Freezing them rather
    // than deleting them is the same rule as rawAnswered's: never throw away
    // history you cannot reconstruct.
    const d = { ...(cur.d || {}) };
    const dk = diff[0];
    d[dk] = [((d[dk] || [0, 0])[0] || 0) + ok, ((d[dk] || [0, 0])[1] || 0) + 1];
    outStats[key] = { ...cur, d };
  }
  return outStats;
}

/**
 * The SAME evidence scoreOf reads, but unweighted: how many questions this
 * record got right, out of how many it answered.
 *
 * This exists so the Profile's "Accuracy" tile can be sourced from the answers
 * themselves instead of the lifetime counters, which are historically
 * inflated: `saveStats` added `newResult.score` to `totalCorrect` for EVERY
 * mode, and in four of them `score` is not a count of correct answers
 * (mp:race 29,584% of questions, mystery 2,606%, footle 358%, trail 126%).
 * 26,081 of the 32,769 "correct answers" the app has ever counted came from
 * those four. The writer is gated now, but every historic total is still
 * wrong, and a wrong 67% sitting beside an honest card is what made a real
 * player's card look broken when it was the only truthful number on screen.
 *
 * catStats is quiz-only — Footle, Trail, Mystery and multiplayer never write a
 * category here — so this is the app's one clean accuracy.
 *
 * ⚠️ NOT `rating / AVG_MULT`. That is the difficulty-ADJUSTED equivalent and
 * would print a number no player can check against their own answers. A tile
 * labelled "Accuracy" has to mean right ÷ answered. The rating sitting ABOVE
 * it is the point: it is higher because hard questions are worth more.
 */
export function rawScoreOf(cs) {
  if (!cs) return { c: 0, n: 0 };
  // pre-summed by computeCard's fold, exactly as scoreOf's s/n branch
  if (Number.isFinite(cs.rc) && Number.isFinite(cs.rn) && cs.rn > 0) return { c: cs.rc, n: cs.rn };
  let c = 0, n = 0;
  const d = cs.d;
  if (d && typeof d === "object") {
    for (const k of ["e", "m", "h", "u"]) {
      const b = d[k];
      if (!Array.isArray(b)) continue;
      c += (b[0] || 0); n += (b[1] || 0);
    }
  }
  const a = cs.a || 0, cc = cs.c || 0;
  const extra = a - n;
  if (extra > 0 && a > 0) { c += (cc / a) * extra; n += extra; }
  return { c, n };
}

/**
 * The player's overall — every category, shrunk toward the population
 * baseline with PRIOR_WEIGHT answers of weight. `lifetime` = {c, a} raw
 * totals (totalCorrect / totalAnswered), used only to top up a legacy record.
 */
export function overallScore(catStats = {}, lifetime) {
  // ⚠️ The caller decides whether `lifetime` applies (computeCard passes it
  // only while NO raw key carries s/n). It cannot be decided here: computeCard
  // folds aliases first, and the fold writes s/n onto every key.
  let s = 0, n = 0, own = 0;
  for (const cs of Object.values(catStats || {})) { const k = scoreOf(cs); s += k.s; n += k.n; own += rawAnswered(cs); }
  void lifetime; // spread by computeCard via withLegacyTopUp before this is called
  return { mean: (s + BASELINE * PRIOR_WEIGHT) / (n + PRIOR_WEIGHT), answered: own };
}

/** Kept for callers that think in accuracy. */
export function overallAccuracy(catStats = {}) {
  const { mean, answered } = overallScore(catStats);
  return { acc: mean / AVG_MULT, answered };
}

// One face. Shrunk toward the player's OVERALL mean with weight 2 — the right
// prior for "how would they do in this league" — but a face is only PRINTED
// from PROVISIONAL_ANSWERS (muted) and fully from MIN_RATED_ANSWERS.
// ⚠️ Nothing sums faces to make the overall; see overallScore().
// ⚠️ A FACE IS DAMPED LESS THAN THE OVERALL, DELIBERATELY — but not by 2.
// This was a bare `2` while the overall uses PRIOR_WEIGHT (20), which is a
// tenth of the damping on a tenth of the data: a face printed 99 from eight
// answers and 40 from three, then drifted. That is the "kept getting lower"
// shape from Alex's very first device review, and it was visible on a real
// rendered card (the WORLD face printing 99 off eight PL answers).
//
// The two weights differ on purpose. The overall pools every answer, so 20 is
// a small correction there; a face holds tens of answers, where 20 would
// dominate — at that weight a perfect 8/8 and a solid 30/40 both read 77 and
// the card stops saying where you are strong, which is its whole job. 8 puts
// a face at the 10-answer gate on roughly 55% its own evidence: enough to
// listen to the player, enough to stop a hot streak printing 99.
//   8/8 -> 87 (was 99) · 9/10 -> 83 (93) · 3/10 -> 47 (40) · 30/40 -> 79 (82)
export const FACE_PRIOR_WEIGHT = 8;
export function compRating(cs, priorAcc = CALIBRATION.median) {
  const { s, n } = scoreOf(cs);
  const p = Number.isFinite(priorAcc) ? priorAcc : CALIBRATION.median;
  const priorMean = Math.max(0.25, Math.min(0.75, p)) * AVG_MULT;
  return ratingFromScore((s + priorMean * FACE_PRIOR_WEIGHT) / (n + FACE_PRIOR_WEIGHT));
}

// BRONZE / SILVER / GOLD. Alex, 2026-08-26: "maybe we should have silver cards
// from 60-74 and gold above that? and bronze below 60? i think maybe the green
// color is worse than silver".
//
// He is right, and for a reason this codebase already had written down: GREEN
// IN THIS APP MEANS CORRECT AND GO. The mode grid was de-greened for exactly
// that reason — nine green icons meant the eye could not rank them — and a
// green TIER competes with green-as-correct in the same way. Bronze/silver/gold
// is also a ladder every football fan already reads, where "prospect / pro /
// elite" had to be learned.
//
// Against the measured population (2026-09-09): the median player rates ~64
// (silver), 75 needs ~68% on medium or ~63% on hard — roughly the top fifth.
export function cardTier(overall) {
  if (overall >= 75) return "gold";
  if (overall >= 60) return "silver";
  return "bronze";
}

// Tier palettes. Shared by the in-app card header and the share render
// (api/og.js imports these — keep this module the single source of truth).
export const CARD_TIERS = {
  gold:   { bg: "linear-gradient(160deg,#2a2410 0%,#0B0C10 100%)", accent: "#FFC107", text: "#FFF6E0", label: "GOLD" },
  silver: { bg: "linear-gradient(160deg,#1b212a 0%,#080a0f 100%)", accent: "#C7D2E0", text: "#EDF1F7", label: "SILVER" },
  bronze: { bg: "linear-gradient(160deg,#2a1a0e 0%,#0b0705 100%)", accent: "#D08A4E", text: "#F6E7D8", label: "BRONZE" },
};

// ⚠️ OLD SHARE LINKS MUST STILL RENDER. api/og.js takes the tier key from a URL
// parameter, and every /p?... card already sitting in somebody's chat history
// carries elite / pro / prospect. Renaming the keys without this would drop all
// of them to a default palette — a silent regression in the one artefact that
// outlives every deploy.
const LEGACY_TIER = { elite: "gold", pro: "silver", prospect: "bronze" };

/** Resolve a tier key — current or legacy — to a palette. Never returns undefined. */
export function tierPalette(key) {
  return CARD_TIERS[key] || CARD_TIERS[LEGACY_TIER[key]] || CARD_TIERS.silver;
}

/**
 * The full card model.
 * @param catStats  per-key records
 * @param _priorAcc accepted for older call sites; unused (the overall is derived here)
 * @param lifetime  {c, a} raw lifetime totals — tops up a legacy record, see overallScore
 * @param pinnedLeague  the player's CHOSEN league face (a LEAGUE_FACES cat), or
 *                      undefined to let the card pick their most-played one
 */
// ⚠️ `u` IS IN THIS LIST AND MUST STAY. It holds every answer we have a record
// of but no difficulty grade for — 4,384 of the 4,825 in the live log, because
// Daily 7 only began storing `diff` this month. Leaving it out (as this did
// until 2026-09-10) silently dropped 91% of the evidence on the way to a face:
// the WORLD and LEGENDS faces on a 299-answer card read as if they had none.
function mergeD(a, b) {
  if (!a && !b) return null;
  const out = {};
  for (const k of ["e", "m", "h", "u"]) {
    const x = Array.isArray(a?.[k]) ? a[k] : [0, 0], y = Array.isArray(b?.[k]) ? b[k] : [0, 0];
    if (x[1] || y[1]) out[k] = [(x[0] || 0) + (y[0] || 0), (x[1] || 0) + (y[1] || 0)];
  }
  return Object.keys(out).length ? out : null;
}

export function computeCard(catStats = {}, _priorAcc, lifetime, pinnedLeague) {
  // Fold aliases into their face BEFORE reading, so a profile carrying both
  // `ChampionsLeague` and `UCL` (46 in prod) rates one Champions League.
  // The player's own league keeps its slot; every OTHER league folds into Clubs
  // for this render only. Nothing is written back, so the fold is reversible
  // and a league face can change without losing a single answer.
  const leagueCat = pickLeagueFace(catStats, pinnedLeague).cat;
  const folded = {};
  for (const [k, v] of Object.entries(catStats || {})) {
    if (EXCLUDED_CATS.has(k)) continue;   // see EXCLUDED_CATS — not knowledge
    const key = k === leagueCat ? k : (LEAGUE_CATS.has(k) ? "Clubs" : (FACE_ALIAS[k] || k));
    const cur = folded[key] || { s: 0, n: 0, rc: 0, rn: 0, c: 0, a: 0 };
    // ⚠️ SCORE EACH MEMBER, THEN SUM — and the sum is the ONLY score the
    // folded record carries. It deliberately keeps `d` and `c`/`a` too, for
    // rawAnswered's gates and the progress bar, which means the record holds
    // the same evidence twice over. scoreOf therefore reads s/n FIRST: when
    // this pre-summed form was scored from its raw halves instead, it counted
    // the merged `d` (then missing `u`) against a summed `a` and discarded the
    // correct total — a 299-answer card came out at 50 instead of 55.
    const sk = scoreOf(v);
    const rk = rawScoreOf(v);   // the same members, unweighted — see rawScoreOf
    const d = mergeD(cur.d, v?.d);
    folded[key] = { s: cur.s + sk.s, n: cur.n + sk.n, rc: cur.rc + rk.c, rn: cur.rn + rk.n,
      c: cur.c + (v?.c || 0), a: cur.a + (v?.a || 0), ...(d ? { d } : {}) };
  }
  // Legacy = no raw key carries per-answer scores yet; only then does the
  // lifetime top-up apply (see overallScore).
  // A legacy record (no key scored yet) is rated WITH its lifetime top-up
  // spread across its keys — the same view recordAnswers will materialise.
  const rated = isScored(catStats) ? folded : withLegacyTopUp(folded, lifetime);
  const { mean, answered: answeredTotal } = overallScore(rated);
  const acc = mean / AVG_MULT;
  const overall = ratingFromScore(mean);
  const ratings = cardCompsFor(catStats, pinnedLeague).map(comp => {
    const cs = rated[comp.cat];
    // Gates count the league's OWN answers (raw), never borrowed ones.
    const answered = rawAnswered(cs);
    return {
      abbr: comp.abbr, cat: comp.cat, name: comp.name, short: comp.short || comp.name, icon: comp.icon, color: comp.color,
      rating: compRating(cs, acc),
      answered,
      // Per-face honesty: a face prints FULLY only from its own data; from
      // PROVISIONAL_ANSWERS it prints muted (see the constant).
      rated: answered >= MIN_RATED_ANSWERS,
      provisional: answered >= PROVISIONAL_ANSWERS && answered < MIN_RATED_ANSWERS,
    };
  });
  // `rated` travels WITH the card so every consumer inherits one answer to
  // "is there enough data to print a number?". Four surfaces once asked it four
  // ways and three got it wrong (a friend card printed 85 · GOLD off one
  // answer; the OG unfurl published six invented ratings).
  // Right / answered over the same records the rating is built from. `null`
  // when there is nothing to divide, so a caller can tell "no data" from 0%.
  let rc = 0, rn = 0;
  for (const cs of Object.values(rated)) { const r = rawScoreOf(cs); rc += r.c; rn += r.n; }
  return {
    ratings, overall, tier: cardTier(overall), answeredTotal,
    rated: answeredTotal >= MIN_RATED_ANSWERS,
    accuracy: acc,
    rawAccuracy: rn > 0 ? rc / rn : null,
    rawAnswered: rn,
    mean,
    calibration: { measured: CALIBRATION.measured, n: CALIBRATION.n },
  };
}

/**
 * What a round did to the card, for the results screen: overall before/after
 * and every face that moved. Pure — both sides are computeCard() over the
 * records the writer had before and after recordAnswers().
 */
export function cardDelta(prevCatStats, nextCatStats, prevLifetime, nextLifetime) {
  const before = computeCard(prevCatStats || {}, undefined, prevLifetime);
  const after = computeCard(nextCatStats || {}, undefined, nextLifetime);
  const faces = after.ratings
    .map((r, i) => ({ abbr: r.abbr, name: r.name, color: r.color, before: before.ratings[i].rating, after: r.rating,
                       shown: r.rated || r.provisional, wasShown: before.ratings[i].rated || before.ratings[i].provisional }))
    .filter(f => f.shown && (f.before !== f.after || !f.wasShown));
  return {
    before: before.overall, after: after.overall, ratedBefore: before.rated, ratedAfter: after.rated,
    answered: after.answeredTotal, toRated: Math.max(0, MIN_RATED_ANSWERS - Math.floor(after.answeredTotal)),
    faces,
  };
}

// ── THE SHARE LINE ────────────────────────────────────────────────────────────
// "My Ball IQ is 68. Can you beat me?" led with the one number that means the
// least to a stranger. The share leads with the strongest league — the thing
// worth bragging about — and, when the last round moved it today, the move.
const DELTA_KEY = "biq_last_card_delta";
const dayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };

/** Remember what the last round did (the writer calls this); read back the same day only. */
export function storeCardDelta(delta) {
  try { if (delta) localStorage.setItem(DELTA_KEY, JSON.stringify({ day: dayKey(), delta })); } catch { /* ignore */ }
}
export function readCardDelta() {
  try {
    const v = JSON.parse(localStorage.getItem(DELTA_KEY) || "null");
    return v && v.day === dayKey() ? v.delta : null;
  } catch { return null; }
}

/** One line for the share sheet. Unrated cards say so; rated ones lead with the best face. */
export function shareLine(card, delta = null, appName = "Ball IQ") {
  if (!card || !card.rated) return `Can you beat me at ${appName}? ⚽`;
  const faces = card.ratings.filter(r => r.rated).sort((a, b) => b.rating - a.rating);
  const best = faces[0];
  const moved = delta && delta.ratedAfter && delta.faces && delta.faces.find(f => f.after > f.before);
  const head = best ? `${appName} ${card.overall} · ${best.abbr} ${best.rating}` : `${appName} ${card.overall}`;
  const move = moved ? ` — ${moved.abbr} ${moved.before} → ${moved.after} today` : "";
  return `${head}${move}. Can you beat me? ⚽`;
}

// ── THE WEB QUEUE ─────────────────────────────────────────────────────────────
// A club page on the same origin queues its finished round's answers here
// (scripts/seo/club-quiz-engine.js, queueForApp) rather than scoring them —
// one writer, no duplicated arithmetic. The app drains the queue on boot and
// feeds it to recordAnswers() like any other round. It counts toward the CARD
// only: a round played on the website earns no XP, no streak and no
// gamesPlayed, because none of those happened in the app.
export const PENDING_KEY = "biq_pending_rounds";

/**
 * Take everything the web queued, clearing it first so a failure downstream
 * cannot double-count. Returns validated answers ({cat, diff, isCorrect}).
 */
export function drainPendingRounds() {
  let raw = null;
  try {
    raw = localStorage.getItem(PENDING_KEY);
    if (!raw) return [];
    localStorage.removeItem(PENDING_KEY); // claim before use
  } catch { return []; }
  let list;
  try { list = JSON.parse(raw); } catch { return []; }
  if (!Array.isArray(list)) return [];
  // ⚠️ ACCEPT ALIASES, NOT JUST FACES. A club page's `data-face` is stamped at
  // BUILD time from CLUB_NAME_TO_COMP, so pages already in the wild carry the
  // pre-2026-09-10 values ("LaLiga", "SerieA", "Bundesliga"). Filtering on the
  // face list alone would have silently dropped every queued round from every
  // page built before the re-cut — the drain would look fine and land nothing.
  // Normalise here so the queue survives the change in both directions.
  const FACES = new Set(CARD_COMPS.map(c => c.cat));
  const faceOf = (c) => (FACES.has(c) ? c : (FACE_ALIAS[c] || null));
  return list
    .filter(a => a && faceOf(a.cat) && typeof a.isCorrect === "boolean")
    .slice(0, 400)
    .map(a => ({ cat: faceOf(a.cat), diff: (a.diff === "easy" || a.diff === "hard") ? a.diff : "medium", isCorrect: a.isCorrect }));
}
