import { MIN_RATED_ANSWERS } from './scoring.js';
import { CALIBRATION } from '../data/cardCalibration.js';
import { CLUB_NAME_TO_COMP } from '../data/clubPackColours.js';
// Ball IQ player-rating card — six "competition" face stats + a compiled overall
// + a Bronze / Silver / Gold tier.
//
// catStats shape (from saveStats): { [cat]: { c, a } } — c and a are
// DIFFICULTY-WEIGHTED and RECENCY-DECAYED (saveStats: DIFF_CREDIT / DIFF_MISS /
// CAT_DECAY), so c/a is "how well, lately, for how hard", not a raw ratio.
//
// ── THE 2026-09-09 REBUILD — three defects, one measured population ──────────
// 1. The overall was the MEAN OF THE SIX FACES, unplayed faces included at an
//    invented prior. Three dashes on the card, three invented numbers in the 71
//    above them.
// 2. The prior for every unplayed face was the player's OWN running accuracy.
//    Two early rights set all six to gold; every answer after was decay toward
//    the truth — a real player's "it keeps going down the more I play".
// 3. HALF OF ALL ANSWERS NEVER REACHED THE CARD. Club quiz re-tags every row
//    cat:"ClubQuiz" (the single biggest bucket in prod — 2,039 answers, ahead
//    of World Cup and PL), Survival is "chaos", and the theme categories
//    (History / Legends / Records / Managers / Transfers) feed no face. An
//    Arsenal fan who plays the Arsenal pack daily had an empty EPL stat.
// And the scale: 40 + 59·acc put the MEDIAN player (acc 0.58) at 74 and a third
// of everyone in gold, with 80% of players between 64 and 82. It could not tell
// good from great.
//
// NOW:
// - The overall is EVERY answer, all modes, smoothed toward the population
//   median with PRIOR_WEIGHT answers of weight — starts mid-table, moves in
//   both directions with evidence, and a steady player converges rather than
//   drifting.
// - The scale is CALIBRATED to the measured population (src/data/
//   cardCalibration.js, generated by scripts/calibrate-card.mjs): p50 → 65,
//   p75 → 75, so GOLD MEANS TOP QUARTER. Tiers stay 60 / 75.
// - Club play FEEDS THE FACES: faceCatFor() routes an answer by its real
//   category, or by its club's league (Arsenal → PL, Juventus → SerieA). The
//   saveStats writer files each answer under its face when it has one.
// - A face prints only from its own data (≥ MIN_RATED_ANSWERS); the overall
//   never derives from the faces.
// - SCORE ABOVE EXPECTATION, not accuracy (later the same day). Each answer
//   scores (correct ? 1 : 0) − EXPECTED[difficulty]: a hard right earns 0.55,
//   an easy right 0.20, an easy miss costs 0.80, a hard miss 0.45. The old
//   evidence weights ranked 80% on easy above 50% on hard; this ranks them
//   the way the population does. catStats keys carry {s, n} (decayed skill
//   sum and count) beside the legacy {c, a}; a record with no s/n converts as
//   s = c − PBAR·a, which is exact for average difficulty and is what the
//   calibration was measured on.

// The six face stats. `cat` maps to the question bank's cat field; `abbr` is the
// 3-letter card label (the competition's short code).
// `icon` uses country flags (license-safe, unlike the trademarked competition
// logos). England flag for the PL, a star for the UCL, a globe for international.
// `color` is the competition's own colour, and it must stay equal to the one
// LEAGUE_QUIZ_SECTIONS (App.jsx) uses for the same `cat` — the quiz picker and
// the rating card naming the same competition in two different colours is the
// drift this app keeps producing. Pinned by tests/unit/card-comp-colours.test.js.
export const CARD_COMPS = [
  { abbr: "EPL", cat: "PL",         name: "Premier League",   icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#3D195B" },
  { abbr: "UCL", cat: "UCL",        name: "Champions League", icon: "⭐", color: "#123A8F" },
  { abbr: "INT", cat: "WorldCup",   name: "International",     icon: "🌍", color: "#8A6D1B" },
  { abbr: "LAL", cat: "LaLiga",     name: "La Liga",          icon: "🇪🇸", color: "#EE8707" },
  { abbr: "BUN", cat: "Bundesliga", name: "Bundesliga",       icon: "🇩🇪", color: "#D20515" },
  { abbr: "SEA", cat: "SerieA",     name: "Serie A",          icon: "🇮🇹", color: "#0578D3" },
];

// Bank categories that ARE a face under another name. `ChampionsLeague` is a
// legacy key still present in 46 prod profiles beside `UCL`; `Euros` is
// international football and belongs with the World Cup on the INT face.
export const FACE_ALIAS = { ChampionsLeague: "UCL", Euros: "WorldCup" };

const FACE_CATS = new Set(CARD_COMPS.map(c => c.cat));

/**
 * Which face an answer feeds, or null (overall only).
 * Order: the answer's real category (club quiz carries it as `realCat` beside
 * the UI re-tag), then an alias, then the club's league.
 */
export function faceCatFor(ans) {
  if (!ans) return null;
  const cat = ans.realCat || ans.cat;
  if (FACE_CATS.has(cat)) return cat;
  if (FACE_ALIAS[cat]) return FACE_ALIAS[cat];
  if (ans.club && CLUB_NAME_TO_COMP[ans.club]) return CLUB_NAME_TO_COMP[ans.club];
  return null;
}

// Prior weight, in answers, for the overall — how many answers the population
// median "counts as" before the player's own record takes over.
//
// TWENTY, NOT TEN, AND THE DIRECTION IS THE POINT. The calibrated scale is
// steep where players actually live (0.58 → 65, 0.82 → 93: 28 points across
// 0.24 of accuracy), so at ten answers the noise in a record is ±15 rating
// points. Simulated with weight 10, a lucky 8/10 start printed 79 · GOLD, then
// slid to 71 · SILVER over the next thirty answers at a true 65% — the exact
// "it keeps going down" a real player reported. With weight 20 the same run
// prints 73 and settles at 70: a three-point correction, no tier flip. And a
// STEADY above-median player now RISES toward their level (68 → 72 → 75)
// rather than starting above it and falling. Shrinkage toward the median is
// honest — with little evidence you are assumed near the middle — and it makes
// the common experience "the more I play, the more it reflects me", which is
// the only direction a rating should surprise in. Twenty ≈ two club quizzes.
export const PRIOR_WEIGHT = 20;

/** Expected score for a difficulty label; unknown labels count as medium. */
export const EXPECTED = CALIBRATION.expected;
export const PBAR = CALIBRATION.pbar;
export function expectedFor(diff) { return EXPECTED[diff] ?? EXPECTED.medium; }

function interpolate(anchors, x) {
  for (let i = 1; i < anchors.length; i++) {
    const [x0, y0] = anchors[i - 1], [x1, y1] = anchors[i];
    if (x <= x1) return Math.max(40, Math.min(99, Math.round(y0 + (y1 - y0) * ((x - x0) / (x1 - x0)))));
  }
  return 99;
}

/** Skill (mean score above expectation, −1…1) → 40-99 through the calibrated anchors. */
export function ratingFromSkill(skill) {
  const A = CALIBRATION.skillAnchors;
  const x = Math.max(A[0][0], Math.min(A[A.length - 1][0], Number.isFinite(skill) ? skill : A[0][0]));
  return interpolate(A, x);
}

/** Plain accuracy → rating, for a record of average difficulty (legacy conversion). */
export function ratingFromAccuracy(acc) {
  const x = Number.isFinite(acc) ? Math.max(0, Math.min(1, acc)) : CALIBRATION.median;
  return interpolate(CALIBRATION.anchors, x);
}

/**
 * A key's skill record. New writes carry {s, n}; a legacy {c, a} converts as
 * s = c − PBAR·a (exact for average difficulty). Both may be present after
 * the upgrade — the writer keeps c/a for the progress bar and the merge.
 */
export function skillOf(cs) {
  if (!cs) return { s: 0, n: 0 };
  if (Number.isFinite(cs.s) && Number.isFinite(cs.n) && cs.n > 0) return { s: cs.s, n: cs.n };
  const c = cs.c || 0, a = cs.a || 0;
  return { s: c - PBAR * a, n: a };
}

/** The population's median skill — where a card with no evidence sits (65). */
export const MEDIAN_SKILL = CALIBRATION.median - PBAR;

/**
 * The player's overall skill — every category, shrunk toward the POPULATION
 * MEDIAN with PRIOR_WEIGHT answers of weight. Toward the median, not toward
 * "par at every difficulty" (skill 0): the measured median sits a little
 * under par (0.58 vs PBAR 0.61), and an unplayed card must read 65 — the
 * median player — not 68, or the first answers would appear to LOWER it.
 */
export function overallSkill(catStats = {}) {
  let s = 0, n = 0;
  for (const cs of Object.values(catStats || {})) { const k = skillOf(cs); s += k.s; n += k.n; }
  return { skill: (s + MEDIAN_SKILL * PRIOR_WEIGHT) / (n + PRIOR_WEIGHT), answered: n };
}

/** Kept for callers that think in accuracy: the overall as an accuracy-equivalent. */
export function overallAccuracy(catStats = {}) {
  const { skill, answered } = overallSkill(catStats);
  return { acc: skill + PBAR, answered };
}

// One face. Shrunk toward the player's OVERALL skill with weight 2 — the right
// prior for "how would they do in this league" — but a face is only PRINTED
// once it has MIN_RATED_ANSWERS of its own, where weight 2 is a nudge.
// ⚠️ Nothing sums faces to make the overall; see overallSkill().
export function compRating(cs, priorAcc = CALIBRATION.median) {
  const { s, n } = skillOf(cs);
  const p = Number.isFinite(priorAcc) ? priorAcc : CALIBRATION.median;
  // Callers pass an accuracy; clamp it to [0.25, 0.75] as before, then to skill.
  const priorSkill = Math.max(0.25, Math.min(0.75, p)) - PBAR;
  return ratingFromSkill((s + priorSkill * 2) / (n + 2));
}

// BRONZE / SILVER / GOLD. Alex, 2026-08-26: "maybe we should have silver cards
// from 60-74 and gold above that? and bronze below 60? i think maybe the green
// color is worse than silver".
//
// He is right, and for a reason this codebase already had written down: GREEN
// IN THIS APP MEANS CORRECT AND GO. The mode grid was de-greened for exactly
// that reason — nine green icons meant the eye could not rank them — and a
// green TIER competes with green-as-correct in the same way. Bronze/silver/gold
// is also a ladder every football fan already reads, where "prospect / pro /
// elite" had to be learned.
//
// Since the 2026-09-09 calibration the cuts MEAN something: 75 is the measured
// 75th percentile (gold = top quarter), 60 falls at roughly the 35th.
export function cardTier(overall) {
  if (overall >= 75) return "gold";
  if (overall >= 60) return "silver";
  return "bronze";
}

// Tier palettes. Shared by the in-app card header and the share render
// (api/og.js imports these — keep this module the single source of truth).
export const CARD_TIERS = {
  gold:   { bg: "linear-gradient(160deg,#2a2410 0%,#0B0C10 100%)", accent: "#FFC107", text: "#FFF6E0", label: "GOLD" },
  silver: { bg: "linear-gradient(160deg,#1b212a 0%,#080a0f 100%)", accent: "#C7D2E0", text: "#EDF1F7", label: "SILVER" },
  bronze: { bg: "linear-gradient(160deg,#2a1a0e 0%,#0b0705 100%)", accent: "#D08A4E", text: "#F6E7D8", label: "BRONZE" },
};

// ⚠️ OLD SHARE LINKS MUST STILL RENDER. api/og.js takes the tier key from a URL
// parameter, and every /p?... card already sitting in somebody's chat history
// carries elite / pro / prospect. Renaming the keys without this would drop all
// of them to a default palette — a silent regression in the one artefact that
// outlives every deploy.
const LEGACY_TIER = { elite: "gold", pro: "silver", prospect: "bronze" };

/** Resolve a tier key — current or legacy — to a palette. Never returns undefined. */
export function tierPalette(key) {
  return CARD_TIERS[key] || CARD_TIERS[LEGACY_TIER[key]] || CARD_TIERS.silver;
}

/**
 * The full card model.
 * The second parameter is accepted for the eleven call sites that still pass a
 * raw-count accuracy; it is no longer used — the overall is derived here, from
 * the same weighted record every face uses, so no surface can disagree.
 */
export function computeCard(catStats = {}, _unusedPriorAcc) {
  // Fold aliases into their face BEFORE reading, so a profile carrying both
  // `ChampionsLeague` and `UCL` (46 in prod) rates one Champions League.
  const folded = {};
  for (const [k, v] of Object.entries(catStats || {})) {
    const key = FACE_ALIAS[k] || k;
    const cur = folded[key] || { s: 0, n: 0, c: 0, a: 0 };
    const sk = skillOf(v);
    folded[key] = { s: cur.s + sk.s, n: cur.n + sk.n, c: cur.c + (v?.c || 0), a: cur.a + (v?.a || 0) };
  }
  const { skill, answered: answeredTotal } = overallSkill(folded);
  const acc = skill + PBAR;
  const overall = ratingFromSkill(skill);
  const ratings = CARD_COMPS.map(comp => {
    const cs = folded[comp.cat];
    const answered = skillOf(cs).n;
    return {
      abbr: comp.abbr, cat: comp.cat, name: comp.name, icon: comp.icon, color: comp.color,
      rating: compRating(cs, acc),
      answered,
      // Per-face honesty: a face prints only from its own data.
      rated: answered >= MIN_RATED_ANSWERS,
    };
  });
  // `rated` travels WITH the card so every consumer inherits one answer to
  // "is there enough data to print a number?". Four surfaces once asked it four
  // ways and three got it wrong (a friend card printed 85 · GOLD off one
  // answer; the OG unfurl published six invented ratings).
  return {
    ratings, overall, tier: cardTier(overall), answeredTotal,
    rated: answeredTotal >= MIN_RATED_ANSWERS,
    accuracy: acc,
    skill,
    calibration: { measured: CALIBRATION.measured, n: CALIBRATION.n },
  };
}
