import { MIN_RATED_ANSWERS } from './scoring.js';
import { CALIBRATION } from '../data/cardCalibration.js';
import { CLUB_NAME_TO_COMP } from '../data/clubPackColours.js';
// Ball IQ player-rating card — six "competition" face stats + a compiled overall
// + a Bronze / Silver / Gold tier.
//
// catStats shape (from saveStats): { [cat]: { c, a } } — c and a are
// DIFFICULTY-WEIGHTED and RECENCY-DECAYED (saveStats: DIFF_CREDIT / DIFF_MISS /
// CAT_DECAY), so c/a is "how well, lately, for how hard", not a raw ratio.
//
// ── THE 2026-09-09 REBUILD — three defects, one measured population ──────────
// 1. The overall was the MEAN OF THE SIX FACES, unplayed faces included at an
//    invented prior. Three dashes on the card, three invented numbers in the 71
//    above them.
// 2. The prior for every unplayed face was the player's OWN running accuracy.
//    Two early rights set all six to gold; every answer after was decay toward
//    the truth — a real player's "it keeps going down the more I play".
// 3. HALF OF ALL ANSWERS NEVER REACHED THE CARD. Club quiz re-tags every row
//    cat:"ClubQuiz" (the single biggest bucket in prod — 2,039 answers, ahead
//    of World Cup and PL), Survival is "chaos", and the theme categories
//    (History / Legends / Records / Managers / Transfers) feed no face. An
//    Arsenal fan who plays the Arsenal pack daily had an empty EPL stat.
// And the scale: 40 + 59·acc put the MEDIAN player (acc 0.58) at 74 and a third
// of everyone in gold, with 80% of players between 64 and 82. It could not tell
// good from great.
//
// NOW:
// - The overall is EVERY answer, all modes, smoothed toward the population
//   median with PRIOR_WEIGHT answers of weight — starts mid-table, moves in
//   both directions with evidence, and a steady player converges rather than
//   drifting.
// - The scale is CALIBRATED to the measured population (src/data/
//   cardCalibration.js, generated by scripts/calibrate-card.mjs): p50 → 65,
//   p75 → 75, so GOLD MEANS TOP QUARTER. Tiers stay 60 / 75.
// - Club play FEEDS THE FACES: faceCatFor() routes an answer by its real
//   category, or by its club's league (Arsenal → PL, Juventus → SerieA). The
//   saveStats writer files each answer under its face when it has one.
// - A face prints only from its own data (≥ MIN_RATED_ANSWERS); the overall
//   never derives from the faces.
// - THE NUMBER IS DIFFICULTY-WEIGHTED ACCURACY (Alex, later the same day):
//   a correct answer is worth 1.0 easy / 1.1 medium / 1.2 hard, a miss 0, the
//   rating is 100 × the mean. 61% on easy = 61, on medium = 67, on hard = 73.
//   It replaced a percentile-calibrated "score above expectation" model built
//   two hours earlier: that one was statistically right and could not be
//   explained on a card, and a number a player can verify beats one they
//   have to trust. catStats keys carry {s, n} beside the legacy {c, a}; a
//   record with no s/n converts as s = AVG_MULT·c (exact for average
//   difficulty). The population percentiles stay in the calibration file as
//   the reference for where the tiers fall: the measured median player rates
//   ~64, the 75th percentile ~74, the 90th ~79.

// The six face stats. `cat` maps to the question bank's cat field; `abbr` is the
// 3-letter card label (the competition's short code).
// `icon` uses country flags (license-safe, unlike the trademarked competition
// logos). England flag for the PL, a star for the UCL, a globe for international.
// `color` is the competition's own colour, and it must stay equal to the one
// LEAGUE_QUIZ_SECTIONS (App.jsx) uses for the same `cat` — the quiz picker and
// the rating card naming the same competition in two different colours is the
// drift this app keeps producing. Pinned by tests/unit/card-comp-colours.test.js.
export const CARD_COMPS = [
  { abbr: "EPL", cat: "PL",         name: "Premier League",   icon: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#3D195B" },
  { abbr: "UCL", cat: "UCL",        name: "Champions League", icon: "⭐", color: "#123A8F" },
  { abbr: "INT", cat: "WorldCup",   name: "International",     icon: "🌍", color: "#8A6D1B" },
  { abbr: "LAL", cat: "LaLiga",     name: "La Liga",          icon: "🇪🇸", color: "#EE8707" },
  { abbr: "BUN", cat: "Bundesliga", name: "Bundesliga",       icon: "🇩🇪", color: "#D20515" },
  { abbr: "SEA", cat: "SerieA",     name: "Serie A",          icon: "🇮🇹", color: "#0578D3" },
];

// Bank categories that ARE a face under another name. `ChampionsLeague` is a
// legacy key still present in 46 prod profiles beside `UCL`; `Euros` is
// international football and belongs with the World Cup on the INT face.
export const FACE_ALIAS = { ChampionsLeague: "UCL", Euros: "WorldCup" };

const FACE_CATS = new Set(CARD_COMPS.map(c => c.cat));

/**
 * Which face an answer feeds, or null (overall only).
 * Order: the answer's real category (club quiz carries it as `realCat` beside
 * the UI re-tag), then an alias, then the club's league.
 */
export function faceCatFor(ans) {
  if (!ans) return null;
  const cat = ans.realCat || ans.cat;
  if (FACE_CATS.has(cat)) return cat;
  if (FACE_ALIAS[cat]) return FACE_ALIAS[cat];
  if (ans.club && CLUB_NAME_TO_COMP[ans.club]) return CLUB_NAME_TO_COMP[ans.club];
  return null;
}

// A face with fewer than MIN_RATED_ANSWERS but at least this many prints a
// PROVISIONAL number — muted, never the accented "best" — instead of a bar.
// Alex, 2026-09-09, seeing La Liga / Bundesliga / Serie A as three bars after
// they had carried numbers: "where is the rating? in the shadow realms? it
// can not vanish like this". He is right about the feel: a number that was
// there and then is not reads as a loss, whatever the gate's statistics. Three
// answers is where the number stops being pure prior; shrinkage toward the
// overall (weight 2) keeps it believable until ten.
export const PROVISIONAL_ANSWERS = 3;

// Prior weight, in answers, for the overall — how many answers the population
// median "counts as" before the player's own record takes over.
//
// TWENTY, NOT TEN, AND THE DIRECTION IS THE POINT. The calibrated scale is
// steep where players actually live (0.58 → 65, 0.82 → 93: 28 points across
// 0.24 of accuracy), so at ten answers the noise in a record is ±15 rating
// points. Simulated with weight 10, a lucky 8/10 start printed 79 · GOLD, then
// slid to 71 · SILVER over the next thirty answers at a true 65% — the exact
// "it keeps going down" a real player reported. With weight 20 the same run
// prints 73 and settles at 70: a three-point correction, no tier flip. And a
// STEADY above-median player now RISES toward their level (68 → 72 → 75)
// rather than starting above it and falling. Shrinkage toward the median is
// honest — with little evidence you are assumed near the middle — and it makes
// the common experience "the more I play, the more it reflects me", which is
// the only direction a rating should surprise in. Twenty ≈ two club quizzes.
export const PRIOR_WEIGHT = 20;

/** Multiplier a correct answer earns, by difficulty. Unknown labels count as medium. */
export const MULT = CALIBRATION.mult;
export const AVG_MULT = CALIBRATION.avgMult;
/** The measured median player's rating, as a fraction (≈0.64): where a card with no evidence starts. */
export const BASELINE = CALIBRATION.baseline;
export function multFor(diff) { return MULT[diff] ?? MULT.medium; }

/** Mean score (0…1.2) → 40-99. Linear: 0.61 → 61. Capped at 99 — perfect on hard is 120. */
export function ratingFromScore(mean) {
  const x = Number.isFinite(mean) ? mean : BASELINE;
  return Math.max(40, Math.min(99, Math.round(x * 100)));
}

/** Kept for the calibration tests and any caller that thinks in accuracy: an average-difficulty record. */
export function ratingFromAccuracy(acc) {
  return ratingFromScore((Number.isFinite(acc) ? acc : CALIBRATION.median) * AVG_MULT);
}

/**
 * A key's score record. New writes carry {s, n} (decayed score sum and
 * answer count). A legacy {c, a} converts as s = AVG_MULT·c — exact for a
 * record of average difficulty; both may be present after the upgrade.
 */
export function scoreOf(cs) {
  if (!cs) return { s: 0, n: 0 };
  if (Number.isFinite(cs.s) && Number.isFinite(cs.n) && cs.n > 0) return { s: cs.s, n: cs.n };
  const c = cs.c || 0, a = cs.a || 0;
  return { s: AVG_MULT * c, n: a };
}
// The name the writer imported earlier today; same function.
export const skillOf = scoreOf;

// A LEGACY RECORD IS TOPPED UP FROM THE LIFETIME TOTALS, ONCE. catStats began
// decaying on 2026-09-01 (0.98 per answer), so by the 9th every account's
// per-category record was its last ~100 answers — Alex's read 55/106, a 52%
// window, beside a Scouting Report saying "Accuracy 61%" from the same
// lifetime totals. Scored under the new model that window printed 58 ·
// BRONZE. Two true records, one card: until a record carries per-answer
// scores (s/n), the answers the window has forgotten are counted back in at
// the lifetime accuracy — as average difficulty, capped at LIFETIME_TOPUP so
// the card stays dynamic once new answers arrive. Once any key carries s/n
// the top-up stops: from there the card is the player's own scored answers.
export const LIFETIME_TOPUP = 300;
export const LEGACY_KEY = "_legacy";

/** The lifetime top-up for a legacy record, or null. {s, n} in score units. */
export function legacyTopUp(catStats = {}, lifetime) {
  if (!lifetime || !(lifetime.a > 0) || !(lifetime.c >= 0) || lifetime.c > lifetime.a) return null;
  let n = 0;
  for (const cs of Object.values(catStats || {})) n += scoreOf(cs).n;
  if (lifetime.a <= n) return null;
  const extra = Math.min(LIFETIME_TOPUP, lifetime.a - n);
  return { s: AVG_MULT * (lifetime.c / lifetime.a) * extra, n: extra };
}

/** True once any key carries per-answer scores (the record is no longer legacy). */
export function isScored(catStats = {}) {
  return Object.values(catStats || {}).some(v => Number.isFinite(v?.s) && Number.isFinite(v?.n) && v.n > 0);
}

// Per-answer decay of every key's score record. 0.995: half-life ~140
// answers — the card reflects "you", moves within a fortnight of daily play.
export const CAT_DECAY = 0.995;

/**
 * THE WRITER. Folds a finished round's answers into catStats and returns the
 * new map. Lives here, not in App.jsx, so the arithmetic that decides every
 * card is unit-tested beside the model that reads it.
 *
 * - each answer scores (correct ? MULT[diff] : 0) into its key's {s, n}; {c, a}
 *   keep being written as plain decayed counts (progress bar, merge, older
 *   clients); `d` keeps RAW per-difficulty counts for the next calibration.
 * - a key is filed under the face it feeds (faceCatFor), else its real cat.
 * - ON THE FIRST SCORED WRITE a legacy record's lifetime top-up (see
 *   legacyTopUp) is MATERIALISED as the `_legacy` key and thereafter decays
 *   like every other key. Without this the top-up vanished at the first scored
 *   quiz and ten hard rights LOWERED a card from 65 to 63 — the exact
 *   "it goes down the more I play" this whole day was about.
 */
export function recordAnswers(prevCatStats = {}, answers = [], lifetime) {
  const catStats = { ...(prevCatStats || {}) };
  const list = (answers || []).filter(a => a && a.cat);
  if (!list.length) return catStats;
  if (!isScored(catStats)) {
    const top = legacyTopUp(catStats, lifetime);
    if (top) catStats[LEGACY_KEY] = { c: 0, a: 0, s: top.s, n: top.n };
  }
  for (const ans of list) {
    const key = faceCatFor(ans) || ans.cat;
    const cur = catStats[key] || { c: 0, a: 0 };
    const ok = ans.isCorrect ? 1 : 0;
    const diff = (ans.diff === "easy" || ans.diff === "hard") ? ans.diff : "medium";
    const prev = scoreOf(cur); // a legacy {c,a} converts once, here, then carries s/n
    const d = { ...(cur.d || {}) };
    const dk = diff[0];
    d[dk] = [((d[dk] || [0, 0])[0] || 0) + ok, ((d[dk] || [0, 0])[1] || 0) + 1];
    catStats[key] = {
      c: (cur.c || 0) * CAT_DECAY + ok,
      a: (cur.a || 0) * CAT_DECAY + 1,
      s: prev.s * CAT_DECAY + (ok ? multFor(diff) : 0),
      n: prev.n * CAT_DECAY + 1,
      d,
    };
    // The materialised top-up fades with every answer, whatever key it lands on.
    const lg = catStats[LEGACY_KEY];
    if (lg && key !== LEGACY_KEY) catStats[LEGACY_KEY] = { ...lg, s: (lg.s || 0) * CAT_DECAY, n: (lg.n || 0) * CAT_DECAY };
  }
  return catStats;
}

/**
 * The player's overall — every category, shrunk toward the population
 * baseline with PRIOR_WEIGHT answers of weight. `lifetime` = {c, a} raw
 * totals (totalCorrect / totalAnswered), used only to top up a legacy record.
 */
export function overallScore(catStats = {}, lifetime) {
  // ⚠️ The caller decides whether `lifetime` applies (computeCard passes it
  // only while NO raw key carries s/n). It cannot be decided here: computeCard
  // folds aliases first, and the fold writes s/n onto every key.
  let s = 0, n = 0;
  for (const cs of Object.values(catStats || {})) { const k = scoreOf(cs); s += k.s; n += k.n; }
  const top = legacyTopUp(catStats, lifetime);
  if (top) { s += top.s; n += top.n; }
  return { mean: (s + BASELINE * PRIOR_WEIGHT) / (n + PRIOR_WEIGHT), answered: n };
}

/** Kept for callers that think in accuracy. */
export function overallAccuracy(catStats = {}) {
  const { mean, answered } = overallScore(catStats);
  return { acc: mean / AVG_MULT, answered };
}

// One face. Shrunk toward the player's OVERALL mean with weight 2 — the right
// prior for "how would they do in this league" — but a face is only PRINTED
// from PROVISIONAL_ANSWERS (muted) and fully from MIN_RATED_ANSWERS.
// ⚠️ Nothing sums faces to make the overall; see overallScore().
export function compRating(cs, priorAcc = CALIBRATION.median) {
  const { s, n } = scoreOf(cs);
  const p = Number.isFinite(priorAcc) ? priorAcc : CALIBRATION.median;
  const priorMean = Math.max(0.25, Math.min(0.75, p)) * AVG_MULT;
  return ratingFromScore((s + priorMean * 2) / (n + 2));
}

// BRONZE / SILVER / GOLD. Alex, 2026-08-26: "maybe we should have silver cards
// from 60-74 and gold above that? and bronze below 60? i think maybe the green
// color is worse than silver".
//
// He is right, and for a reason this codebase already had written down: GREEN
// IN THIS APP MEANS CORRECT AND GO. The mode grid was de-greened for exactly
// that reason — nine green icons meant the eye could not rank them — and a
// green TIER competes with green-as-correct in the same way. Bronze/silver/gold
// is also a ladder every football fan already reads, where "prospect / pro /
// elite" had to be learned.
//
// Against the measured population (2026-09-09): the median player rates ~64
// (silver), 75 needs ~68% on medium or ~63% on hard — roughly the top fifth.
export function cardTier(overall) {
  if (overall >= 75) return "gold";
  if (overall >= 60) return "silver";
  return "bronze";
}

// Tier palettes. Shared by the in-app card header and the share render
// (api/og.js imports these — keep this module the single source of truth).
export const CARD_TIERS = {
  gold:   { bg: "linear-gradient(160deg,#2a2410 0%,#0B0C10 100%)", accent: "#FFC107", text: "#FFF6E0", label: "GOLD" },
  silver: { bg: "linear-gradient(160deg,#1b212a 0%,#080a0f 100%)", accent: "#C7D2E0", text: "#EDF1F7", label: "SILVER" },
  bronze: { bg: "linear-gradient(160deg,#2a1a0e 0%,#0b0705 100%)", accent: "#D08A4E", text: "#F6E7D8", label: "BRONZE" },
};

// ⚠️ OLD SHARE LINKS MUST STILL RENDER. api/og.js takes the tier key from a URL
// parameter, and every /p?... card already sitting in somebody's chat history
// carries elite / pro / prospect. Renaming the keys without this would drop all
// of them to a default palette — a silent regression in the one artefact that
// outlives every deploy.
const LEGACY_TIER = { elite: "gold", pro: "silver", prospect: "bronze" };

/** Resolve a tier key — current or legacy — to a palette. Never returns undefined. */
export function tierPalette(key) {
  return CARD_TIERS[key] || CARD_TIERS[LEGACY_TIER[key]] || CARD_TIERS.silver;
}

/**
 * The full card model.
 * @param catStats  per-key records
 * @param _priorAcc accepted for older call sites; unused (the overall is derived here)
 * @param lifetime  {c, a} raw lifetime totals — tops up a legacy record, see overallScore
 */
export function computeCard(catStats = {}, _priorAcc, lifetime) {
  // Fold aliases into their face BEFORE reading, so a profile carrying both
  // `ChampionsLeague` and `UCL` (46 in prod) rates one Champions League.
  const folded = {};
  for (const [k, v] of Object.entries(catStats || {})) {
    const key = FACE_ALIAS[k] || k;
    const cur = folded[key] || { s: 0, n: 0, c: 0, a: 0 };
    const sk = scoreOf(v);
    folded[key] = { s: cur.s + sk.s, n: cur.n + sk.n, c: cur.c + (v?.c || 0), a: cur.a + (v?.a || 0) };
  }
  // Legacy = no raw key carries per-answer scores yet; only then does the
  // lifetime top-up apply (see overallScore).
  const { mean, answered: answeredTotal } = overallScore(folded, isScored(catStats) ? null : lifetime);
  const acc = mean / AVG_MULT;
  const overall = ratingFromScore(mean);
  const ratings = CARD_COMPS.map(comp => {
    const cs = folded[comp.cat];
    const answered = scoreOf(cs).n;
    return {
      abbr: comp.abbr, cat: comp.cat, name: comp.name, icon: comp.icon, color: comp.color,
      rating: compRating(cs, acc),
      answered,
      // Per-face honesty: a face prints FULLY only from its own data; from
      // PROVISIONAL_ANSWERS it prints muted (see the constant).
      rated: answered >= MIN_RATED_ANSWERS,
      provisional: answered >= PROVISIONAL_ANSWERS && answered < MIN_RATED_ANSWERS,
    };
  });
  // `rated` travels WITH the card so every consumer inherits one answer to
  // "is there enough data to print a number?". Four surfaces once asked it four
  // ways and three got it wrong (a friend card printed 85 · GOLD off one
  // answer; the OG unfurl published six invented ratings).
  return {
    ratings, overall, tier: cardTier(overall), answeredTotal,
    rated: answeredTotal >= MIN_RATED_ANSWERS,
    accuracy: acc,
    mean,
    calibration: { measured: CALIBRATION.measured, n: CALIBRATION.n },
  };
}
