// Transfer Trail — pure game logic (docs/transfer-trail-spec.md).
//
// Daily "put the career in order" puzzle: the day's mystery footballer has
// their clubs revealed but SCRAMBLED; the player arranges them into
// chronological order in ≤5 attempts. This module is the Footle-pattern
// sibling of wordle.js/footleNumber.js: frozen schedule, pure grader,
// localStorage streak walker. No React, no side effects — unit-tested in
// tests/unit/trail-grading.test.js.
//
// DATA: TRAIL_PLAYERS ships EMPTY on purpose. Career rows are forge-generated
// (generate → skeptic re-derivation from an independent source) and then
// 100% human spot-checked before ANY entry lands here — a wrong career order
// is unfalsifiable to the player and poisons the share loop (same trust class
// as a wrong answer key). Editorial rules are LOCKED in the spec: loans
// included + marked, youth excluded, return spells = separate rungs, max 6.
import { dateToYMD } from "./date.js";

export const TRAIL_MAX_ATTEMPTS = 5;

// ── Puzzle number ─────────────────────────────────────────────────────────────
// Same day-index math as footleNumber.js.
//
// ⚠️ PROVISIONAL AGAIN — the mode is DARK. It was briefly pointed at 2026-07-29
// and reverted the same hour: Alex, on seeing the screen, "transfer trail is not
// ready and not intended to look like that". Verified in prod before reverting
// that `scores` held ZERO rows for game_mode='trail', so no puzzle number had
// ever been played or shared and the anchor was still free to move. That is the
// ONLY condition under which it may move — once a single grid is out in the
// world, the number is load-bearing and shifting it renumbers everyone's.
//
// Set this to the real launch day in the SAME commit that declares the screen
// ready. Until then getTrailAnswerForDayIndex returns null for every date
// before it, so Home shows no Trail row and the route sends you home.
export const DAY_MS = 24 * 60 * 60 * 1000;
// ⚠️ LIVE. Was 20697 (2026-09-01) and commented "PROVISIONAL, mode is dark" —
// a placeholder from when the engine shipped inert awaiting a career
// spot-check. That check is now done: all 44 careers verified 2026-08-03,
// which found and fixed one real defect (Courtois listed Chelsea BEFORE the
// Atletico loan, a club he had not played a minute for) and confirmed the two
// recent moves against sources (Kante to Fenerbahce, Feb 2026; Pogba to
// Monaco, Jun 2025).
//
// The placeholder outlived its reason and left a finished daily game dark for
// days while memory recorded it as "LIVE". If you ever set this ahead again,
// verify getTrailAnswer() returns a player on the day you ship.
export const TRAIL_ANCHOR_DAY = 20668; // days since epoch — Trail #1

export function getTrailDayIndex(date = new Date()) {
  return Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / DAY_MS);
}

export function getTrailNumber(date = new Date()) {
  return getTrailDayIndex(date) - TRAIL_ANCHOR_DAY + 1;
}

// ── Dataset (filled by the verified forge waves — see header) ─────────────────
// Row shape:
//   { key:"YOUNG_A", display:["Ashley","Young"], nat:"England",
//     clubs:["Watford","Aston Villa","Man Utd","Inter","Aston Villa","Everton"],
//     loans:[false,false,false,false,false,false],   // parallel to clubs
//     years:["2003–07", ...] }                        // assist-only, optional
export const TRAIL_PLAYERS = [
  // ── WAVE N (2026-08-12): 58 careers from Wikipedia infoboxes, the
  // only source that marks loans. Generated by scripts/build-trail-candidates.mjs,
  // read one by one before merging. Club names normalised to house style.
  { key: "MESSI", display: ["Lionel","Messi"], nat: "Spain",
    clubs: ["Barcelona","PSG","Inter Miami"],
    loans: [false,false,false] },
  { key: "MBAPP", display: ["Kylian","Mbappé"], nat: "France",
    clubs: ["Monaco","PSG","Real Madrid"],
    loans: [false,false,false] },
  { key: "MODRI", display: ["Luka","Modrić"], nat: "Croatia",
    clubs: ["Dinamo Zagreb","Zrinjski Mostar","Inter Zaprešić","Tottenham","Real Madrid","AC Milan"],
    loans: [false,true,true,false,false,false] },
  { key: "BENZEMA", display: ["Karim","Benzema"], nat: "France",
    clubs: ["Lyon","Real Madrid","Al-Ittihad","Al-Hilal"],
    loans: [false,false,false,false] },
  { key: "KANE", display: ["Harry","Kane"], nat: "United Kingdom",
    clubs: ["Tottenham","Leyton Orient","Millwall","Norwich City","Leicester City","Bayern Munich"],
    loans: [false,true,true,true,true,false] },
  { key: "DEMBL", display: ["Ousmane","Dembélé"], nat: "France",
    clubs: ["Rennes","Borussia Dortmund","Barcelona","PSG"],
    loans: [false,false,false,false] },
  { key: "LLORIS", display: ["Hugo","Lloris"], nat: "France",
    clubs: ["Nice","Lyon","Tottenham","LAFC"],
    loans: [false,false,false,false] },
  { key: "GEA", display: ["David de","Gea"], nat: "Spain",
    clubs: ["Atletico Madrid","Man Utd","Fiorentina"],
    loans: [false,false,false] },
  { key: "DYBALA", display: ["Paulo","Dybala"], nat: "Italy",
    clubs: ["Instituto","Palermo","Juventus","Roma"],
    loans: [false,false,false,false] },
  { key: "REUS", display: ["Marco","Reus"], nat: "Germany",
    clubs: ["Rot Weiss Ahlen","Borussia M.gladbach","Borussia Dortmund","LA Galaxy"],
    loans: [false,false,false,false] },
  { key: "HEUNGMIN", display: ["Son","Heung-min"], nat: "South Korea",
    clubs: ["Hamburger SV","Leverkusen","Tottenham","LAFC"],
    loans: [false,false,false,false] },
  { key: "BELLINGHAM", display: ["Jude","Bellingham"], nat: "United Kingdom",
    clubs: ["Birmingham City","Borussia Dortmund","Real Madrid"],
    loans: [false,false,false] },
  { key: "BECKER", display: ["Alisson","Becker"], nat: "Brazil",
    clubs: ["Internacional","Roma","Liverpool"],
    loans: [false,false,false] },
  { key: "HAKIMI", display: ["Achraf","Hakimi"], nat: "Spain",
    clubs: ["Real Madrid","Borussia Dortmund","Inter Milan","PSG"],
    loans: [false,true,false,false] },
  { key: "FIRMINO", display: ["Roberto","Firmino"], nat: "Brazil",
    clubs: ["Figueirense","Hoffenheim","Liverpool","Al-Ahli","Al Sadd"],
    loans: [false,false,false,false,false] },
  { key: "SZCZSNY", display: ["Wojciech","Szczęsny"], nat: "Poland",
    clubs: ["Arsenal","Brentford","Roma","Juventus","Barcelona"],
    loans: [false,true,true,false,false] },
  { key: "MAGUIRE", display: ["Harry","Maguire"], nat: "United Kingdom",
    clubs: ["Sheffield Utd","Hull City","Wigan Athletic","Leicester City","Man Utd"],
    loans: [false,false,true,false,false] },
  { key: "STEGEN", display: ["Marc-André ter","Stegen"], nat: "Germany",
    clubs: ["Borussia M.gladbach","Barcelona","Girona","Ajax"],
    loans: [false,false,true,true] },
  { key: "ERIKSEN", display: ["Christian","Eriksen"], nat: "Kingdom of Denmark",
    clubs: ["Ajax","Tottenham","Inter Milan","Brentford","Man Utd","VfL Wolfsburg"],
    loans: [false,false,false,false,false,false] },
  { key: "DEPAY", display: ["Memphis","Depay"], nat: "Ghana",
    clubs: ["PSV Eindhoven","Man Utd","Lyon","Barcelona","Atletico Madrid","Corinthians"],
    loans: [false,false,false,false,false,false] },
  { key: "NAGATOMO", display: ["Yūto","Nagatomo"], nat: "Japan",
    clubs: ["FC Tokyo","Cesena","Inter Milan","Galatasaray","Marseille","FC Tokyo"],
    loans: [false,true,false,false,false,false] },
  { key: "FERNANDES", display: ["Bruno","Fernandes"], nat: "Portugal",
    clubs: ["Novara","Udinese","Sampdoria","Sporting CP","Man Utd"],
    loans: [false,false,false,false,false] },
  { key: "DRAXLER", display: ["Julian","Draxler"], nat: "Germany",
    clubs: ["Schalke 04","VfL Wolfsburg","PSG","Benfica","Al Ahli"],
    loans: [false,false,false,true,false] },
  { key: "MINAMINO", display: ["Takumi","Minamino"], nat: "Japan",
    clubs: ["Cerezo Osaka","RB Salzburg","Liverpool","Southampton","Monaco"],
    loans: [false,false,false,true,false] },
  { key: "RDIGER", display: ["Antonio","Rüdiger"], nat: "Germany",
    clubs: ["VfB Stuttgart","Roma","Chelsea","Real Madrid"],
    loans: [false,false,false,false] },
  { key: "VALVERDE", display: ["Federico","Valverde"], nat: "Uruguay",
    clubs: ["Peñarol","Real Madrid","Deportivo"],
    loans: [false,false,true] },
  { key: "GNDOAN", display: ["İlkay","Gündoğan"], nat: "Germany",
    clubs: ["1. FC Nürnberg","Borussia Dortmund","Man City","Barcelona","Man City","Galatasaray"],
    loans: [false,false,false,false,false,false] },
  { key: "HAVERTZ", display: ["Kai","Havertz"], nat: "Germany",
    clubs: ["Leverkusen","Chelsea","Arsenal"],
    loans: [false,false,false] },
  { key: "TORRES_FER", display: ["Ferran","Torres"], nat: "Spain",
    // + PSG 2026-08-15 (€50m from Barcelona, verified: both clubs' official
    // announcements + BBC/AFP). All four of his TRAIL_ANSWER_LOG days are
    // future (first: log index 32), so this is a content fix, not a
    // schedule change.
    clubs: ["Valencia","Man City","Barcelona","PSG"],
    loans: [false,false,false,false] },
  { key: "OSAKO", display: ["Yuya","Osako"], nat: "Japan",
    clubs: ["Kashima Antlers","1860 Munich","1. FC Köln","Werder Bremen","Vissel Kobe"],
    loans: [false,false,false,false,false] },
  { key: "FATI", display: ["Ansu","Fati"], nat: "Spain",
    clubs: ["Barcelona","Brighton","Monaco"],
    loans: [false,true,false] },
  { key: "DONNARUMMA", display: ["Gianluigi","Donnarumma"], nat: "Italy",
    clubs: ["AC Milan","PSG","Man City"],
    loans: [false,false,false] },
  { key: "KOVAI", display: ["Mateo","Kovačić"], nat: "Croatia",
    clubs: ["Dinamo Zagreb","Inter Milan","Real Madrid","Chelsea","Man City"],
    loans: [false,false,false,false,false] },
  { key: "YOSHIDA", display: ["Maya","Yoshida"], nat: "Japan",
    clubs: ["Nagoya Grampus","VVV-Venlo","Southampton","Sampdoria","Schalke 04","LA Galaxy"],
    loans: [false,false,false,false,false,false] },
  { key: "UCHIDA", display: ["Atsuto","Uchida"], nat: "Japan",
    clubs: ["Kashima Antlers","Schalke 04","Union Berlin","Kashima Antlers"],
    loans: [false,false,false,false] },
  { key: "SILVA", display: ["Bernardo","Silva"], nat: "Portugal",
    clubs: ["Benfica","Monaco","Man City","Real Madrid"],
    loans: [false,false,false,false] },
  { key: "SAN", display: ["Leroy","Sané"], nat: "Germany",
    clubs: ["Schalke 04","Man City","Bayern Munich","Galatasaray"],
    loans: [false,false,false,false] },
  { key: "WERNER", display: ["Timo","Werner"], nat: "Germany",
    clubs: ["VfB Stuttgart","RB Leipzig","Chelsea","RB Leipzig","Tottenham","San Jose Earthquakes"],
    loans: [false,false,false,false,true,false] },
  { key: "PAVARD", display: ["Benjamin","Pavard"], nat: "France",
    clubs: ["Lille","VfB Stuttgart","Bayern Munich","Inter Milan","Marseille"],
    loans: [false,false,false,false,true] },
  { key: "SHIBASAKI", display: ["Gaku","Shibasaki"], nat: "Japan",
    clubs: ["Kashima Antlers","Tenerife","Getafe","Deportivo","Leganés","Kashima Antlers"],
    loans: [false,false,false,false,false,false] },
  { key: "SAKAI", display: ["Gōtoku","Sakai"], nat: "Japan",
    clubs: ["Albirex Niigata","VfB Stuttgart","Hamburger SV","Vissel Kobe"],
    loans: [false,false,false,false] },
  { key: "ALVAREZ", display: ["Julián","Alvarez"], nat: "Argentina",
    clubs: ["River Plate","Man City","River Plate","Atletico Madrid"],
    loans: [false,false,true,false] },
  { key: "VZQUEZ", display: ["Lucas","Vázquez"], nat: "Spain",
    clubs: ["Espanyol","Real Madrid","Leverkusen"],
    loans: [true,false,false] },
  { key: "MUTO", display: ["Yoshinori","Muto"], nat: "Japan",
    clubs: ["FC Tokyo","Mainz 05","Newcastle United","Eibar","Vissel Kobe"],
    loans: [false,false,false,true,false] },
  { key: "GAKPO", display: ["Cody","Gakpo"], nat: "Kingdom of the Netherlands",
    clubs: ["Jong PSV","PSV","Liverpool"],
    loans: [false,false,false] },
  { key: "CAN", display: ["Emre","Can"], nat: "Turkey",
    clubs: ["Bayern Munich","Leverkusen","Liverpool","Juventus","Borussia Dortmund"],
    loans: [false,false,false,false,false] },
  { key: "XHAKA", display: ["Granit","Xhaka"], nat: "Switzerland",
    clubs: ["Basel","Borussia M.gladbach","Arsenal","Leverkusen","Sunderland"],
    loans: [false,false,false,false,false] },
  { key: "SAKAI_HIR", display: ["Hiroki","Sakai"], nat: "Japan",
    clubs: ["Kashiwa Reysol","Hannover 96","Marseille","Urawa Red Diamonds","Auckland"],
    loans: [false,false,false,false,false] },
  { key: "RABIOT", display: ["Adrien","Rabiot"], nat: "France",
    clubs: ["PSG","Toulouse","Juventus","Marseille","AC Milan"],
    loans: [false,true,false,false,false] },
  { key: "JONG", display: ["Frenkie de","Jong"], nat: "Kingdom of the Netherlands",
    clubs: ["Jong Ajax","Ajax","Barcelona"],
    loans: [false,false,false] },
  { key: "AFELLAY", display: ["Ibrahim","Afellay"], nat: "Kingdom of the Netherlands",
    // ⚠️ WAS CORRUPT UNTIL 2026-08-12, and would have rendered as a rung reading
    // "PSV Eindhoven |caps1 = 159 |goals1 = 35" on Trail #29. His infobox puts
    // clubs, caps and goals on ONE line — the only article in 102 that does —
    // so the generator's end-of-line capture swallowed two extra fields into
    // every club name. Nothing in the build could see it: the tests check
    // schedule shape, not that a club name is a club name. Found by
    // scripts/verify-trail-careers.mjs on its first real run, 19 days before
    // the puzzle was due. The parser now cuts trailing infobox fields.
    clubs: ["PSV","Barcelona","Schalke 04","Olympiacos","Stoke City","PSV"],
    loans: [false,false,true,true,false,false] },
  { key: "STONES", display: ["John","Stones"], nat: "United Kingdom",
    clubs: ["Barnsley","Everton","Man City","Inter Milan"],
    loans: [false,false,false,false] },
  { key: "VERRATTI", display: ["Marco","Verratti"], nat: "Spain",
    clubs: ["Pescara","PSG","Al-Arabi","Al Duhail"],
    loans: [false,false,false,false] },
  { key: "OLISE", display: ["Michael","Olise"], nat: "France",
    clubs: ["Reading","Crystal Palace","Bayern Munich"],
    loans: [false,false,false] },
  { key: "OSIMHEN", display: ["Victor","Osimhen"], nat: "Nigeria",
    clubs: ["VfL Wolfsburg","Charleroi","Lille","Napoli","Galatasaray"],
    loans: [false,false,false,false,false] },
  { key: "KONNO", display: ["Yasuyuki","Konno"], nat: "Japan",
    clubs: ["Consadole Sapporo","FC Tokyo","Gamba Osaka","Júbilo Iwata","Nankatsu SC"],
    loans: [false,false,false,false,false] },
  { key: "ISAK", display: ["Alexander","Isak"], nat: "Sweden",
    clubs: ["AIK","Borussia Dortmund","Real Sociedad","Newcastle United","Liverpool"],
    loans: [false,false,false,false,false] },
  { key: "MARTIAL", display: ["Anthony","Martial"], nat: "France",
    clubs: ["Lyon","Monaco","Man Utd","Sevilla","AEK Athens","Monterrey"],
    loans: [false,false,false,true,false,false] },
  // Wave 1 — forge-generated (generate → independent web re-derivation vs
  // Wikipedia/Transfermarkt, all verified:true high-confidence) + Alex spot-
  // checked 2026-07-21. `display` corrected from the forge (a schema-wording
  // slip had some agents emit clubs there). 4 others from the batch were
  // rejected: Young(7)/Villa(8)/Pirlo(8) exceed the 6-rung max (not truncated,
  // per the locked rules); Modrić dropped editorially (obscure loan openers).
  { key: "TORRES", display: ["Fernando", "Torres"], nat: "Spain",
    clubs: ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan", "Atletico Madrid", "Sagan Tosu"],
    loans: [false, false, false, true, false, false] },
  { key: "BALE", display: ["Gareth", "Bale"], nat: "Wales",
    clubs: ["Southampton", "Tottenham", "Real Madrid", "Tottenham", "Real Madrid", "LAFC"],
    loans: [false, false, false, true, false, false] },
  { key: "VAN_PERSIE", display: ["Robin", "van Persie"], nat: "Netherlands",
    clubs: ["Feyenoord", "Arsenal", "Man Utd", "Fenerbahce", "Feyenoord"],
    loans: [false, false, false, false, false] },
  { key: "ALONSO", display: ["Xabi", "Alonso"], nat: "Spain",
    clubs: ["Real Sociedad", "Eibar", "Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"],
    loans: [false, true, false, false, false, false] },
  { key: "HENRY", display: ["Thierry", "Henry"], nat: "France",
    clubs: ["Monaco", "Juventus", "Arsenal", "Barcelona", "New York Red Bulls", "Arsenal"],
    loans: [false, false, false, false, false, true] },
  { key: "SNEIJDER", display: ["Wesley", "Sneijder"], nat: "Netherlands",
    clubs: ["Ajax", "Real Madrid", "Inter", "Galatasaray", "Nice", "Al-Gharafa"],
    loans: [false, false, false, false, false, false] },
  { key: "OZIL", display: ["Mesut", "Özil"], nat: "Germany",
    clubs: ["Schalke 04", "Werder Bremen", "Real Madrid", "Arsenal", "Fenerbahce", "Basaksehir"],
    loans: [false, false, false, false, false, false] },
  { key: "OWEN", display: ["Michael", "Owen"], nat: "England",
    clubs: ["Liverpool", "Real Madrid", "Newcastle", "Man Utd", "Stoke City"],
    loans: [false, false, false, false, false] },

  // ── Wave 2, forged 2026-07-29 ────────────────────────────────────
  // ⚠️ NOT yet spot-checked by Alex. Spec §7.3 requires a 100% manual pass
  // before TRAIL_ANSWER_LOG is frozen — a wrong career order is unfalsifiable
  // to the player and poisons the share loop. These are INERT until then:
  // the log is still empty, so no puzzle draws from them.
  { key: "RONALDO_C", display: ["Cristiano","Ronaldo"], nat: "Portugal",
    clubs: ["Sporting CP","Man Utd","Real Madrid","Juventus","Man Utd","Al-Nassr"],
    loans: [false, false, false, false, false, false] },
  { key: "ROONEY", display: ["Wayne","Rooney"], nat: "England",
    clubs: ["Everton","Man Utd","Everton","DC United","Derby County"],
    loans: [false, false, false, false, false] },
  { key: "ROBBEN", display: ["Arjen","Robben"], nat: "Netherlands",
    clubs: ["Groningen","PSV","Chelsea","Real Madrid","Bayern Munich","Groningen"],
    loans: [false, false, false, false, false, false] },
  { key: "SEEDORF", display: ["Clarence","Seedorf"], nat: "Netherlands",
    clubs: ["Ajax","Sampdoria","Real Madrid","Inter","AC Milan","Botafogo"],
    loans: [false, false, false, false, false, false] },
  { key: "VIEIRA", display: ["Patrick","Vieira"], nat: "France",
    clubs: ["Cannes","AC Milan","Arsenal","Juventus","Inter","Man City"],
    loans: [false, false, false, false, false, false] },
  { key: "MAKELELE", display: ["Claude","Makélélé"], nat: "France",
    clubs: ["Nantes","Marseille","Celta Vigo","Real Madrid","Chelsea","PSG"],
    loans: [false, false, false, false, false, false] },
  { key: "BALLACK", display: ["Michael","Ballack"], nat: "Germany",
    clubs: ["Chemnitzer FC","Kaiserslautern","Bayer Leverkusen","Bayern Munich","Chelsea","Bayer Leverkusen"],
    loans: [false, false, false, false, false, false] },
  { key: "MANE", display: ["Sadio","Mané"], nat: "Senegal",
    clubs: ["Metz","Red Bull Salzburg","Southampton","Liverpool","Bayern Munich","Al-Nassr"],
    loans: [false, false, false, false, false, false] },
  { key: "POGBA", display: ["Paul","Pogba"], nat: "France",
    clubs: ["Man Utd","Juventus","Man Utd","Juventus","Monaco"],
    loans: [false, false, false, false, false] },
  { key: "FABREGAS", display: ["Cesc","Fàbregas"], nat: "Spain",
    clubs: ["Arsenal","Barcelona","Chelsea","Monaco","Como"],
    loans: [false, false, false, false, false] },
  { key: "COLE_A", display: ["Ashley","Cole"], nat: "England",
    clubs: ["Arsenal","Crystal Palace","Chelsea","Roma","LA Galaxy","Derby County"],
    loans: [false, true, false, false, false, false] },
  { key: "BUFFON", display: ["Gianluigi","Buffon"], nat: "Italy",
    clubs: ["Parma","Juventus","PSG","Juventus","Parma"],
    loans: [false, false, false, false, false] },
  { key: "RAMOS", display: ["Sergio","Ramos"], nat: "Spain",
    clubs: ["Sevilla","Real Madrid","PSG","Sevilla","Monterrey"],
    loans: [false, false, false, false, false] },
  { key: "CECH", display: ["Petr","Čech"], nat: "Czech Republic",
    clubs: ["Chmel Blsany","Sparta Prague","Rennes","Chelsea","Arsenal"],
    loans: [false, false, false, false, false] },
  { key: "DUFF", display: ["Damien","Duff"], nat: "Ireland",
    clubs: ["Blackburn","Chelsea","Newcastle","Fulham","Melbourne City","Shamrock Rovers"],
    loans: [false, false, false, false, false, false] },
  { key: "GOTZE", display: ["Mario","Götze"], nat: "Germany",
    clubs: ["Dortmund","Bayern Munich","Dortmund","PSV","Eintracht Frankfurt"],
    loans: [false, false, false, false, false] },
  { key: "KOMPANY", display: ["Vincent","Kompany"], nat: "Belgium",
    clubs: ["Anderlecht","Hamburg","Man City","Anderlecht"],
    loans: [false, false, false, false] },
  { key: "FIGO", display: ["Luis","Figo"], nat: "Portugal",
    clubs: ["Sporting CP","Barcelona","Real Madrid","Inter"],
    loans: [false, false, false, false] },
  { key: "KROOS", display: ["Toni","Kroos"], nat: "Germany",
    clubs: ["Bayern Munich","Bayer Leverkusen","Real Madrid"],
    loans: [false, true, false] },
  { key: "NEYMAR", display: ["Neymar","Júnior"], nat: "Brazil",
    clubs: ["Santos","Barcelona","PSG","Al-Hilal","Santos"],
    loans: [false, false, false, false, false] },
  { key: "AGUERO", display: ["Sergio","Agüero"], nat: "Argentina",
    clubs: ["Independiente","Atletico Madrid","Man City","Barcelona"],
    loans: [false, false, false, false] },
  { key: "ISCO", display: ["Isco","Alarcón"], nat: "Spain",
    clubs: ["Valencia","Malaga","Real Madrid","Sevilla","Real Betis"],
    loans: [false, false, false, false, false] },
  { key: "VERTONGHEN", display: ["Jan","Vertonghen"], nat: "Belgium",
    clubs: ["Ajax","RKC Waalwijk","Tottenham","Benfica","Anderlecht"],
    loans: [false, true, false, false, false] },
  { key: "KANTE", display: ["N'Golo","Kanté"], nat: "France",
    clubs: ["Boulogne","Caen","Leicester","Chelsea","Al-Ittihad","Fenerbahce"],
    loans: [false, false, false, false, false, false] },
  { key: "ALDERWEIRELD", display: ["Toby","Alderweireld"], nat: "Belgium",
    clubs: ["Ajax","Atletico Madrid","Southampton","Tottenham","Al-Duhail","Antwerp"],
    loans: [false, false, true, false, false, false] },
  { key: "JOAQUIN", display: ["Joaquín","Sánchez"], nat: "Spain",
    clubs: ["Real Betis","Valencia","Malaga","Fiorentina","Real Betis"],
    loans: [false, false, false, false, false] },
  { key: "KLOSE", display: ["Miroslav","Klose"], nat: "Germany",
    clubs: ["Homburg","Kaiserslautern","Werder Bremen","Bayern Munich","Lazio"],
    loans: [false, false, false, false, false] },
  { key: "MATUIDI", display: ["Blaise","Matuidi"], nat: "France",
    clubs: ["Troyes","Saint-Etienne","PSG","Juventus","Inter Miami"],
    loans: [false, false, false, false, false] },
  { key: "FLAMINI", display: ["Mathieu","Flamini"], nat: "France",
    clubs: ["Marseille","Arsenal","AC Milan","Arsenal","Crystal Palace","Getafe"],
    loans: [false, false, false, false, false, false] },
  { key: "GILBERTO_SILVA", display: ["Gilberto","Silva"], nat: "Brazil",
    clubs: ["America Mineiro","Atletico Mineiro","Arsenal","Panathinaikos","Gremio","Atletico Mineiro"],
    loans: [false, false, false, false, false, false] },

  // ── Wave M, forged 2026-07-30 ────────────────────────────────────
  // ⚠️ INERT. Added to the roster but NOT written into TRAIL_ANSWER_LOG, so no
  // puzzle draws from them. Per the spec header, a career row needs a 100%
  // human spot-check before it can be scheduled — a wrong order is
  // unfalsifiable to the player. Alex: check these seven, then I extend the log.
  //
  // WHY MORE CAREERS AT ALL, given the log already covers 380 days: 38 players
  // over 380 days means every answer recurs roughly ONCE A MONTH. For a daily
  // game that is very noticeable. Recurrence, not runway, is the problem.
  //
  // Each row was web-verified before landing. FIVE candidates were generated
  // and then REJECTED rather than shipped on a maybe:
  //   Hummels, Di María — recent moves I could not confirm (Roma / a Rosario
  //     Central return would change the final rung).
  //   Mahrez — Al-Ahli terminated his contract, so the last rung is unstable.
  //   Ibrahimović, Drogba — genuine careers, but 9-10 senior clubs. The 6-rung
  //     max is a locked editorial rule and truncating a career is not allowed.
  { key: "VAN_DIJK", display: ["Virgil","van Dijk"], nat: "Netherlands",
    clubs: ["Groningen","Celtic","Southampton","Liverpool"],
    loans: [false, false, false, false] },
  { key: "COURTOIS", display: ["Thibaut","Courtois"], nat: "Belgium",
    // ⚠️ CORRECTED 2026-08-03. This used to open Genk -> Chelsea -> Atletico,
    // on the reasoning that he signed for Chelsea in 2011 and was loaned out
    // immediately, so "the return spell is its own rung". That gets the game
    // backwards: he never played a single senior match for Chelsea before
    // 2014, so the first Chelsea rung showed a club he had never turned out
    // for. In a puzzle where the clubs ARE the clue, that is a false clue.
    //
    // The rungs are now the clubs he actually played for, in order. Note this
    // also settles the rule ambiguity that De Bruyne exposed: coming back from
    // a loan is NOT a "return" under the returns-are-rungs rule, because the
    // parent contract never ended. Both players had one continuous Chelsea
    // deal with a loan inside it; both now list Chelsea once. De Bruyne
    // needed no change, and does not need a 7th rung.
    clubs: ["Genk","Atletico Madrid","Chelsea","Real Madrid"],
    loans: [false, true, false, false] },
  { key: "GRIEZMANN", display: ["Antoine","Griezmann"], nat: "France",
    // ⚠️ Orlando City added 2026-08-12 by scripts/verify-trail-careers.mjs, which
    // caught the move FOUR DAYS before Trail #14 would have shipped the old
    // four-club path as today's puzzle. Confirmed against Wikidata P54 (start
    // 2026) as well as the infobox — one source is not enough for a claim about
    // a living player, and Wikipedia vandalism has reached our binaries before.
    clubs: ["Real Sociedad","Atletico Madrid","Barcelona","Atletico Madrid","Orlando City"],
    loans: [false, false, false, false, false] },
  { key: "DE_BRUYNE", display: ["Kevin","De Bruyne"], nat: "Belgium",
    clubs: ["Genk","Chelsea","Werder Bremen","Wolfsburg","Man City","Napoli"],
    loans: [false, false, true, false, false, false] },
  { key: "SON", display: ["Heung-min","Son"], nat: "South Korea",
    clubs: ["Hamburg","Bayer Leverkusen","Tottenham","LAFC"],
    loans: [false, false, false, false] },
  // MARCELO was forged and then REJECTED here: a mononym cannot satisfy the
  // 2-part `display` contract, and his legal surname (Vieira) already belongs
  // to Patrick Vieira in this roster — two puzzles would share an answer.
  { key: "LEWANDOWSKI", display: ["Robert","Lewandowski"], nat: "Poland",
    // Znicz Pruszkow opens the real career but is third-tier Polish football —
    // dropped for the same editorial reason Modric's loan openers were.
    // ⚠️ Chicago Fire added 2026-08-12 by scripts/verify-trail-careers.mjs,
    // confirmed against Wikidata P54 (start 2026) as well as the infobox. With
    // the two trimmed Polish clubs the full career is seven rungs, over the
    // six-rung cap — this stays at five because the trim is a deliberate
    // editorial subset made in wave M, not a truncation of the recent end.
    clubs: ["Lech Poznan","Dortmund","Bayern Munich","Barcelona","Chicago Fire"],
    loans: [false, false, false, false, false] },
];

// Frozen answer log: TRAIL_ANSWER_LOG[n] is the player `key` for day index
// TRAIL_ANCHOR_DAY + n. Generated once at ship time (clone of
// WORDLE_ANSWER_LOG) so the schedule never reshuffles under players.
export const TRAIL_ANSWER_LOG = [
  // RE-PLANNED 2026-08-12 for wave N (44 -> 102 careers).
  // ⚠️ Entries 1..10 are copied through UNCHANGED — those puzzles have been
  // played and their grids shared. Everything after is re-planned, which is
  // safe precisely because nobody has seen it. Deterministic LCG, seed 20260812.
  // Minimum gap between repeats: 16 days.
  "TORRES",
  "GILBERTO_SILVA",
  "RONALDO_C",
  "RAMOS",
  "MATUIDI",
  "ROONEY",
  "CECH",
  "HENRY",
  "SNEIJDER",
  "FLAMINI",   // ← puzzles above are PLAYED; never touch them
  "ERIKSEN",
  "VALVERDE",
  "CAN",
  "GRIEZMANN",
  "FERNANDES",
  "AGUERO",
  "VAN_PERSIE",
  "KOVAI",
  "KLOSE",
  "ALONSO",
  "SON",
  "BALLACK",
  "MINAMINO",
  "WERNER",
  "BENZEMA",
  "SAKAI",
  "MAKELELE",
  "KONNO",
  "AFELLAY",
  "UCHIDA",
  "RDIGER",
  "VERRATTI",
  "TORRES_FER",
  "XHAKA",
  "JONG",
  "POGBA",
  "MANE",
  "OZIL",
  "ROBBEN",
  "MESSI",
  "ALVAREZ",
  "SHIBASAKI",
  "LEWANDOWSKI",
  "DUFF",
  "BECKER",
  "LLORIS",
  "GOTZE",
  "OSAKO",
  "OLISE",
  "GAKPO",
  "PAVARD",
  "FIGO",
  "COLE_A",
  "DEPAY",
  "BUFFON",
  "HAVERTZ",
  "NEYMAR",
  "MAGUIRE",
  "FIRMINO",
  "VERTONGHEN",
  "VZQUEZ",
  "MODRI",
  "KOMPANY",
  "DE_BRUYNE",
  "SZCZSNY",
  "FABREGAS",
  "REUS",
  "MUTO",
  "VAN_DIJK",
  "OWEN",
  "STEGEN",
  "ALDERWEIRELD",
  "VIEIRA",
  "GEA",
  "OSIMHEN",
  "SAKAI_HIR",
  "FATI",
  "MARTIAL",
  "BELLINGHAM",
  "STONES",
  "ISCO",
  "HAKIMI",
  "SEEDORF",
  "KANE",
  "HEUNGMIN",
  "SAN",
  "DONNARUMMA",
  "DYBALA",
  "MBAPP",
  "JOAQUIN",
  "RABIOT",
  "YOSHIDA",
  "NAGATOMO",
  "DRAXLER",
  "ISAK",
  "KANTE",
  "BALE",
  "KROOS",
  "SILVA",
  "DEMBL",
  "GNDOAN",
  "COURTOIS",
  "STEGEN",
  "KOMPANY",
  "CAN",
  "MAKELELE",
  "SZCZSNY",
  "HENRY",
  "VAN_DIJK",
  "BUFFON",
  "DUFF",
  "SHIBASAKI",
  "FIGO",
  "MINAMINO",
  "HAKIMI",
  "BALLACK",
  "JONG",
  "YOSHIDA",
  "SAKAI",
  "ROBBEN",
  "OLISE",
  "KOVAI",
  "SEEDORF",
  "GNDOAN",
  "LEWANDOWSKI",
  "GAKPO",
  "MANE",
  "GRIEZMANN",
  "DEMBL",
  "ISCO",
  "SAKAI_HIR",
  "VALVERDE",
  "KONNO",
  "AGUERO",
  "MODRI",
  "VZQUEZ",
  "GEA",
  "MESSI",
  "FABREGAS",
  "KANTE",
  "BECKER",
  "ALDERWEIRELD",
  "KLOSE",
  "FLAMINI",
  "BALE",
  "SON",
  "RDIGER",
  "BENZEMA",
  "AFELLAY",
  "OZIL",
  "BELLINGHAM",
  "COURTOIS",
  "TORRES_FER",
  "LLORIS",
  "XHAKA",
  "KROOS",
  "CECH",
  "VERRATTI",
  "REUS",
  "FATI",
  "HEUNGMIN",
  "OWEN",
  "STONES",
  "GOTZE",
  "SAN",
  "RABIOT",
  "DEPAY",
  "VERTONGHEN",
  "SILVA",
  "TORRES",
  "MARTIAL",
  "MUTO",
  "ERIKSEN",
  "POGBA",
  "DONNARUMMA",
  "ALONSO",
  "MATUIDI",
  "JOAQUIN",
  "DYBALA",
  "HAVERTZ",
  "RONALDO_C",
  "UCHIDA",
  "SNEIJDER",
  "MBAPP",
  "PAVARD",
  "NEYMAR",
  "FERNANDES",
  "OSAKO",
  "OSIMHEN",
  "COLE_A",
  "DRAXLER",
  "GILBERTO_SILVA",
  "VIEIRA",
  "NAGATOMO",
  "KANE",
  "DE_BRUYNE",
  "WERNER",
  "FIRMINO",
  "ISAK",
  "RAMOS",
  "MAGUIRE",
  "VAN_PERSIE",
  "ROONEY",
  "ALVAREZ",
  "KOVAI",
  "SILVA",
  "AGUERO",
  "MINAMINO",
  "FABREGAS",
  "REUS",
  "ISCO",
  "SZCZSNY",
  "POGBA",
  "OSAKO",
  "GRIEZMANN",
  "FIGO",
  "DEMBL",
  "GEA",
  "OZIL",
  "SHIBASAKI",
  "YOSHIDA",
  "ALVAREZ",
  "HAVERTZ",
  "LLORIS",
  "CECH",
  "XHAKA",
  "FLAMINI",
  "MBAPP",
  "ALONSO",
  "ISAK",
  "VALVERDE",
  "KOMPANY",
  "SAKAI_HIR",
  "RABIOT",
  "GNDOAN",
  "COLE_A",
  "JONG",
  "ALDERWEIRELD",
  "KROOS",
  "DE_BRUYNE",
  "GOTZE",
  "OSIMHEN",
  "HENRY",
  "BUFFON",
  "VERRATTI",
  "STEGEN",
  "FIRMINO",
  "VZQUEZ",
  "MAGUIRE",
  "JOAQUIN",
  "KLOSE",
  "FATI",
  "RONALDO_C",
  "MUTO",
  "ROBBEN",
  "SAKAI",
  "UCHIDA",
  "RAMOS",
  "BECKER",
  "TORRES",
  "ROONEY",
  "DEPAY",
  "TORRES_FER",
  "BALLACK",
  "VAN_PERSIE",
  "VIEIRA",
  "OLISE",
  "MATUIDI",
  "GAKPO",
  "COURTOIS",
  "DUFF",
  "STONES",
  "NEYMAR",
  "HAKIMI",
  "MESSI",
  "VAN_DIJK",
  "RDIGER",
  "NAGATOMO",
  "VERTONGHEN",
  "SEEDORF",
  "FERNANDES",
  "KONNO",
  "DYBALA",
  "GILBERTO_SILVA",
  "HEUNGMIN",
  "AFELLAY",
  "DONNARUMMA",
  "MODRI",
  "CAN",
  "OWEN",
  "BELLINGHAM",
  "BENZEMA",
  "MANE",
  "MAKELELE",
  "LEWANDOWSKI",
  "KANTE",
  "BALE",
  "DRAXLER",
  "WERNER",
  "PAVARD",
  "KANE",
  "MARTIAL",
  "SAN",
  "SON",
  "SNEIJDER",
  "ERIKSEN",
  "GNDOAN",
  "VAN_DIJK",
  "SZCZSNY",
  "DUFF",
  "NEYMAR",
  "ISCO",
  "TORRES",
  "BENZEMA",
  "MAKELELE",
  "MODRI",
  "FIRMINO",
  "GAKPO",
  "KONNO",
  "ALDERWEIRELD",
  "SNEIJDER",
  "POGBA",
  "OSIMHEN",
  "HENRY",
  "DE_BRUYNE",
  "BALE",
  "OWEN",
  "DRAXLER",
  "MBAPP",
  "SEEDORF",
  "GRIEZMANN",
  "MANE",
  "AFELLAY",
  "TORRES_FER",
  "MINAMINO",
  "YOSHIDA",
  "VAN_PERSIE",
  "OZIL",
  "HEUNGMIN",
  "CAN",
  "KANTE",
  "ISAK",
  "BECKER",
  "RDIGER",
  "HAKIMI",
  "SHIBASAKI",
  "VERRATTI",
  "SAKAI_HIR",
  "COURTOIS",
  "MAGUIRE",
  "VZQUEZ",
  "KROOS",
  "MATUIDI",
  "REUS",
  "LEWANDOWSKI",
  "SAN",
  "ALVAREZ",
  "DONNARUMMA",
  "MUTO",
  "STEGEN",
  "FATI",
  "GEA",
  "KOMPANY",
  "JOAQUIN",
  "UCHIDA",
  "RONALDO_C",
  "OSAKO",
  "NAGATOMO",
  "DEMBL",
  "BELLINGHAM",
  "PAVARD",
  "SAKAI",
  "WERNER",
  "COLE_A",
  "SON",
  "FIGO",
  "BALLACK",
  "JONG",
  "MARTIAL",
  "MESSI",
  "ROONEY",
  "ROBBEN",
  "VERTONGHEN",
  "ALONSO",
  "CECH",
  "GILBERTO_SILVA",
  "DYBALA",
  "FABREGAS",
  "RAMOS",
  "FLAMINI",
  "VALVERDE",
  "VIEIRA",
  "BUFFON",
  "AGUERO",
  "XHAKA",
  "DEPAY",
  "KLOSE",
  "RABIOT",
  "LLORIS",
  "FERNANDES",
  "KANE",
  "ERIKSEN",
  "STONES",
  "OLISE",
  "HAVERTZ",
  "GOTZE",
  "SILVA",
  "KOVAI",
];

export function getTrailPlayerByKey(key, players = TRAIL_PLAYERS) {
  return players.find((p) => p && p.key === key) || null;
}

export function getTrailAnswerForDayIndex(dayIndex, log = TRAIL_ANSWER_LOG, players = TRAIL_PLAYERS) {
  const n = dayIndex - TRAIL_ANCHOR_DAY;
  if (n < 0 || !log.length) return null;
  const key = log[n % log.length]; // wrap after the log runs out rather than going dark
  return getTrailPlayerByKey(key, players);
}

export function getTrailAnswer(date = new Date(), log = TRAIL_ANSWER_LOG, players = TRAIL_PLAYERS) {
  return getTrailAnswerForDayIndex(getTrailDayIndex(date), log, players);
}

// ── Answer matching (spec v2) ────────────────────────────────────────────────
//
// The guess is a surname typed by hand, so matching has to survive accents,
// case, punctuation and spacing. NFD + combining-mark strip turns Čech into
// cech, Özil into ozil, Agüero into aguero — one rule instead of a lookup.
//
// Accepted forms are DERIVED from `display` (surname, and the full name), so
// only genuine exceptions are listed below. Two of them are not stylistic —
// they are unwinnable without an alias: Neymar's surname in the data is
// "Júnior" and Isco's is "Alarcón". Nobody on earth types those.
export const TRAIL_ALIASES = {
  NEYMAR:         ["Neymar"],
  ISCO:           ["Isco"],
  JOAQUIN:        ["Joaquin"],
  VAN_PERSIE:     ["Persie"],
  RONALDO_C:      ["Cristiano", "CR7"],
  GILBERTO_SILVA: ["Gilberto", "Gilberto Silva"],
  GOTZE:          ["Goetze"],   // common German transliteration of ö
  OZIL:           ["Oezil"],
};

// Revealed as a hint after the third miss. Nationality already lives on the
// career row; position did not, and a nationality on its own is a weak rescue
// ("France" covers half the roster).
export const TRAIL_POSITIONS = {
  // ── WAVE N positions, from the lineup pool's own position field. Broad
  // (Goalkeeper/Defender/Midfielder/Forward) rather than the specific labels
  // some older entries carry: a correct broad hint beats a guessed precise one.
  "MESSI": "Forward",
  "MBAPP": "Forward",
  "MODRI": "Midfielder",
  "BENZEMA": "Forward",
  "KANE": "Forward",
  "DEMBL": "Forward",
  "LLORIS": "Goalkeeper",
  "GEA": "Goalkeeper",
  "DYBALA": "Forward",
  "REUS": "Midfielder",
  "HEUNGMIN": "Forward",
  "BELLINGHAM": "Midfielder",
  "BECKER": "Goalkeeper",
  "HAKIMI": "Defender",
  "FIRMINO": "Forward",
  "SZCZSNY": "Goalkeeper",
  "MAGUIRE": "Defender",
  "STEGEN": "Goalkeeper",
  "ERIKSEN": "Midfielder",
  "DEPAY": "Forward",
  "NAGATOMO": "Defender",
  "FERNANDES": "Midfielder",
  "DRAXLER": "Midfielder",
  "MINAMINO": "Midfielder",
  "RDIGER": "Defender",
  "VALVERDE": "Midfielder",
  "GNDOAN": "Midfielder",
  "HAVERTZ": "Midfielder",
  "TORRES_FER": "Forward",
  "OSAKO": "Forward",
  "FATI": "Forward",
  "DONNARUMMA": "Goalkeeper",
  "KOVAI": "Midfielder",
  "YOSHIDA": "Defender",
  "UCHIDA": "Defender",
  "SILVA": "Midfielder",
  "SAN": "Forward",
  "WERNER": "Forward",
  "PAVARD": "Defender",
  "SHIBASAKI": "Midfielder",
  "SAKAI": "Defender",
  "ALVAREZ": "Forward",
  "VZQUEZ": "Midfielder",
  "MUTO": "Forward",
  "GAKPO": "Forward",
  "CAN": "Midfielder",
  "XHAKA": "Midfielder",
  "SAKAI_HIR": "Defender",
  "RABIOT": "Midfielder",
  "JONG": "Midfielder",
  "AFELLAY": "Midfielder",
  "STONES": "Defender",
  "VERRATTI": "Midfielder",
  "OLISE": "Forward",
  "OSIMHEN": "Forward",
  "KONNO": "Defender",
  "ISAK": "Forward",
  "MARTIAL": "Forward",
  TORRES: "Forward", BALE: "Winger", VAN_PERSIE: "Forward", ALONSO: "Midfielder",
  HENRY: "Forward", SNEIJDER: "Midfielder", OZIL: "Midfielder", OWEN: "Forward",
  RONALDO_C: "Forward", ROONEY: "Forward", ROBBEN: "Winger", SEEDORF: "Midfielder",
  VIEIRA: "Midfielder", MAKELELE: "Midfielder", BALLACK: "Midfielder", MANE: "Forward",
  POGBA: "Midfielder", FABREGAS: "Midfielder", COLE_A: "Defender", BUFFON: "Goalkeeper",
  RAMOS: "Defender", CECH: "Goalkeeper", DUFF: "Winger", GOTZE: "Midfielder",
  KOMPANY: "Defender", FIGO: "Winger", KROOS: "Midfielder", NEYMAR: "Forward",
  AGUERO: "Forward", ISCO: "Midfielder", VERTONGHEN: "Defender", KANTE: "Midfielder",
  ALDERWEIRELD: "Defender", JOAQUIN: "Winger", KLOSE: "Forward", MATUIDI: "Midfielder",
  FLAMINI: "Midfielder", GILBERTO_SILVA: "Midfielder",
  // Wave M
  VAN_DIJK: "Defender", COURTOIS: "Goalkeeper", GRIEZMANN: "Forward",
  DE_BRUYNE: "Midfielder", SON: "Forward", LEWANDOWSKI: "Forward",
};

// Letters that are NOT decorated versions of an ascii letter — they are their
// own characters, so NFD does not decompose them and a naive mark-strip DELETES
// them. Measured before this existed: Ødegaard folded to "degaard", Højbjerg to
// "hjbjerg", Błaszczykowski to "baszczykowski", Đorđević to "orevic", Weiß to
// "wei". Every one of those is unwinnable — the player types the obvious plain
// spelling and it cannot match.
//
// Alex, 2026-07-29: "people write names differently you know, some swedish
// names, norwegian names, south american, they all have unique letters and dots
// everywhere so we should be graceful here." Correct, and this is the half that
// gracefulness does not come free.
//
// Note what is NOT here: é č ö ü å ñ ş all DO decompose, so the mark-strip below
// already handles them. Only the non-decomposing ones need spelling out.
const LETTER_FOLD = {
  ø: "o", æ: "ae", œ: "oe", ß: "ss", ł: "l", đ: "d", ð: "d", þ: "th",
  ı: "i", ŧ: "t", ħ: "h", ŋ: "n", ĸ: "k",
};

/** Fold a typed guess to its comparable form: accent-free, lowercase, a-z only. */
export function normaliseGuess(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/[øæœßłđðþıŧħŋĸ]/g, (c) => LETTER_FOLD[c] || c)
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z]/g, "");
}

// German and Nordic spelling admits TWO correct plain-ascii forms: Müller is
// written "Muller" or "Mueller", Ødegaard as "Odegaard" or "Oedegaard", and
// both are things a real person types. One fold cannot satisfy both, so a name
// folds to a SET and a guess matches if the sets overlap.
const DIGRAPH_FOLD = { "ü": "ue", "ö": "oe", "ä": "ae", "ø": "oe", "å": "aa" };

/** Every plain-ascii spelling this string could reasonably be typed as. */
export function normaliseVariants(s) {
  const raw = String(s || "").toLowerCase();
  const digraph = raw.replace(/[üöäøå]/g, (c) => DIGRAPH_FOLD[c] || c);
  return [...new Set([normaliseGuess(raw), normaliseGuess(digraph)].filter(Boolean))];
}

/** Every string that counts as naming this player. */
export function acceptedNamesFor(player) {
  if (!player) return [];
  const [first, last] = player.display || [];
  const out = [];
  if (last) out.push(last);
  if (first && last) out.push(`${first} ${last}`);
  if (first && !last) out.push(first);

  // ⚠️ `display` splits names INCONSISTENTLY, and that inconsistency was
  // rejecting answers the player had plainly got right (reported 2026-08-22:
  // a surname marked wrong while the full name was marked right).
  //
  // The particle sometimes rides with the forename and sometimes with the
  // surname — ["David de","Gea"] but ["Virgil","van Dijk"] — so whichever way
  // a given player is stored, ONE of the two forms a human would actually type
  // was refused:
  //
  //     Kevin De Bruyne        "Bruyne"      rejected
  //     Virgil van Dijk        "Dijk"        rejected
  //     Frenkie de Jong        "de Jong"     rejected
  //     David de Gea           "de Gea"      rejected
  //     Marc-André ter Stegen  "ter Stegen"  rejected
  //
  // So derive the forms from the WHOLE name rather than trusting the split:
  // the bare final word, and the last two words (which covers every
  // particle+surname). Both are additive — nothing previously accepted stops
  // being accepted.
  //
  // Deliberately generous. A Trail guess is limited and the mode is about
  // football knowledge, not about guessing how we happened to store a name.
  // Over-accepting costs a player nothing they did not earn; under-accepting
  // takes an attempt away from someone who KNEW the answer, which is the
  // worst outcome this mode can produce.
  const whole = [first, last].filter(Boolean).join(' ').trim();
  const words = whole ? whole.split(/\s+/) : [];
  if (words.length >= 2) out.push(words[words.length - 1]);
  if (words.length >= 3) out.push(words.slice(-2).join(' '));

  for (const alias of TRAIL_ALIASES[player.key] || []) out.push(alias);
  return [...new Set(out)];
}

export function guessMatchesPlayer(guess, player) {
  const guessForms = normaliseVariants(guess);
  if (!guessForms.length) return false;
  return acceptedNamesFor(player).some((name) =>
    normaliseVariants(name).some((n) => guessForms.includes(n))
  );
}

/**
 * How many clubs are on the ladder after `misses` wrong guesses or skips.
 * Opens at TRAIL_OPENING_CLUBS and grows by one each time, capped at the
 * career length — a 6-rung career runs out of clubs exactly as the player runs
 * out of attempts, so there is no tuning constant to drift.
 */
export const TRAIL_OPENING_CLUBS = 2;
export function cluesShown(misses, careerLength) {
  return Math.min(TRAIL_OPENING_CLUBS + Math.max(0, misses), careerLength);
}

/** The hint unlocks once three guesses are gone. */
export function hintFor(player, misses) {
  if (!player || misses < 3) return null;
  const pos = TRAIL_POSITIONS[player.key];
  return [player.nat, pos].filter(Boolean).join(" · ") || null;
}

/**
 * A day's stored Trail state, normalised to { status, used } — the same shape
 * Footle's history uses, so screens can treat all the daily modes alike.
 * Returns null when the day was never opened.
 *
 * Exported because THREE screens now need it (the Trail itself, the Daily tab,
 * the Home daily zone) and each hand-rolled read of `biq_trail_<ymd>` is a
 * chance for them to disagree about what "played" means.
 */
export function loadTrailDay(date = new Date()) {
  try {
    const raw = localStorage.getItem(`biq_trail_${dateToYMD(date)}`);
    if (!raw) return null;
    const p = JSON.parse(raw);
    return { status: p?.status || null, used: Array.isArray(p?.attempts) ? p.attempts.length : 0 };
  } catch { return null; }
}

// ── Streak ────────────────────────────────────────────────────────────────────
// Clone of computeFootleStreak: walk backwards over biq_trail_<ymd> localStorage
// entries while they exist and are wins. Storage writes live in the screen.
export function computeTrailStreak(today) {
  let streak = 0;
  const cursor = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  for (let i = 0; i < 366; i++) {
    try {
      const raw = localStorage.getItem(`biq_trail_${dateToYMD(cursor)}`);
      if (!raw) break;
      const p = JSON.parse(raw);
      if (p?.status !== "won" || p?.arc) break; // arc = archive back-fill, not streak fuel
    } catch { break; }
    streak++;
    cursor.setDate(cursor.getDate() - 1);
  }
  return streak;
}

// ── Share text (spec v2) ─────────────────────────────────────────────────────
// Spoiler-free by construction: it names neither the player nor a single club,
// only how many rungs it took. That is a stronger guarantee than v1's grid,
// which leaked the SHAPE of the career (how many clubs, how scrambled).
export function buildTrailShareText({ number, won, clubsUsed, streak } = {}) {
  const head = `⚽ Ball IQ · Transfer Trail${number > 0 ? ` #${number}` : ""}`;
  const line = won
    ? `Got it on ${clubsUsed} club${clubsUsed === 1 ? "" : "s"} ${"⚽".repeat(Math.min(clubsUsed, 6))}`
    : `Didn't get it — X/${TRAIL_MAX_ATTEMPTS}`;
  const streakLine = won && streak > 0 ? `\n🔥 ${streak}-day streak` : "";
  return `${head}\n${line}${streakLine}\n\nballiq.app/trail`;
}

