// Transfer Trail — pure game logic (docs/transfer-trail-spec.md).
//
// Daily "put the career in order" puzzle: the day's mystery footballer has
// their clubs revealed but SCRAMBLED; the player arranges them into
// chronological order in ≤5 attempts. This module is the Footle-pattern
// sibling of wordle.js/footleNumber.js: frozen schedule, pure grader,
// localStorage streak walker. No React, no side effects — unit-tested in
// tests/unit/trail-grading.test.js.
//
// DATA: TRAIL_PLAYERS ships EMPTY on purpose. Career rows are forge-generated
// (generate → skeptic re-derivation from an independent source) and then
// 100% human spot-checked before ANY entry lands here — a wrong career order
// is unfalsifiable to the player and poisons the share loop (same trust class
// as a wrong answer key). Editorial rules are LOCKED in the spec: loans
// included + marked, youth excluded, return spells = separate rungs, max 6.
import { dateToYMD } from "./date.js";
import { foldLetters, foldDigraphs } from "./letterFold.js";

export const TRAIL_MAX_ATTEMPTS = 5;

// ── Puzzle number ─────────────────────────────────────────────────────────────
// Same day-index math as footleNumber.js.
//
// ⚠️ PROVISIONAL AGAIN — the mode is DARK. It was briefly pointed at 2026-07-29
// and reverted the same hour: Alex, on seeing the screen, "transfer trail is not
// ready and not intended to look like that". Verified in prod before reverting
// that `scores` held ZERO rows for game_mode='trail', so no puzzle number had
// ever been played or shared and the anchor was still free to move. That is the
// ONLY condition under which it may move — once a single grid is out in the
// world, the number is load-bearing and shifting it renumbers everyone's.
//
// Set this to the real launch day in the SAME commit that declares the screen
// ready. Until then getTrailAnswerForDayIndex returns null for every date
// before it, so Home shows no Trail row and the route sends you home.
export const DAY_MS = 24 * 60 * 60 * 1000;
// ⚠️ LIVE. Was 20697 (2026-09-01) and commented "PROVISIONAL, mode is dark" —
// a placeholder from when the engine shipped inert awaiting a career
// spot-check. That check is now done: all 44 careers verified 2026-08-03,
// which found and fixed one real defect (Courtois listed Chelsea BEFORE the
// Atletico loan, a club he had not played a minute for) and confirmed the two
// recent moves against sources (Kante to Fenerbahce, Feb 2026; Pogba to
// Monaco, Jun 2025).
//
// The placeholder outlived its reason and left a finished daily game dark for
// days while memory recorded it as "LIVE". If you ever set this ahead again,
// verify getTrailAnswer() returns a player on the day you ship.
export const TRAIL_ANCHOR_DAY = 20668; // days since epoch — Trail #1

export function getTrailDayIndex(date = new Date()) {
  return Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / DAY_MS);
}

export function getTrailNumber(date = new Date()) {
  return getTrailDayIndex(date) - TRAIL_ANCHOR_DAY + 1;
}

// ── Dataset (filled by the verified forge waves — see header) ─────────────────
// Row shape:
//   { key:"YOUNG_A", display:["Ashley","Young"], nat:"England",
//     clubs:["Watford","Aston Villa","Man Utd","Inter","Aston Villa","Everton"],
//     loans:[false,false,false,false,false,false],   // parallel to clubs
//     years:["2003–07", ...] }                        // assist-only, optional
export const TRAIL_PLAYERS = [
  // ── WAVE N (2026-08-12): 106 careers from Wikipedia infoboxes, the
  // only source that marks loans. Generated by scripts/build-trail-candidates.mjs,
  // read one by one before merging. Club names normalised to house style.
  { key: "ZIDANE", display: ["Zinedine","Zidane"], nat: "France",
    clubs: ["Cannes","Bordeaux","Juventus","Real Madrid"],
    loans: [false,false,false,false] },
  { key: "BECKHAM", display: ["David","Beckham"], nat: "England",
    clubs: ["Man Utd","Preston North End","Real Madrid","LA Galaxy","AC Milan","PSG"],
    loans: [false,true,false,false,true,false] },
  { key: "BECKENBAUER", display: ["Franz","Beckenbauer"], nat: "Germany",
    clubs: ["Bayern Munich","New York Cosmos","Hamburger SV","New York Cosmos"],
    loans: [false,false,false,false] },
  { key: "INIESTA", display: ["Andrés","Iniesta"], nat: "Spain",
    clubs: ["Barcelona","Vissel Kobe","Emirates Club"],
    loans: [false,false,false] },
  { key: "PLATINI", display: ["Michel","Platini"], nat: "France",
    clubs: ["Nancy","Saint-Étienne","Juventus"],
    loans: [false,false,false] },
  { key: "HAZARD", display: ["Eden","Hazard"], nat: "Belgium",
    clubs: ["Lille","Chelsea","Real Madrid"],
    loans: [false,false,false] },
  { key: "PIQUE", display: ["Gerard","Piqué"], nat: "Spain",
    clubs: ["Man Utd","Zaragoza","Barcelona"],
    loans: [false,true,false] },
  { key: "MULLER", display: ["Gerd","Müller"], nat: "Germany",
    clubs: ["1861 Nördlingen","Bayern Munich","Fort Lauderdale Strikers"],
    loans: [false,false,false] },
  { key: "STEFANO", display: ["Alfredo Di","Stéfano"], nat: "Spain",
    clubs: ["River Plate","Huracán","Millonarios","Real Madrid","Espanyol"],
    loans: [false,true,false,false,false] },
  { key: "LINEKER", display: ["Gary","Lineker"], nat: "England",
    clubs: ["Leicester City","Everton","Barcelona","Tottenham","Nagoya Grampus"],
    loans: [false,false,false,false,false] },
  { key: "SHEVCHENKO", display: ["Andriy","Shevchenko"], nat: "Ukraine",
    clubs: ["Dynamo Kyiv","AC Milan","Chelsea","AC Milan","Dynamo Kyiv"],
    loans: [false,false,false,true,false] },
  { key: "PIERO", display: ["Alessandro Del","Piero"], nat: "Italy",
    clubs: ["Padova","Juventus","Sydney","Delhi Dynamos"],
    loans: [false,false,false,false] },
  { key: "CHARLTON", display: ["Bobby","Charlton"], nat: "England",
    clubs: ["Man Utd","Preston North End","Waterford","Newcastle KB United","Perth Azzurri","Blacktown City"],
    loans: [false,false,false,false,false,false] },
  { key: "MARCELO", display: ["","Marcelo"], nat: "Brazil",
    clubs: ["Fluminense","Real Madrid","Olympiacos","Fluminense"],
    loans: [false,false,false,false] },
  { key: "TERRY", display: ["John","Terry"], nat: "England",
    clubs: ["Chelsea","Nottingham Forest","Aston Villa"],
    loans: [false,true,false] },
  { key: "VARANE", display: ["Raphaël","Varane"], nat: "France",
    clubs: ["Lens","Real Madrid","Man Utd","Como"],
    loans: [false,false,false,false] },
  { key: "VIDIC", display: ["Nemanja","Vidić"], nat: "Serbia",
    clubs: ["Red Star Belgrade","Spartak Subotica","Spartak Moscow","Man Utd","Inter Milan"],
    loans: [false,true,false,false,false] },
  { key: "BERGKAMP", display: ["Dennis","Bergkamp"], nat: "Netherlands",
    clubs: ["Ajax","Inter Milan","Arsenal"],
    loans: [false,false,false] },
  { key: "SAR", display: ["Edwin van der","Sar"], nat: "Netherlands",
    clubs: ["Ajax","Juventus","Fulham","Man Utd","Noordwijk"],
    loans: [false,false,false,false,false] },
  { key: "SCHWEINSTEIGER", display: ["Bastian","Schweinsteiger"], nat: "Germany",
    clubs: ["Bayern Munich","Man Utd","Chicago Fire"],
    loans: [false,false,false] },
  { key: "SILVA_DAV", display: ["David","Silva"], nat: "Spain",
    clubs: ["Valencia","Eibar","Celta Vigo","Man City","Real Sociedad"],
    loans: [false,true,true,false,false] },
  { key: "KHEDIRA", display: ["Sami","Khedira"], nat: "Germany",
    clubs: ["VfB Stuttgart","Real Madrid","Juventus","Hertha BSC"],
    loans: [false,false,false,false] },
  { key: "HUMMELS", display: ["Mats","Hummels"], nat: "Germany",
    clubs: ["Bayern Munich","Borussia Dortmund","Bayern Munich","Borussia Dortmund","Roma"],
    loans: [false,false,false,false,false] },
  { key: "SHEARER", display: ["Alan","Shearer"], nat: "England",
    clubs: ["Southampton","Blackburn Rovers","Newcastle United"],
    loans: [false,false,false] },
  { key: "VALDES", display: ["Víctor","Valdés"], nat: "Spain",
    clubs: ["Barcelona","Man Utd","Standard Liège","Middlesbrough"],
    loans: [false,false,true,false] },
  { key: "THURAM", display: ["Lilian","Thuram"], nat: "France",
    clubs: ["Monaco","Parma","Juventus","Barcelona"],
    loans: [false,false,false,false] },
  { key: "FERDINAND", display: ["Rio","Ferdinand"], nat: "England",
    clubs: ["West Ham","Bournemouth","Leeds United","Man Utd","QPR"],
    loans: [false,true,false,false,false] },
  { key: "GOMEZ", display: ["Mario","Gómez"], nat: "Germany",
    clubs: ["VfB Stuttgart","Bayern Munich","Fiorentina","Beşiktaş","VfL Wolfsburg","VfB Stuttgart"],
    loans: [false,false,false,true,false,false] },
  { key: "KEEGAN", display: ["Kevin","Keegan"], nat: "England",
    clubs: ["Scunthorpe United","Liverpool","Hamburger SV","Southampton","Newcastle United","Blacktown City"],
    loans: [false,false,false,false,false,false] },
  { key: "ARSHAVIN", display: ["Andrey","Arshavin"], nat: "Russia",
    clubs: ["Zenit","Arsenal","Zenit","Kuban Krasnodar","Kairat"],
    loans: [false,false,false,false,false] },
  { key: "ZANETTI", display: ["Javier","Zanetti"], nat: "Argentina",
    clubs: ["Talleres","Banfield","Inter Milan"],
    loans: [false,false,false] },
  { key: "JOTA", display: ["Diogo","Jota"], nat: "Portugal",
    clubs: ["Paços de Ferreira","Atletico Madrid","Porto","Wolves","Liverpool"],
    loans: [false,false,true,false,false] },
  { key: "TURAN", display: ["Arda","Turan"], nat: "Turkey",
    clubs: ["Galatasaray","Manisaspor","Atletico Madrid","Barcelona","Başakşehir","Galatasaray"],
    loans: [false,true,false,false,true,false] },
  { key: "ARBELOA", display: ["Álvaro","Arbeloa"], nat: "Spain",
    clubs: ["Real Madrid","Deportivo","Liverpool","Real Madrid","West Ham"],
    loans: [false,false,false,false,false] },
  { key: "RIJKAARD", display: ["Frank","Rijkaard"], nat: "Netherlands",
    clubs: ["Ajax","Sporting CP","Zaragoza","AC Milan","Ajax"],
    loans: [false,false,true,false,false] },
  { key: "CARRICK", display: ["Michael","Carrick"], nat: "England",
    clubs: ["West Ham","Swindon Town","Birmingham City","Tottenham","Man Utd"],
    loans: [false,true,true,false,false] },
  { key: "ZOFF", display: ["Dino","Zoff"], nat: "Italy",
    clubs: ["Udinese","Mantova","Napoli","Juventus"],
    loans: [false,false,false,false] },
  { key: "ALBIOL", display: ["Raúl","Albiol"], nat: "Spain",
    clubs: ["Valencia","Getafe","Real Madrid","Napoli","Villarreal","Pisa"],
    loans: [false,true,false,false,false,false] },
  { key: "UMTITI", display: ["Samuel","Umtiti"], nat: "France",
    clubs: ["Lyon","Barcelona","Lecce","Lille"],
    loans: [false,false,true,false] },
  { key: "KUYT", display: ["Dirk","Kuyt"], nat: "Netherlands",
    clubs: ["Utrecht","Feyenoord","Liverpool","Fenerbahçe","Feyenoord"],
    loans: [false,false,false,false,false] },
  { key: "SCHILLACI", display: ["Salvatore","Schillaci"], nat: "Italy",
    clubs: ["Messina","Juventus","Inter Milan","Júbilo Iwata"],
    loans: [false,false,false,false] },
  { key: "WALCOTT", display: ["Theo","Walcott"], nat: "England",
    clubs: ["Southampton","Arsenal","Everton","Southampton"],
    loans: [false,false,false,false] },
  { key: "ALABA", display: ["David","Alaba"], nat: "Austria",
    clubs: ["Bayern Munich","Hoffenheim","Real Madrid","Udinese"],
    loans: [false,true,false,false] },
  { key: "VARDY", display: ["Jamie","Vardy"], nat: "England",
    clubs: ["Stocksbridge Park Steels","FC Halifax Town","Fleetwood Town","Leicester City","Cremonese","Burnley"],
    loans: [false,false,false,false,false,false] },
  { key: "MERTESACKER", display: ["Per","Mertesacker"], nat: "Germany",
    clubs: ["Hannover 96","Werder Bremen","Arsenal"],
    loans: [false,false,false] },
  { key: "AZPILICUETA", display: ["César","Azpilicueta"], nat: "Spain",
    clubs: ["Osasuna","Marseille","Chelsea","Atletico Madrid","Sevilla"],
    loans: [false,false,false,false,false] },
  { key: "LEHMANN", display: ["Jens","Lehmann"], nat: "Germany",
    clubs: ["Schalke 04","AC Milan","Borussia Dortmund","Arsenal","VfB Stuttgart","Arsenal"],
    loans: [false,false,false,false,false,false] },
  { key: "SOLSKJAER", display: ["Ole Gunnar","Solskjær"], nat: "Norway",
    clubs: ["Clausenengen","Molde","Man Utd"],
    loans: [false,false,false] },
  { key: "NAVAS", display: ["Jesús","Navas"], nat: "Spain",
    clubs: ["Sevilla","Man City","Sevilla"],
    loans: [false,false,false] },
  { key: "GATTUSO", display: ["Gennaro","Gattuso"], nat: "Italy",
    clubs: ["Perugia","Rangers","Salernitana","AC Milan","Sion"],
    loans: [false,false,false,false,false] },
  { key: "RUMMENIGGE", display: ["Karl-Heinz","Rummenigge"], nat: "Germany",
    clubs: ["Bayern Munich","Inter Milan","Servette"],
    loans: [false,false,false] },
  { key: "NEDVED", display: ["Pavel","Nedvěd"], nat: "Czechia",
    clubs: ["Dukla Prague","Sparta Prague","Lazio","Juventus"],
    loans: [false,false,false,false] },
  { key: "IVANOVIC", display: ["Branislav","Ivanović"], nat: "Serbia",
    clubs: ["Srem","OFK Beograd","Lokomotiv Moscow","Chelsea","Zenit","West Brom"],
    loans: [false,false,false,false,false,false] },
  { key: "ENDO", display: ["Wataru","Endō"], nat: "Japan",
    clubs: ["Shonan Bellmare","Urawa Red Diamonds","Sint-Truiden","VfB Stuttgart","Liverpool"],
    loans: [false,false,false,false,false] },
  { key: "ALCANTARA", display: ["Thiago","Alcântara"], nat: "Spain",
    clubs: ["Barcelona","Bayern Munich","Liverpool"],
    loans: [false,false,false] },
  { key: "ORIGI", display: ["Divock","Origi"], nat: "Belgium",
    clubs: ["Lille","Liverpool","Lille","VfL Wolfsburg","AC Milan","Nottingham Forest"],
    loans: [false,false,true,true,false,true] },
  { key: "BLASZCZYKOWSKI", display: ["Jakub","Błaszczykowski"], nat: "Poland",
    clubs: ["KS Częstochowa","Wisła Kraków","Borussia Dortmund","Fiorentina","VfL Wolfsburg","Wisła Kraków"],
    loans: [false,false,false,true,false,false] },
  { key: "VERMAELEN", display: ["Thomas","Vermaelen"], nat: "Belgium",
    clubs: ["Ajax","RKC Waalwijk","Arsenal","Barcelona","Roma","Vissel Kobe"],
    loans: [false,true,false,false,true,false] },
  { key: "MUSTAFI", display: ["Shkodran","Mustafi"], nat: "Germany",
    clubs: ["Everton","Sampdoria","Valencia","Arsenal","Schalke 04","Levante"],
    loans: [false,false,false,false,false,false] },
  { key: "SAGNA", display: ["Bacary","Sagna"], nat: "France",
    clubs: ["Auxerre","Arsenal","Man City","Benevento","Montreal Impact"],
    loans: [false,false,false,false,false] },
  { key: "KEANE", display: ["Roy","Keane"], nat: "Republic of Ireland",
    clubs: ["Cobh Ramblers","Nottingham Forest","Man Utd","Celtic"],
    loans: [false,false,false,false] },
  { key: "DESAILLY", display: ["Marcel","Desailly"], nat: "France",
    clubs: ["Nantes","Marseille","AC Milan","Chelsea","Al-Gharafa","Qatar SC"],
    loans: [false,false,false,false,false,false] },
  { key: "BREITNER", display: ["Paul","Breitner"], nat: "Germany",
    clubs: ["Bayern Munich","Real Madrid","Eintracht Braunschweig","Bayern Munich"],
    loans: [false,false,false,false] },
  { key: "BARTHEZ", display: ["Fabien","Barthez"], nat: "France",
    clubs: ["Toulouse","Marseille","Monaco","Man Utd","Marseille","Nantes"],
    loans: [false,false,false,false,false,false] },
  { key: "MILITO", display: ["Diego","Milito"], nat: "Argentina",
    clubs: ["Racing Club","Genoa","Zaragoza","Genoa","Inter Milan","Racing Club"],
    loans: [false,false,false,false,false,false] },
  { key: "FELLAINI", display: ["Marouane","Fellaini"], nat: "Belgium",
    clubs: ["Standard Liège","Everton","Man Utd","Shandong Taishan"],
    loans: [false,false,false,false] },
  { key: "BRAVO", display: ["Claudio","Bravo"], nat: "Chile",
    clubs: ["Colo-Colo","Real Sociedad","Barcelona","Man City","Real Betis"],
    loans: [false,false,false,false,false] },
  { key: "WILSHERE", display: ["Jack","Wilshere"], nat: "England",
    clubs: ["Arsenal","Bolton Wanderers","Bournemouth","West Ham","Bournemouth","AGF"],
    loans: [false,true,true,false,false,false] },
  { key: "MOTTA", display: ["Thiago","Motta"], nat: "Italy",
    clubs: ["Barcelona","Atletico Madrid","Genoa","Inter Milan","PSG"],
    loans: [false,false,false,false,false] },
  { key: "FONTAINE", display: ["Just","Fontaine"], nat: "France",
    clubs: ["US Marocaine","Nice","Reims"],
    loans: [false,false,false] },
  { key: "TOURE", display: ["Kolo","Touré"], nat: "Ivory Coast",
    clubs: ["ASEC Mimosas","Arsenal","Man City","Liverpool","Celtic"],
    loans: [false,false,false,false,false] },
  { key: "NATALE", display: ["Antonio Di","Natale"], nat: "Italy",
    clubs: ["Empoli","Iperzola","Varese","Viareggio","Udinese"],
    loans: [false,true,true,true,false] },
  { key: "NESTA", display: ["Alessandro","Nesta"], nat: "Italy",
    clubs: ["Lazio","AC Milan","Montreal Impact","Chennaiyin"],
    loans: [false,false,false,false] },
  { key: "SMALLING", display: ["Chris","Smalling"], nat: "England",
    clubs: ["Maidstone United","Fulham","Man Utd","Roma","Al-Fayha","Porto"],
    loans: [false,false,false,false,false,false] },
  { key: "VOLLER", display: ["Rudi","Völler"], nat: "Germany",
    clubs: ["Kickers Offenbach","1860 Munich","Werder Bremen","Roma","Marseille","Leverkusen"],
    loans: [false,false,false,false,false,false] },
  { key: "SRNA", display: ["Darijo","Srna"], nat: "Croatia",
    clubs: ["Hajduk Split","Shakhtar Donetsk","Cagliari"],
    loans: [false,false,false] },
  { key: "MARCHISIO", display: ["Claudio","Marchisio"], nat: "Italy",
    clubs: ["Juventus","Empoli","Zenit"],
    loans: [false,true,false] },
  { key: "ROSICKY", display: ["Tomáš","Rosický"], nat: "Czechia",
    clubs: ["Sparta Prague","Borussia Dortmund","Arsenal","Sparta Prague"],
    loans: [false,false,false,false] },
  { key: "RIQUELME", display: ["Juan Román","Riquelme"], nat: "Argentina",
    clubs: ["Boca Juniors","Barcelona","Villarreal","Boca Juniors","Argentinos Juniors"],
    loans: [false,false,false,false,false] },
  { key: "BOMMEL", display: ["Mark van","Bommel"], nat: "Netherlands",
    clubs: ["Fortuna Sittard","PSV","Barcelona","Bayern Munich","AC Milan","PSV"],
    loans: [false,false,false,false,false,false] },
  { key: "BRONCKHORST", display: ["Giovanni van","Bronckhorst"], nat: "Netherlands",
    clubs: ["Feyenoord","RKC Waalwijk","Rangers","Arsenal","Barcelona","Feyenoord"],
    loans: [false,true,false,false,false,false] },
  { key: "STOJKOVIC", display: ["Dragan","Stojković"], nat: "Yugoslavia",
    clubs: ["Radnički Niš","Red Star Belgrade","Marseille","Verona","Nagoya Grampus"],
    loans: [false,false,false,true,false] },
  { key: "PATRICIO", display: ["Rui","Patrício"], nat: "Portugal",
    clubs: ["Sporting CP","Wolves","Roma","Atalanta","Al Ain"],
    loans: [false,false,false,false,false] },
  { key: "CORLUKA", display: ["Vedran","Ćorluka"], nat: "Croatia",
    clubs: ["Dinamo Zagreb","Inter Zaprešić","Man City","Tottenham","Leverkusen","Lokomotiv Moscow"],
    loans: [false,true,false,false,true,false] },
  { key: "HOWEDES", display: ["Benedikt","Höwedes"], nat: "Germany",
    clubs: ["Schalke 04","Juventus","Lokomotiv Moscow"],
    loans: [false,true,false] },
  { key: "MEIRELES", display: ["Raul","Meireles"], nat: "Portugal",
    clubs: ["Boavista","Aves","Porto","Liverpool","Chelsea","Fenerbahçe"],
    loans: [false,true,false,false,false,false] },
  { key: "LIZARAZU", display: ["Bixente","Lizarazu"], nat: "France",
    clubs: ["Bordeaux","Athletic Bilbao","Bayern Munich","Marseille","Bayern Munich"],
    loans: [false,false,false,false,false] },
  { key: "COMAN", display: ["Kingsley","Coman"], nat: "France",
    clubs: ["PSG","Juventus","Bayern Munich","Al-Nassr"],
    loans: [false,false,false,false] },
  { key: "OLMO", display: ["Dani","Olmo"], nat: "Spain",
    clubs: ["Dinamo Zagreb","RB Leipzig","Barcelona"],
    loans: [false,false,false] },
  { key: "JESUS", display: ["Gabriel","Jesus"], nat: "Brazil",
    clubs: ["Palmeiras","Man City","Arsenal","Barcelona"],
    loans: [false,false,false,false] },
  { key: "PULISIC", display: ["Christian","Pulisic"], nat: "United States",
    clubs: ["Borussia Dortmund","Chelsea","AC Milan"],
    loans: [false,false,false] },
  { key: "CHIESA", display: ["Federico","Chiesa"], nat: "Italy",
    clubs: ["Fiorentina","Juventus","Liverpool"],
    loans: [false,false,false] },
  { key: "FERNANDEZ", display: ["Enzo","Fernández"], nat: "Argentina",
    clubs: ["River Plate","Defensa y Justicia","Benfica","Chelsea","Man City"],
    loans: [false,true,false,false,false] },
  { key: "LEAO", display: ["Rafael","Leão"], nat: "Portugal",
    clubs: ["Sporting CP","Lille","AC Milan","Galatasaray"],
    loans: [false,false,false,false] },
  { key: "COSTA", display: ["Rui","Costa"], nat: "Portugal",
    clubs: ["Benfica","Fafe","Fiorentina","AC Milan","Benfica"],
    loans: [false,true,false,false,false] },
  { key: "BARRY", display: ["Gareth","Barry"], nat: "England",
    clubs: ["Aston Villa","Man City","Everton","West Brom"],
    loans: [false,false,false,false] },
  { key: "BONIEK", display: ["Zbigniew","Boniek"], nat: "Poland",
    clubs: ["Zawisza Bydgoszcz","Widzew Łódź","Juventus","Roma"],
    loans: [false,false,false,false] },
  { key: "GNABRY", display: ["Serge","Gnabry"], nat: "Germany",
    clubs: ["Arsenal","West Brom","Werder Bremen","Bayern Munich","Hoffenheim"],
    loans: [false,true,false,false,true] },
  { key: "ROBERTO", display: ["Sergi","Roberto"], nat: "Spain",
    clubs: ["Barcelona","Como","LA Galaxy"],
    loans: [false,false,false] },
  { key: "CALHANOGLU", display: ["Hakan","Çalhanoğlu"], nat: "Turkey",
    clubs: ["Karlsruher SC","Hamburger SV","Leverkusen","AC Milan","Inter Milan"],
    loans: [false,false,false,false,false] },
  { key: "DIER", display: ["Eric","Dier"], nat: "England",
    clubs: ["Sporting CP","Tottenham","Bayern Munich","Monaco"],
    loans: [false,false,false,false] },
  { key: "GALLAS", display: ["William","Gallas"], nat: "France",
    clubs: ["Caen","Marseille","Chelsea","Arsenal","Tottenham","Perth Glory"],
    loans: [false,false,false,false,false,false] },
  { key: "HERNANDEZ", display: ["Lucas","Hernandez"], nat: "France",
    clubs: ["Atletico Madrid","Bayern Munich","PSG"],
    loans: [false,false,false] },
  { key: "VLAHOVIC", display: ["Dušan","Vlahović"], nat: "Serbia",
    clubs: ["Partizan","Fiorentina","Juventus","Beşiktaş"],
    loans: [false,false,false,false] },
  { key: "TCHOUAMENI", display: ["Aurélien","Tchouaméni"], nat: "France",
    clubs: ["Bordeaux","Monaco","Real Madrid"],
    loans: [false,false,false] },
  { key: "KOUNDE", display: ["Jules","Koundé"], nat: "France",
    clubs: ["Bordeaux","Sevilla","Barcelona"],
    loans: [false,false,false] },
  // ── WAVE N (2026-08-12): 58 careers from Wikipedia infoboxes, the
  // only source that marks loans. Generated by scripts/build-trail-candidates.mjs,
  // read one by one before merging. Club names normalised to house style.
  { key: "MESSI", display: ["Lionel","Messi"], nat: "Argentina",
    clubs: ["Barcelona","PSG","Inter Miami"],
    loans: [false,false,false] },
  { key: "MBAPP", display: ["Kylian","Mbappé"], nat: "France",
    clubs: ["Monaco","PSG","Real Madrid"],
    loans: [false,false,false] },
  { key: "MODRI", display: ["Luka","Modrić"], nat: "Croatia",
    clubs: ["Dinamo Zagreb","Zrinjski Mostar","Inter Zaprešić","Tottenham","Real Madrid","AC Milan"],
    loans: [false,true,true,false,false,false] },
  { key: "BENZEMA", display: ["Karim","Benzema"], nat: "France",
    clubs: ["Lyon","Real Madrid","Al-Ittihad","Al-Hilal"],
    loans: [false,false,false,false] },
  { key: "KANE", display: ["Harry","Kane"], nat: "England",
    clubs: ["Tottenham","Leyton Orient","Millwall","Norwich City","Leicester City","Bayern Munich"],
    loans: [false,true,true,true,true,false] },
  { key: "DEMBL", display: ["Ousmane","Dembélé"], nat: "France",
    clubs: ["Rennes","Borussia Dortmund","Barcelona","PSG"],
    loans: [false,false,false,false] },
  { key: "LLORIS", display: ["Hugo","Lloris"], nat: "France",
    clubs: ["Nice","Lyon","Tottenham","LAFC"],
    loans: [false,false,false,false] },
  { key: "GEA", display: ["David de","Gea"], nat: "Spain",
    clubs: ["Atletico Madrid","Man Utd","Fiorentina"],
    loans: [false,false,false] },
  { key: "DYBALA", display: ["Paulo","Dybala"], nat: "Argentina",
    clubs: ["Instituto","Palermo","Juventus","Roma"],
    loans: [false,false,false,false] },
  { key: "REUS", display: ["Marco","Reus"], nat: "Germany",
    clubs: ["Rot Weiss Ahlen","Borussia M.gladbach","Borussia Dortmund","LA Galaxy"],
    loans: [false,false,false,false] },
  // PARK replaced HEUNGMIN 2026-09-28 — HEUNGMIN was a second key for Son
  // Heung-min (see SON below). Only unserved days changed (#85/#161/#285/#339).
  // Verified by the bank-verifier: Kyoto→PSV 2003 was a permanent transfer,
  // the 2013–14 PSV spell a loan from QPR; "Kyoto Purple Sanga" is the club's
  // name in his era (renamed 2010); retired May 2014, so this cannot rot.
  { key: "PARK", display: ["Park","Ji-sung"], nat: "South Korea",
    clubs: ["Kyoto Purple Sanga","PSV","Man Utd","QPR","PSV"],
    loans: [false,false,false,false,true] },
  { key: "BELLINGHAM", display: ["Jude","Bellingham"], nat: "England",
    clubs: ["Birmingham City","Borussia Dortmund","Real Madrid"],
    loans: [false,false,false] },
  { key: "BECKER", display: ["Alisson","Becker"], nat: "Brazil",
    clubs: ["Internacional","Roma","Liverpool"],
    loans: [false,false,false] },
  { key: "HAKIMI", display: ["Achraf","Hakimi"], nat: "Morocco",
    clubs: ["Real Madrid","Borussia Dortmund","Inter Milan","PSG"],
    loans: [false,true,false,false] },
  { key: "FIRMINO", display: ["Roberto","Firmino"], nat: "Brazil",
    clubs: ["Figueirense","Hoffenheim","Liverpool","Al-Ahli","Al Sadd"],
    loans: [false,false,false,false,false] },
  { key: "SZCZSNY", display: ["Wojciech","Szczęsny"], nat: "Poland",
    clubs: ["Arsenal","Brentford","Roma","Juventus","Barcelona"],
    loans: [false,true,true,false,false] },
  { key: "MAGUIRE", display: ["Harry","Maguire"], nat: "England",
    clubs: ["Sheffield Utd","Hull City","Wigan Athletic","Leicester City","Man Utd"],
    loans: [false,false,true,false,false] },
  { key: "STEGEN", display: ["Marc-André ter","Stegen"], nat: "Germany",
    clubs: ["Borussia M.gladbach","Barcelona","Girona","Ajax"],
    loans: [false,false,true,true] },
  { key: "ERIKSEN", display: ["Christian","Eriksen"], nat: "Denmark",
    clubs: ["Ajax","Tottenham","Inter Milan","Brentford","Man Utd","VfL Wolfsburg"],
    loans: [false,false,false,false,false,false] },
  { key: "DEPAY", display: ["Memphis","Depay"], nat: "Netherlands",
    clubs: ["PSV Eindhoven","Man Utd","Lyon","Barcelona","Atletico Madrid","Corinthians"],
    loans: [false,false,false,false,false,false] },
  { key: "NAGATOMO", display: ["Yūto","Nagatomo"], nat: "Japan",
    clubs: ["FC Tokyo","Cesena","Inter Milan","Galatasaray","Marseille","FC Tokyo"],
    loans: [false,true,false,false,false,false] },
  { key: "FERNANDES", display: ["Bruno","Fernandes"], nat: "Portugal",
    clubs: ["Novara","Udinese","Sampdoria","Sporting CP","Man Utd"],
    loans: [false,false,false,false,false] },
  { key: "DRAXLER", display: ["Julian","Draxler"], nat: "Germany",
    clubs: ["Schalke 04","VfL Wolfsburg","PSG","Benfica","Al Ahli"],
    loans: [false,false,false,true,false] },
  { key: "MINAMINO", display: ["Takumi","Minamino"], nat: "Japan",
    clubs: ["Cerezo Osaka","RB Salzburg","Liverpool","Southampton","Monaco"],
    loans: [false,false,false,true,false] },
  { key: "RDIGER", display: ["Antonio","Rüdiger"], nat: "Germany",
    clubs: ["VfB Stuttgart","Roma","Chelsea","Real Madrid"],
    loans: [false,false,false,false] },
  { key: "VALVERDE", display: ["Federico","Valverde"], nat: "Uruguay",
    clubs: ["Peñarol","Real Madrid","Deportivo"],
    loans: [false,false,true] },
  { key: "GNDOAN", display: ["İlkay","Gündoğan"], nat: "Germany",
    clubs: ["1. FC Nürnberg","Borussia Dortmund","Man City","Barcelona","Man City","Galatasaray"],
    loans: [false,false,false,false,false,false] },
  { key: "HAVERTZ", display: ["Kai","Havertz"], nat: "Germany",
    clubs: ["Leverkusen","Chelsea","Arsenal"],
    loans: [false,false,false] },
  { key: "TORRES_FER", display: ["Ferran","Torres"], nat: "Spain",
    // + PSG 2026-08-15 (€50m from Barcelona, verified: both clubs' official
    // announcements + BBC/AFP). All four of his TRAIL_ANSWER_LOG days are
    // future (first: log index 32), so this is a content fix, not a
    // schedule change.
    clubs: ["Valencia","Man City","Barcelona","PSG"],
    loans: [false,false,false,false] },
  { key: "OSAKO", display: ["Yuya","Osako"], nat: "Japan",
    clubs: ["Kashima Antlers","1860 Munich","1. FC Köln","Werder Bremen","Vissel Kobe"],
    loans: [false,false,false,false,false] },
  { key: "FATI", display: ["Ansu","Fati"], nat: "Spain",
    clubs: ["Barcelona","Brighton","Monaco"],
    loans: [false,true,false] },
  { key: "DONNARUMMA", display: ["Gianluigi","Donnarumma"], nat: "Italy",
    clubs: ["AC Milan","PSG","Man City"],
    loans: [false,false,false] },
  { key: "KOVAI", display: ["Mateo","Kovačić"], nat: "Croatia",
    clubs: ["Dinamo Zagreb","Inter Milan","Real Madrid","Chelsea","Man City"],
    loans: [false,false,false,false,false] },
  { key: "YOSHIDA", display: ["Maya","Yoshida"], nat: "Japan",
    clubs: ["Nagoya Grampus","VVV-Venlo","Southampton","Sampdoria","Schalke 04","LA Galaxy"],
    loans: [false,false,false,false,false,false] },
  { key: "UCHIDA", display: ["Atsuto","Uchida"], nat: "Japan",
    clubs: ["Kashima Antlers","Schalke 04","Union Berlin","Kashima Antlers"],
    loans: [false,false,false,false] },
  { key: "SILVA", display: ["Bernardo","Silva"], nat: "Portugal",
    clubs: ["Benfica","Monaco","Man City","Real Madrid"],
    loans: [false,false,false,false] },
  { key: "SAN", display: ["Leroy","Sané"], nat: "Germany",
    clubs: ["Schalke 04","Man City","Bayern Munich","Galatasaray"],
    loans: [false,false,false,false] },
  { key: "WERNER", display: ["Timo","Werner"], nat: "Germany",
    clubs: ["VfB Stuttgart","RB Leipzig","Chelsea","RB Leipzig","Tottenham","San Jose Earthquakes"],
    loans: [false,false,false,false,true,false] },
  { key: "PAVARD", display: ["Benjamin","Pavard"], nat: "France",
    clubs: ["Lille","VfB Stuttgart","Bayern Munich","Inter Milan","Marseille"],
    loans: [false,false,false,false,true] },
  { key: "SHIBASAKI", display: ["Gaku","Shibasaki"], nat: "Japan",
    clubs: ["Kashima Antlers","Tenerife","Getafe","Deportivo","Leganés","Kashima Antlers"],
    loans: [false,false,false,false,false,false] },
  { key: "SAKAI", display: ["Gōtoku","Sakai"], nat: "Japan",
    clubs: ["Albirex Niigata","VfB Stuttgart","Hamburger SV","Vissel Kobe"],
    loans: [false,false,false,false] },
  { key: "ALVAREZ", display: ["Julián","Alvarez"], nat: "Argentina",
    clubs: ["River Plate","Man City","River Plate","Atletico Madrid"],
    loans: [false,false,true,false] },
  { key: "VZQUEZ", display: ["Lucas","Vázquez"], nat: "Spain",
    clubs: ["Espanyol","Real Madrid","Leverkusen"],
    loans: [true,false,false] },
  { key: "MUTO", display: ["Yoshinori","Muto"], nat: "Japan",
    clubs: ["FC Tokyo","Mainz 05","Newcastle United","Eibar","Vissel Kobe"],
    loans: [false,false,false,true,false] },
  { key: "GAKPO", display: ["Cody","Gakpo"], nat: "Netherlands",
    clubs: ["Jong PSV","PSV","Liverpool"],
    loans: [false,false,false] },
  { key: "CAN", display: ["Emre","Can"], nat: "Germany",
    clubs: ["Bayern Munich","Leverkusen","Liverpool","Juventus","Borussia Dortmund"],
    loans: [false,false,false,false,false] },
  { key: "XHAKA", display: ["Granit","Xhaka"], nat: "Switzerland",
    clubs: ["Basel","Borussia M.gladbach","Arsenal","Leverkusen","Sunderland"],
    loans: [false,false,false,false,false] },
  { key: "SAKAI_HIR", display: ["Hiroki","Sakai"], nat: "Japan",
    clubs: ["Kashiwa Reysol","Hannover 96","Marseille","Urawa Red Diamonds","Auckland"],
    loans: [false,false,false,false,false] },
  { key: "RABIOT", display: ["Adrien","Rabiot"], nat: "France",
    clubs: ["PSG","Toulouse","Juventus","Marseille","AC Milan"],
    loans: [false,true,false,false,false] },
  { key: "JONG", display: ["Frenkie de","Jong"], nat: "Netherlands",
    clubs: ["Jong Ajax","Ajax","Barcelona"],
    loans: [false,false,false] },
  { key: "AFELLAY", display: ["Ibrahim","Afellay"], nat: "Netherlands",
    // ⚠️ WAS CORRUPT UNTIL 2026-08-12, and would have rendered as a rung reading
    // "PSV Eindhoven |caps1 = 159 |goals1 = 35" on Trail #29. His infobox puts
    // clubs, caps and goals on ONE line — the only article in 102 that does —
    // so the generator's end-of-line capture swallowed two extra fields into
    // every club name. Nothing in the build could see it: the tests check
    // schedule shape, not that a club name is a club name. Found by
    // scripts/verify-trail-careers.mjs on its first real run, 19 days before
    // the puzzle was due. The parser now cuts trailing infobox fields.
    clubs: ["PSV","Barcelona","Schalke 04","Olympiacos","Stoke City","PSV"],
    loans: [false,false,true,true,false,false] },
  { key: "STONES", display: ["John","Stones"], nat: "England",
    clubs: ["Barnsley","Everton","Man City","Inter Milan"],
    loans: [false,false,false,false] },
  { key: "VERRATTI", display: ["Marco","Verratti"], nat: "Italy",
    clubs: ["Pescara","PSG","Al-Arabi","Al Duhail"],
    loans: [false,false,false,false] },
  { key: "OLISE", display: ["Michael","Olise"], nat: "France",
    clubs: ["Reading","Crystal Palace","Bayern Munich"],
    loans: [false,false,false] },
  { key: "OSIMHEN", display: ["Victor","Osimhen"], nat: "Nigeria",
    clubs: ["VfL Wolfsburg","Charleroi","Lille","Napoli","Galatasaray"],
    loans: [false,false,false,false,false] },
  { key: "KONNO", display: ["Yasuyuki","Konno"], nat: "Japan",
    clubs: ["Consadole Sapporo","FC Tokyo","Gamba Osaka","Júbilo Iwata","Nankatsu SC"],
    loans: [false,false,false,false,false] },
  { key: "ISAK", display: ["Alexander","Isak"], nat: "Sweden",
    clubs: ["AIK","Borussia Dortmund","Real Sociedad","Newcastle United","Liverpool"],
    loans: [false,false,false,false,false] },
  { key: "MARTIAL", display: ["Anthony","Martial"], nat: "France",
    clubs: ["Lyon","Monaco","Man Utd","Sevilla","AEK Athens","Monterrey"],
    loans: [false,false,false,true,false,false] },
  // Wave 1 — forge-generated (generate → independent web re-derivation vs
  // Wikipedia/Transfermarkt, all verified:true high-confidence) + Alex spot-
  // checked 2026-07-21. `display` corrected from the forge (a schema-wording
  // slip had some agents emit clubs there). 4 others from the batch were
  // rejected: Young(7)/Villa(8)/Pirlo(8) exceed the 6-rung max (not truncated,
  // per the locked rules); Modrić dropped editorially (obscure loan openers).
  { key: "TORRES", display: ["Fernando", "Torres"], nat: "Spain",
    clubs: ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan", "Atletico Madrid", "Sagan Tosu"],
    loans: [false, false, false, true, false, false] },
  { key: "BALE", display: ["Gareth", "Bale"], nat: "Wales",
    clubs: ["Southampton", "Tottenham", "Real Madrid", "Tottenham", "Real Madrid", "LAFC"],
    loans: [false, false, false, true, false, false] },
  { key: "VAN_PERSIE", display: ["Robin", "van Persie"], nat: "Netherlands",
    clubs: ["Feyenoord", "Arsenal", "Man Utd", "Fenerbahce", "Feyenoord"],
    loans: [false, false, false, false, false] },
  { key: "ALONSO", display: ["Xabi", "Alonso"], nat: "Spain",
    clubs: ["Real Sociedad", "Eibar", "Real Sociedad", "Liverpool", "Real Madrid", "Bayern Munich"],
    loans: [false, true, false, false, false, false] },
  { key: "HENRY", display: ["Thierry", "Henry"], nat: "France",
    clubs: ["Monaco", "Juventus", "Arsenal", "Barcelona", "New York Red Bulls", "Arsenal"],
    loans: [false, false, false, false, false, true] },
  { key: "SNEIJDER", display: ["Wesley", "Sneijder"], nat: "Netherlands",
    clubs: ["Ajax", "Real Madrid", "Inter", "Galatasaray", "Nice", "Al-Gharafa"],
    loans: [false, false, false, false, false, false] },
  { key: "OZIL", display: ["Mesut", "Özil"], nat: "Germany",
    clubs: ["Schalke 04", "Werder Bremen", "Real Madrid", "Arsenal", "Fenerbahce", "Basaksehir"],
    loans: [false, false, false, false, false, false] },
  { key: "OWEN", display: ["Michael", "Owen"], nat: "England",
    clubs: ["Liverpool", "Real Madrid", "Newcastle", "Man Utd", "Stoke City"],
    loans: [false, false, false, false, false] },

  // ── Wave 2, forged 2026-07-29 ────────────────────────────────────
  // ⚠️ NOT yet spot-checked by Alex. Spec §7.3 requires a 100% manual pass
  // before TRAIL_ANSWER_LOG is frozen — a wrong career order is unfalsifiable
  // to the player and poisons the share loop. These are INERT until then:
  // the log is still empty, so no puzzle draws from them.
  { key: "RONALDO_C", display: ["Cristiano","Ronaldo"], nat: "Portugal",
    clubs: ["Sporting CP","Man Utd","Real Madrid","Juventus","Man Utd","Al-Nassr"],
    loans: [false, false, false, false, false, false] },
  { key: "ROONEY", display: ["Wayne","Rooney"], nat: "England",
    clubs: ["Everton","Man Utd","Everton","DC United","Derby County"],
    loans: [false, false, false, false, false] },
  { key: "ROBBEN", display: ["Arjen","Robben"], nat: "Netherlands",
    clubs: ["Groningen","PSV","Chelsea","Real Madrid","Bayern Munich","Groningen"],
    loans: [false, false, false, false, false, false] },
  { key: "SEEDORF", display: ["Clarence","Seedorf"], nat: "Netherlands",
    clubs: ["Ajax","Sampdoria","Real Madrid","Inter","AC Milan","Botafogo"],
    loans: [false, false, false, false, false, false] },
  { key: "VIEIRA", display: ["Patrick","Vieira"], nat: "France",
    clubs: ["Cannes","AC Milan","Arsenal","Juventus","Inter","Man City"],
    loans: [false, false, false, false, false, false] },
  { key: "MAKELELE", display: ["Claude","Makélélé"], nat: "France",
    clubs: ["Nantes","Marseille","Celta Vigo","Real Madrid","Chelsea","PSG"],
    loans: [false, false, false, false, false, false] },
  { key: "BALLACK", display: ["Michael","Ballack"], nat: "Germany",
    clubs: ["Chemnitzer FC","Kaiserslautern","Bayer Leverkusen","Bayern Munich","Chelsea","Bayer Leverkusen"],
    loans: [false, false, false, false, false, false] },
  { key: "MANE", display: ["Sadio","Mané"], nat: "Senegal",
    clubs: ["Metz","Red Bull Salzburg","Southampton","Liverpool","Bayern Munich","Al-Nassr"],
    loans: [false, false, false, false, false, false] },
  { key: "POGBA", display: ["Paul","Pogba"], nat: "France",
    clubs: ["Man Utd","Juventus","Man Utd","Juventus","Monaco"],
    loans: [false, false, false, false, false] },
  { key: "FABREGAS", display: ["Cesc","Fàbregas"], nat: "Spain",
    clubs: ["Arsenal","Barcelona","Chelsea","Monaco","Como"],
    loans: [false, false, false, false, false] },
  { key: "COLE_A", display: ["Ashley","Cole"], nat: "England",
    clubs: ["Arsenal","Crystal Palace","Chelsea","Roma","LA Galaxy","Derby County"],
    loans: [false, true, false, false, false, false] },
  { key: "BUFFON", display: ["Gianluigi","Buffon"], nat: "Italy",
    clubs: ["Parma","Juventus","PSG","Juventus","Parma"],
    loans: [false, false, false, false, false] },
  { key: "RAMOS", display: ["Sergio","Ramos"], nat: "Spain",
    clubs: ["Sevilla","Real Madrid","PSG","Sevilla","Monterrey"],
    loans: [false, false, false, false, false] },
  { key: "CECH", display: ["Petr","Čech"], nat: "Czech Republic",
    clubs: ["Chmel Blsany","Sparta Prague","Rennes","Chelsea","Arsenal"],
    loans: [false, false, false, false, false] },
  { key: "DUFF", display: ["Damien","Duff"], nat: "Ireland",
    clubs: ["Blackburn","Chelsea","Newcastle","Fulham","Melbourne City","Shamrock Rovers"],
    loans: [false, false, false, false, false, false] },
  { key: "GOTZE", display: ["Mario","Götze"], nat: "Germany",
    clubs: ["Dortmund","Bayern Munich","Dortmund","PSV","Eintracht Frankfurt"],
    loans: [false, false, false, false, false] },
  { key: "KOMPANY", display: ["Vincent","Kompany"], nat: "Belgium",
    clubs: ["Anderlecht","Hamburg","Man City","Anderlecht"],
    loans: [false, false, false, false] },
  { key: "FIGO", display: ["Luis","Figo"], nat: "Portugal",
    clubs: ["Sporting CP","Barcelona","Real Madrid","Inter"],
    loans: [false, false, false, false] },
  { key: "KROOS", display: ["Toni","Kroos"], nat: "Germany",
    clubs: ["Bayern Munich","Bayer Leverkusen","Real Madrid"],
    loans: [false, true, false] },
  { key: "NEYMAR", display: ["Neymar","Júnior"], nat: "Brazil",
    clubs: ["Santos","Barcelona","PSG","Al-Hilal","Santos"],
    loans: [false, false, false, false, false] },
  { key: "AGUERO", display: ["Sergio","Agüero"], nat: "Argentina",
    clubs: ["Independiente","Atletico Madrid","Man City","Barcelona"],
    loans: [false, false, false, false] },
  { key: "ISCO", display: ["Isco","Alarcón"], nat: "Spain",
    clubs: ["Valencia","Malaga","Real Madrid","Sevilla","Real Betis"],
    loans: [false, false, false, false, false] },
  { key: "VERTONGHEN", display: ["Jan","Vertonghen"], nat: "Belgium",
    clubs: ["Ajax","RKC Waalwijk","Tottenham","Benfica","Anderlecht"],
    loans: [false, true, false, false, false] },
  { key: "KANTE", display: ["N'Golo","Kanté"], nat: "France",
    clubs: ["Boulogne","Caen","Leicester","Chelsea","Al-Ittihad","Fenerbahce"],
    loans: [false, false, false, false, false, false] },
  { key: "ALDERWEIRELD", display: ["Toby","Alderweireld"], nat: "Belgium",
    clubs: ["Ajax","Atletico Madrid","Southampton","Tottenham","Al-Duhail","Antwerp"],
    loans: [false, false, true, false, false, false] },
  { key: "JOAQUIN", display: ["Joaquín","Sánchez"], nat: "Spain",
    clubs: ["Real Betis","Valencia","Malaga","Fiorentina","Real Betis"],
    loans: [false, false, false, false, false] },
  { key: "KLOSE", display: ["Miroslav","Klose"], nat: "Germany",
    clubs: ["Homburg","Kaiserslautern","Werder Bremen","Bayern Munich","Lazio"],
    loans: [false, false, false, false, false] },
  { key: "MATUIDI", display: ["Blaise","Matuidi"], nat: "France",
    clubs: ["Troyes","Saint-Etienne","PSG","Juventus","Inter Miami"],
    loans: [false, false, false, false, false] },
  { key: "FLAMINI", display: ["Mathieu","Flamini"], nat: "France",
    clubs: ["Marseille","Arsenal","AC Milan","Arsenal","Crystal Palace","Getafe"],
    loans: [false, false, false, false, false, false] },
  { key: "GILBERTO_SILVA", display: ["Gilberto","Silva"], nat: "Brazil",
    clubs: ["America Mineiro","Atletico Mineiro","Arsenal","Panathinaikos","Gremio","Atletico Mineiro"],
    loans: [false, false, false, false, false, false] },

  // ── Wave M, forged 2026-07-30 ────────────────────────────────────
  // ⚠️ INERT. Added to the roster but NOT written into TRAIL_ANSWER_LOG, so no
  // puzzle draws from them. Per the spec header, a career row needs a 100%
  // human spot-check before it can be scheduled — a wrong order is
  // unfalsifiable to the player. Alex: check these seven, then I extend the log.
  //
  // WHY MORE CAREERS AT ALL, given the log already covers 380 days: 38 players
  // over 380 days means every answer recurs roughly ONCE A MONTH. For a daily
  // game that is very noticeable. Recurrence, not runway, is the problem.
  //
  // Each row was web-verified before landing. FIVE candidates were generated
  // and then REJECTED rather than shipped on a maybe:
  //   Hummels, Di María — recent moves I could not confirm (Roma / a Rosario
  //     Central return would change the final rung).
  //   Mahrez — Al-Ahli terminated his contract, so the last rung is unstable.
  //   Ibrahimović, Drogba — genuine careers, but 9-10 senior clubs. The 6-rung
  //     max is a locked editorial rule and truncating a career is not allowed.
  { key: "VAN_DIJK", display: ["Virgil","van Dijk"], nat: "Netherlands",
    clubs: ["Groningen","Celtic","Southampton","Liverpool"],
    loans: [false, false, false, false] },
  { key: "COURTOIS", display: ["Thibaut","Courtois"], nat: "Belgium",
    // ⚠️ CORRECTED 2026-08-03. This used to open Genk -> Chelsea -> Atletico,
    // on the reasoning that he signed for Chelsea in 2011 and was loaned out
    // immediately, so "the return spell is its own rung". That gets the game
    // backwards: he never played a single senior match for Chelsea before
    // 2014, so the first Chelsea rung showed a club he had never turned out
    // for. In a puzzle where the clubs ARE the clue, that is a false clue.
    //
    // The rungs are now the clubs he actually played for, in order. Note this
    // also settles the rule ambiguity that De Bruyne exposed: coming back from
    // a loan is NOT a "return" under the returns-are-rungs rule, because the
    // parent contract never ended. Both players had one continuous Chelsea
    // deal with a loan inside it; both now list Chelsea once. De Bruyne
    // needed no change, and does not need a 7th rung.
    clubs: ["Genk","Atletico Madrid","Chelsea","Real Madrid"],
    loans: [false, true, false, false] },
  { key: "GRIEZMANN", display: ["Antoine","Griezmann"], nat: "France",
    // ⚠️ Orlando City added 2026-08-12 by scripts/verify-trail-careers.mjs, which
    // caught the move FOUR DAYS before Trail #14 would have shipped the old
    // four-club path as today's puzzle. Confirmed against Wikidata P54 (start
    // 2026) as well as the infobox — one source is not enough for a claim about
    // a living player, and Wikipedia vandalism has reached our binaries before.
    clubs: ["Real Sociedad","Atletico Madrid","Barcelona","Atletico Madrid","Orlando City"],
    loans: [false, false, false, false, false] },
  { key: "DE_BRUYNE", display: ["Kevin","De Bruyne"], nat: "Belgium",
    clubs: ["Genk","Chelsea","Werder Bremen","Wolfsburg","Man City","Napoli"],
    loans: [false, false, true, false, false, false] },
  // ⚠️ Was the same human as HEUNGMIN, stored twice under two keys — and this
  // one had the name REVERSED, which broke every SON day outright (reported
  // live on day 20, 2026-08-23). `mysteryPool.json` — the pool the in-game
  // autocomplete offers from — stores the canonical "Son Heung-min", so
  // tapping the app's own first suggestion spent an attempt and revealed a
  // free club. Both entries now carry the same Korean name order.
  //
  // RESOLVED 2026-09-28: HEUNGMIN's four log days (#85/#161/#285/#339, none
  // yet served) now go to PARK, a 102nd distinct, verified career — so Son no
  // longer gets 8 of 408 days (twice inside a fortnight at #146/#161).
  { key: "SON", display: ["Son","Heung-min"], nat: "South Korea",
    clubs: ["Hamburg","Bayer Leverkusen","Tottenham","LAFC"],
    loans: [false, false, false, false] },
  // MARCELO was forged and then REJECTED here: a mononym cannot satisfy the
  // 2-part `display` contract, and his legal surname (Vieira) already belongs
  // to Patrick Vieira in this roster — two puzzles would share an answer.
  { key: "LEWANDOWSKI", display: ["Robert","Lewandowski"], nat: "Poland",
    // Znicz Pruszkow opens the real career but is third-tier Polish football —
    // dropped for the same editorial reason Modric's loan openers were.
    // ⚠️ Chicago Fire added 2026-08-12 by scripts/verify-trail-careers.mjs,
    // confirmed against Wikidata P54 (start 2026) as well as the infobox. With
    // the two trimmed Polish clubs the full career is seven rungs, over the
    // six-rung cap — this stays at five because the trim is a deliberate
    // editorial subset made in wave M, not a truncation of the recent end.
    clubs: ["Lech Poznan","Dortmund","Bayern Munich","Barcelona","Chicago Fire"],
    loans: [false, false, false, false, false] },
];

// Frozen answer log: TRAIL_ANSWER_LOG[n] is the player `key` for day index
// TRAIL_ANCHOR_DAY + n. Generated once at ship time (clone of
// WORDLE_ANSWER_LOG) so the schedule never reshuffles under players.
export const TRAIL_ANSWER_LOG = [
  // RE-PLANNED 2026-08-12 for wave N (102 -> 208 careers).
  // ⚠️ Entries 1..87 are copied through UNCHANGED — those puzzles have been
  // played and their grids shared. Everything after is re-planned, which is
  // safe precisely because nobody has seen it. Deterministic LCG, seed 20260812.
  // Minimum gap between repeats: 121 days.
  "TORRES",
  "GILBERTO_SILVA",
  "RONALDO_C",
  "RAMOS",
  "MATUIDI",
  "ROONEY",
  "CECH",
  "HENRY",
  "SNEIJDER",
  "FLAMINI",
  "ERIKSEN",
  "VALVERDE",
  "CAN",
  "GRIEZMANN",
  "FERNANDES",
  "AGUERO",
  "VAN_PERSIE",
  "KOVAI",
  "KLOSE",
  "ALONSO",
  "SON",
  "BALLACK",
  "MINAMINO",
  "WERNER",
  "BENZEMA",
  "SAKAI",
  "MAKELELE",
  "KONNO",
  "AFELLAY",
  "UCHIDA",
  "RDIGER",
  "VERRATTI",
  "TORRES_FER",
  "XHAKA",
  "JONG",
  "POGBA",
  "MANE",
  "OZIL",
  "ROBBEN",
  "MESSI",
  "ALVAREZ",
  "SHIBASAKI",
  "LEWANDOWSKI",
  "DUFF",
  "BECKER",
  "LLORIS",
  "GOTZE",
  "OSAKO",
  "OLISE",
  "GAKPO",
  "PAVARD",
  "FIGO",
  "COLE_A",
  "DEPAY",
  "BUFFON",
  "HAVERTZ",
  "NEYMAR",
  "MAGUIRE",
  "FIRMINO",
  "VERTONGHEN",
  "VZQUEZ",
  "MODRI",
  "KOMPANY",
  "DE_BRUYNE",
  "SZCZSNY",
  "FABREGAS",
  "REUS",
  "MUTO",
  "VAN_DIJK",
  "OWEN",
  "STEGEN",
  "ALDERWEIRELD",
  "VIEIRA",
  "GEA",
  "OSIMHEN",
  "SAKAI_HIR",
  "FATI",
  "MARTIAL",
  "BELLINGHAM",
  "STONES",
  "ISCO",
  "HAKIMI",
  "SEEDORF",
  "KANE",
  "PARK",
  "SAN",
  "DONNARUMMA",   // ← puzzles above are PLAYED; never touch them
  "ALCANTARA",
  "BREITNER",
  "OLMO",
  "VALDES",
  "VERMAELEN",
  "MARCELO",
  "DYBALA",
  "NESTA",
  "SILVA_DAV",
  "DEMBL",
  "GOMEZ",
  "KANTE",
  "SAGNA",
  "RIQUELME",
  "RIJKAARD",
  "STOJKOVIC",
  "BALE",
  "HERNANDEZ",
  "BARRY",
  "SRNA",
  "BARTHEZ",
  "CALHANOGLU",
  "WILSHERE",
  "CHIESA",
  "BONIEK",
  "ZIDANE",
  "JOAQUIN",
  "DRAXLER",
  "GNDOAN",
  "ARSHAVIN",
  "HOWEDES",
  "MEIRELES",
  "ZANETTI",
  "PLATINI",
  "LEHMANN",
  "ALBIOL",
  "HAZARD",
  "FONTAINE",
  "ROBERTO",
  "JESUS",
  "PATRICIO",
  "STEFANO",
  "BECKHAM",
  "MUSTAFI",
  "BECKENBAUER",
  "BRAVO",
  "SHEVCHENKO",
  "IVANOVIC",
  "GATTUSO",
  "TERRY",
  "LIZARAZU",
  "TURAN",
  "PIQUE",
  "FERDINAND",
  "RUMMENIGGE",
  "INIESTA",
  "WALCOTT",
  "CORLUKA",
  "KHEDIRA",
  "YOSHIDA",
  "NEDVED",
  "VIDIC",
  "ISAK",
  "ZOFF",
  "GNABRY",
  "PULISIC",
  "FELLAINI",
  "TCHOUAMENI",
  "SOLSKJAER",
  "DIER",
  "CHARLTON",
  "AZPILICUETA",
  "SILVA",
  "JOTA",
  "ALABA",
  "BRONCKHORST",
  "SMALLING",
  "MERTESACKER",
  "CARRICK",
  "HUMMELS",
  "FERNANDEZ",
  "MARCHISIO",
  "VARDY",
  "BLASZCZYKOWSKI",
  "LEAO",
  "SHEARER",
  "MBAPP",
  "NAGATOMO",
  "VLAHOVIC",
  "ARBELOA",
  "NATALE",
  "SCHILLACI",
  "KEANE",
  "BERGKAMP",
  "COMAN",
  "MULLER",
  "ORIGI",
  "KROOS",
  "KEEGAN",
  "VARANE",
  "SAR",
  "ROSICKY",
  "SCHWEINSTEIGER",
  "MOTTA",
  "DESAILLY",
  "LINEKER",
  "GALLAS",
  "VOLLER",
  "BOMMEL",
  "COURTOIS",
  "KOUNDE",
  "MILITO",
  "PIERO",
  "ENDO",
  "UMTITI",
  "COSTA",
  "RABIOT",
  "KUYT",
  "NAVAS",
  "THURAM",
  "TOURE",
  "BALLACK",
  "SON",
  "TORRES_FER",
  "AFELLAY",
  "MATUIDI",
  "KONNO",
  "SAKAI_HIR",
  "STEGEN",
  "DONNARUMMA",
  "SNEIJDER",
  "UCHIDA",
  "WERNER",
  "SAKAI",
  "MODRI",
  "JONG",
  "CECH",
  "VERRATTI",
  "ALCANTARA",
  "REUS",
  "ROONEY",
  "CAN",
  "FIGO",
  "VAN_PERSIE",
  "BREITNER",
  "KOVAI",
  "HAVERTZ",
  "STOJKOVIC",
  "OWEN",
  "KLOSE",
  "ROBBEN",
  "BELLINGHAM",
  "MEIRELES",
  "SAN",
  "VALDES",
  "RIQUELME",
  "KOMPANY",
  "MUTO",
  "GOMEZ",
  "KANE",
  "ROBERTO",
  "HOWEDES",
  "KANTE",
  "RDIGER",
  "ZANETTI",
  "DYBALA",
  "BALE",
  "STONES",
  "RAMOS",
  "MARCELO",
  "FIRMINO",
  "RIJKAARD",
  "HAKIMI",
  "MAKELELE",
  "BRAVO",
  "OLISE",
  "BECKHAM",
  "ALBIOL",
  "PATRICIO",
  "VZQUEZ",
  "LEHMANN",
  "ALONSO",
  "PAVARD",
  "SHEVCHENKO",
  "NEYMAR",
  "COLE_A",
  "GATTUSO",
  "DE_BRUYNE",
  "CALHANOGLU",
  "FLAMINI",
  "TURAN",
  "OSAKO",
  "ISCO",
  "AZPILICUETA",
  "NEDVED",
  "MUSTAFI",
  "ISAK",
  "ARSHAVIN",
  "GNDOAN",
  "PLATINI",
  "TORRES",
  "VIDIC",
  "VALVERDE",
  "RUMMENIGGE",
  "AGUERO",
  "OSIMHEN",
  "INIESTA",
  "PIQUE",
  "PARK",
  "SMALLING",
  "BARTHEZ",
  "SRNA",
  "IVANOVIC",
  "STEFANO",
  "ALVAREZ",
  "OLMO",
  "GOTZE",
  "BECKENBAUER",
  "LLORIS",
  "VLAHOVIC",
  "SOLSKJAER",
  "OZIL",
  "COMAN",
  "JESUS",
  "BLASZCZYKOWSKI",
  "SHIBASAKI",
  "PULISIC",
  "KROOS",
  "MANE",
  "HAZARD",
  "VIEIRA",
  "HERNANDEZ",
  "BECKER",
  "MARTIAL",
  "GNABRY",
  "UMTITI",
  "ZOFF",
  "BRONCKHORST",
  "KUYT",
  "JOAQUIN",
  "VAN_DIJK",
  "FELLAINI",
  "DEPAY",
  "BOMMEL",
  "FERNANDES",
  "CORLUKA",
  "FONTAINE",
  "RONALDO_C",
  "CARRICK",
  "MESSI",
  "DRAXLER",
  "MERTESACKER",
  "MILITO",
  "GAKPO",
  "BENZEMA",
  "FATI",
  "BONIEK",
  "ALDERWEIRELD",
  "LIZARAZU",
  "ZIDANE",
  "RABIOT",
  "BARRY",
  "HENRY",
  "SCHILLACI",
  "CHARLTON",
  "LEWANDOWSKI",
  "KEANE",
  "VARDY",
  "FABREGAS",
  "MINAMINO",
  "NAVAS",
  "GALLAS",
  "HUMMELS",
  "GILBERTO_SILVA",
  "FERDINAND",
  "COSTA",
  "DESAILLY",
  "SAR",
  "FERNANDEZ",
  "SILVA",
  "WALCOTT",
  "SCHWEINSTEIGER",
  "BUFFON",
  "XHAKA",
  "PIERO",
  "DUFF",
  "MBAPP",
  "ARBELOA",
  "SAGNA",
  "VOLLER",
  "KHEDIRA",
  "TCHOUAMENI",
  "DIER",
  "KEEGAN",
  "SEEDORF",
  "LEAO",
  "ORIGI",
  "LINEKER",
  "JOTA",
  "YOSHIDA",
  "COURTOIS",
  "GRIEZMANN",
  "DEMBL",
  "SILVA_DAV",
  "ERIKSEN",
  "SHEARER",
  "ENDO",
  "MARCHISIO",
  "KOUNDE",
  "MULLER",
  "GEA",
  "NAGATOMO",
  "CHIESA",
  "SZCZSNY",
  "BERGKAMP",
  "MAGUIRE",
  "POGBA",
  "MOTTA",
  "ALABA",
  "VERTONGHEN",
  "VERMAELEN",
  "TERRY",
  "ROSICKY",
  "TOURE",
  "NATALE",
  "WILSHERE",
  "VARANE",
  "THURAM",
  "NESTA",
];

export function getTrailPlayerByKey(key, players = TRAIL_PLAYERS) {
  return players.find((p) => p && p.key === key) || null;
}

export function getTrailAnswerForDayIndex(dayIndex, log = TRAIL_ANSWER_LOG, players = TRAIL_PLAYERS) {
  const n = dayIndex - TRAIL_ANCHOR_DAY;
  if (n < 0 || !log.length) return null;
  const key = log[n % log.length]; // wrap after the log runs out rather than going dark
  return getTrailPlayerByKey(key, players);
}

export function getTrailAnswer(date = new Date(), log = TRAIL_ANSWER_LOG, players = TRAIL_PLAYERS) {
  return getTrailAnswerForDayIndex(getTrailDayIndex(date), log, players);
}

// ── Answer matching (spec v2) ────────────────────────────────────────────────
//
// The guess is a surname typed by hand, so matching has to survive accents,
// case, punctuation and spacing. NFD + combining-mark strip turns Čech into
// cech, Özil into ozil, Agüero into aguero — one rule instead of a lookup.
//
// Accepted forms are DERIVED from `display` (surname, and the full name), so
// only genuine exceptions are listed below. Two of them are not stylistic —
// they are unwinnable without an alias: Neymar's surname in the data is
// "Júnior" and Isco's is "Alarcón". Nobody on earth types those.
export const TRAIL_ALIASES = {
  NEYMAR:         ["Neymar"],
  ISCO:           ["Isco"],
  JOAQUIN:        ["Joaquin"],
  VAN_PERSIE:     ["Persie"],
  RONALDO_C:      ["Cristiano", "CR7"],
  GILBERTO_SILVA: ["Gilberto", "Gilberto Silva"],
  GOTZE:          ["Goetze"],   // common German transliteration of ö
  OZIL:           ["Oezil"],

  // ⚠️ EAST ASIAN NAME ORDER. acceptedNamesFor() derives the surname as the
  // LAST word, which holds for Western names and is exactly backwards here:
  // stored in native order, "Son Heung-min" has the family name FIRST, so the
  // derived forms are "Heung-min" (the given name) and the full name — and
  // "Son", the one thing every commentator actually says, was refused on all
  // eight of his scheduled days. Alias rather than reordering the display,
  // because the display order is correct and the derivation is what does not
  // generalise. Western order is aliased too; people type both. Park Ji-sung
  // (stored "Park Ji-sung") has the identical shape.
  SON:            ["Son", "Heung-min Son"],
  PARK:           ["Park", "Ji-sung Park"],
};

// Revealed as a hint after the third miss. Nationality already lives on the
// career row; position did not, and a nationality on its own is a weak rescue
// ("France" covers half the roster).
export const TRAIL_POSITIONS = {
  // ── WAVE N positions, from the lineup pool's own position field. Broad
  // (Goalkeeper/Defender/Midfielder/Forward) rather than the specific labels
  // some older entries carry: a correct broad hint beats a guessed precise one.
  "ZIDANE": "Midfielder",
  "BECKHAM": "Midfielder",
  "BECKENBAUER": "Midfielder",
  "INIESTA": "Midfielder",
  "PLATINI": "Midfielder",
  "HAZARD": "Forward",
  "PIQUE": "Defender",
  "MULLER": "Midfielder",
  "STEFANO": "Midfielder",
  "LINEKER": "Midfielder",
  "SHEVCHENKO": "Midfielder",
  "PIERO": "Midfielder",
  "CHARLTON": "Midfielder",
  "MARCELO": "Midfielder",
  "TERRY": "Defender",
  "VARANE": "Defender",
  "VIDIC": "Defender",
  "BERGKAMP": "Midfielder",
  "SAR": "Midfielder",
  "SCHWEINSTEIGER": "Midfielder",
  "SILVA_DAV": "Forward",
  "KHEDIRA": "Midfielder",
  "HUMMELS": "Defender",
  "SHEARER": "Midfielder",
  "VALDES": "Goalkeeper",
  "THURAM": "Midfielder",
  "FERDINAND": "Midfielder",
  "GOMEZ": "Forward",
  "KEEGAN": "Midfielder",
  "ARSHAVIN": "Forward",
  "ZANETTI": "Midfielder",
  "JOTA": "Forward",
  "TURAN": "Forward",
  "ARBELOA": "Defender",
  "RIJKAARD": "Midfielder",
  "CARRICK": "Midfielder",
  "ZOFF": "Midfielder",
  "ALBIOL": "Defender",
  "UMTITI": "Defender",
  "KUYT": "Forward",
  "SCHILLACI": "Midfielder",
  "WALCOTT": "Forward",
  "ALABA": "Defender",
  "VARDY": "Forward",
  "MERTESACKER": "Defender",
  "AZPILICUETA": "Defender",
  "LEHMANN": "Midfielder",
  "SOLSKJAER": "Midfielder",
  "NAVAS": "Defender",
  "GATTUSO": "Midfielder",
  "RUMMENIGGE": "Midfielder",
  "NEDVED": "Midfielder",
  "IVANOVIC": "Defender",
  "ENDO": "Midfielder",
  "ALCANTARA": "Midfielder",
  "ORIGI": "Forward",
  "BLASZCZYKOWSKI": "Forward",
  "VERMAELEN": "Defender",
  "MUSTAFI": "Defender",
  "SAGNA": "Defender",
  "KEANE": "Midfielder",
  "DESAILLY": "Midfielder",
  "BREITNER": "Midfielder",
  "BARTHEZ": "Midfielder",
  "MILITO": "Midfielder",
  "FELLAINI": "Midfielder",
  "BRAVO": "Goalkeeper",
  "WILSHERE": "Midfielder",
  "MOTTA": "Midfielder",
  "FONTAINE": "Midfielder",
  "TOURE": "Defender",
  "NATALE": "Midfielder",
  "NESTA": "Midfielder",
  "SMALLING": "Defender",
  "VOLLER": "Midfielder",
  "SRNA": "Defender",
  "MARCHISIO": "Midfielder",
  "ROSICKY": "Midfielder",
  "RIQUELME": "Midfielder",
  "BOMMEL": "Midfielder",
  "BRONCKHORST": "Midfielder",
  "STOJKOVIC": "Midfielder",
  "PATRICIO": "Goalkeeper",
  "CORLUKA": "Defender",
  "HOWEDES": "Defender",
  "MEIRELES": "Midfielder",
  "LIZARAZU": "Midfielder",
  "COMAN": "Forward",
  "OLMO": "Midfielder",
  "JESUS": "Forward",
  "PULISIC": "Midfielder",
  "CHIESA": "Forward",
  "FERNANDEZ": "Midfielder",
  "LEAO": "Forward",
  "COSTA": "Midfielder",
  "BARRY": "Midfielder",
  "BONIEK": "Midfielder",
  "GNABRY": "Forward",
  "ROBERTO": "Midfielder",
  "CALHANOGLU": "Midfielder",
  "DIER": "Defender",
  "GALLAS": "Midfielder",
  "HERNANDEZ": "Defender",
  "VLAHOVIC": "Forward",
  "TCHOUAMENI": "Midfielder",
  "KOUNDE": "Defender",
  // ── WAVE N positions, from the lineup pool's own position field. Broad
  // (Goalkeeper/Defender/Midfielder/Forward) rather than the specific labels
  // some older entries carry: a correct broad hint beats a guessed precise one.
  "MESSI": "Forward",
  "MBAPP": "Forward",
  "MODRI": "Midfielder",
  "BENZEMA": "Forward",
  "KANE": "Forward",
  "DEMBL": "Forward",
  "LLORIS": "Goalkeeper",
  "GEA": "Goalkeeper",
  "DYBALA": "Forward",
  "REUS": "Midfielder",
  "PARK": "Midfielder",
  "BELLINGHAM": "Midfielder",
  "BECKER": "Goalkeeper",
  "HAKIMI": "Defender",
  "FIRMINO": "Forward",
  "SZCZSNY": "Goalkeeper",
  "MAGUIRE": "Defender",
  "STEGEN": "Goalkeeper",
  "ERIKSEN": "Midfielder",
  "DEPAY": "Forward",
  "NAGATOMO": "Defender",
  "FERNANDES": "Midfielder",
  "DRAXLER": "Midfielder",
  "MINAMINO": "Midfielder",
  "RDIGER": "Defender",
  "VALVERDE": "Midfielder",
  "GNDOAN": "Midfielder",
  "HAVERTZ": "Midfielder",
  "TORRES_FER": "Forward",
  "OSAKO": "Forward",
  "FATI": "Forward",
  "DONNARUMMA": "Goalkeeper",
  "KOVAI": "Midfielder",
  "YOSHIDA": "Defender",
  "UCHIDA": "Defender",
  "SILVA": "Midfielder",
  "SAN": "Forward",
  "WERNER": "Forward",
  "PAVARD": "Defender",
  "SHIBASAKI": "Midfielder",
  "SAKAI": "Defender",
  "ALVAREZ": "Forward",
  "VZQUEZ": "Midfielder",
  "MUTO": "Forward",
  "GAKPO": "Forward",
  "CAN": "Midfielder",
  "XHAKA": "Midfielder",
  "SAKAI_HIR": "Defender",
  "RABIOT": "Midfielder",
  "JONG": "Midfielder",
  "AFELLAY": "Midfielder",
  "STONES": "Defender",
  "VERRATTI": "Midfielder",
  "OLISE": "Forward",
  "OSIMHEN": "Forward",
  "KONNO": "Defender",
  "ISAK": "Forward",
  "MARTIAL": "Forward",
  TORRES: "Forward", BALE: "Winger", VAN_PERSIE: "Forward", ALONSO: "Midfielder",
  HENRY: "Forward", SNEIJDER: "Midfielder", OZIL: "Midfielder", OWEN: "Forward",
  RONALDO_C: "Forward", ROONEY: "Forward", ROBBEN: "Winger", SEEDORF: "Midfielder",
  VIEIRA: "Midfielder", MAKELELE: "Midfielder", BALLACK: "Midfielder", MANE: "Forward",
  POGBA: "Midfielder", FABREGAS: "Midfielder", COLE_A: "Defender", BUFFON: "Goalkeeper",
  RAMOS: "Defender", CECH: "Goalkeeper", DUFF: "Winger", GOTZE: "Midfielder",
  KOMPANY: "Defender", FIGO: "Winger", KROOS: "Midfielder", NEYMAR: "Forward",
  AGUERO: "Forward", ISCO: "Midfielder", VERTONGHEN: "Defender", KANTE: "Midfielder",
  ALDERWEIRELD: "Defender", JOAQUIN: "Winger", KLOSE: "Forward", MATUIDI: "Midfielder",
  FLAMINI: "Midfielder", GILBERTO_SILVA: "Midfielder",
  // Wave M
  VAN_DIJK: "Defender", COURTOIS: "Goalkeeper", GRIEZMANN: "Forward",
  DE_BRUYNE: "Midfielder", SON: "Forward", LEWANDOWSKI: "Forward",
};

// Letters that are NOT decorated versions of an ascii letter — they are their
// own characters, so NFD does not decompose them and a naive mark-strip DELETES
// them. Measured before this existed: Ødegaard folded to "degaard", Højbjerg to
// "hjbjerg", Błaszczykowski to "baszczykowski", Đorđević to "orevic", Weiß to
// "wei". Every one of those is unwinnable — the player types the obvious plain
// spelling and it cannot match.
//
// Alex, 2026-07-29: "people write names differently you know, some swedish
// names, norwegian names, south american, they all have unique letters and dots
// everywhere so we should be graceful here." Correct, and this is the half that
// gracefulness does not come free.
//
// Note what is NOT here: é č ö ü å ñ ş all DO decompose, so the mark-strip below
// already handles them. Only the non-decomposing ones need spelling out.
// The table itself lives in lib/letterFold.js since 2026-10-09, so the name
// search folds the same letters the grader does.

/** Fold a typed guess to its comparable form: accent-free, lowercase, a-z only. */
export function normaliseGuess(s) {
  return foldLetters(s)
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z]/g, "");
}

// German and Nordic spelling admits TWO correct plain-ascii forms (Muller or
// Mueller, Odegaard or Oedegaard), so a name folds to a SET and a guess matches
// if the sets overlap.

/** Every plain-ascii spelling this string could reasonably be typed as. */
export function normaliseVariants(s) {
  return [...new Set([normaliseGuess(s), normaliseGuess(foldDigraphs(s))].filter(Boolean))];
}

/** Every string that counts as naming this player. */
export function acceptedNamesFor(player) {
  if (!player) return [];
  const [first, last] = player.display || [];
  const out = [];
  if (last) out.push(last);
  if (first && last) out.push(`${first} ${last}`);
  if (first && !last) out.push(first);

  // ⚠️ `display` splits names INCONSISTENTLY, and that inconsistency was
  // rejecting answers the player had plainly got right (reported 2026-08-22:
  // a surname marked wrong while the full name was marked right).
  //
  // The particle sometimes rides with the forename and sometimes with the
  // surname — ["David de","Gea"] but ["Virgil","van Dijk"] — so whichever way
  // a given player is stored, ONE of the two forms a human would actually type
  // was refused:
  //
  //     Kevin De Bruyne        "Bruyne"      rejected
  //     Virgil van Dijk        "Dijk"        rejected
  //     Frenkie de Jong        "de Jong"     rejected
  //     David de Gea           "de Gea"      rejected
  //     Marc-André ter Stegen  "ter Stegen"  rejected
  //
  // So derive the forms from the WHOLE name rather than trusting the split:
  // the bare final word, and the last two words (which covers every
  // particle+surname). Both are additive — nothing previously accepted stops
  // being accepted.
  //
  // Deliberately generous. A Trail guess is limited and the mode is about
  // football knowledge, not about guessing how we happened to store a name.
  // Over-accepting costs a player nothing they did not earn; under-accepting
  // takes an attempt away from someone who KNEW the answer, which is the
  // worst outcome this mode can produce.
  const whole = [first, last].filter(Boolean).join(' ').trim();
  const words = whole ? whole.split(/\s+/) : [];
  if (words.length >= 2) out.push(words[words.length - 1]);
  if (words.length >= 3) out.push(words.slice(-2).join(' '));

  for (const alias of TRAIL_ALIASES[player.key] || []) out.push(alias);
  return [...new Set(out)];
}

export function guessMatchesPlayer(guess, player) {
  const guessForms = normaliseVariants(guess);
  if (!guessForms.length) return false;
  return acceptedNamesFor(player).some((name) =>
    normaliseVariants(name).some((n) => guessForms.includes(n))
  );
}

/**
 * How many clubs are on the ladder after `misses` wrong guesses or skips.
 * Opens at TRAIL_OPENING_CLUBS and grows by one each time, capped at the
 * career length — a 6-rung career runs out of clubs exactly as the player runs
 * out of attempts, so there is no tuning constant to drift.
 */
export const TRAIL_OPENING_CLUBS = 2;
export function cluesShown(misses, careerLength) {
  return Math.min(TRAIL_OPENING_CLUBS + Math.max(0, misses), careerLength);
}

/** The hint unlocks once three guesses are gone. */
export function hintFor(player, misses) {
  if (!player || misses < 3) return null;
  const pos = TRAIL_POSITIONS[player.key];
  return [player.nat, pos].filter(Boolean).join(" · ") || null;
}

/**
 * A day's stored Trail state, normalised to { status, used } — the same shape
 * Footle's history uses, so screens can treat all the daily modes alike.
 * Returns null when the day was never opened.
 *
 * Exported because THREE screens now need it (the Trail itself, the Daily tab,
 * the Home daily zone) and each hand-rolled read of `biq_trail_<ymd>` is a
 * chance for them to disagree about what "played" means.
 */
export function loadTrailDay(date = new Date()) {
  try {
    const raw = localStorage.getItem(`biq_trail_${dateToYMD(date)}`);
    if (!raw) return null;
    const p = JSON.parse(raw);
    return { status: p?.status || null, used: Array.isArray(p?.attempts) ? p.attempts.length : 0 };
  } catch { return null; }
}

// ── Streak ────────────────────────────────────────────────────────────────────
// Clone of computeFootleStreak: walk backwards over biq_trail_<ymd> localStorage
// entries while they exist and are wins. Storage writes live in the screen.
export function computeTrailStreak(today) {
  let streak = 0;
  const cursor = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  for (let i = 0; i < 366; i++) {
    try {
      const raw = localStorage.getItem(`biq_trail_${dateToYMD(cursor)}`);
      if (!raw) break;
      const p = JSON.parse(raw);
      if (p?.status !== "won" || p?.arc) break; // arc = archive back-fill, not streak fuel
    } catch { break; }
    streak++;
    cursor.setDate(cursor.getDate() - 1);
  }
  return streak;
}

// ── Share text (spec v2) ─────────────────────────────────────────────────────
// Spoiler-free by construction: it names neither the player nor a single club,
// only how many rungs it took. That is a stronger guarantee than v1's grid,
// which leaked the SHAPE of the career (how many clubs, how scrambled).
export function buildTrailShareText({ number, won, clubsUsed, streak } = {}) {
  const head = `⚽ Ball IQ · Transfer Trail${number > 0 ? ` #${number}` : ""}`;
  const line = won
    ? `Got it on ${clubsUsed} club${clubsUsed === 1 ? "" : "s"} ${"⚽".repeat(Math.min(clubsUsed, 6))}`
    : `Didn't get it — X/${TRAIL_MAX_ATTEMPTS}`;
  const streakLine = won && streak > 0 ? `\n🔥 ${streak}-day Trail streak` : "";
  return `${head}\n${line}${streakLine}\n\nballiq.app/trail`;
}

