// GENERATED by scripts/gen-footle-practice.mjs — do not edit.
// A PAST Footle puzzle (never today's) + the app's own grader, emitted via
// toString() so duplicate-letter scoring cannot drift from src/lib/wordle.js.

export const FP_ANSWER = 'EDERSON';
export const FP_FULL = 'Ederson';
export const FP_NUMBER = 86;

export const gradeGuess = function gradeWordleGuess(guess, answer) {
  const n = answer.length;
  const result = new Array(n).fill("grey");
  const remaining = [];
  for (let i = 0; i < n; i++) {
    if (guess[i] === answer[i]) result[i] = "green";
    else remaining.push(answer[i]);
  }
  for (let i = 0; i < n; i++) {
    if (result[i] === "green") continue;
    const idx = remaining.indexOf(guess[i]);
    if (idx !== -1) {
      result[i] = "yellow";
      remaining.splice(idx, 1);
    }
  }
  return result;
};
