// GENERATED by scripts/build-fun-facts.mjs — do not hand-edit.
// Every fact is a VERIFIED explanation from the question bank (forge:
// generate -> examiner -> skeptic -> adversarial fact-check). Facts that
// could not stand alone were dropped, never rewritten.
export const FUN_FACTS = [
 {
  "theme": "Records & firsts",
  "facts": [
   {
    "id": "q_ad8d29",
    "text": "After finishing fourth in La Liga, Betis played their first Champions League campaign in 2005-06.",
    "cat": "ChampionsLeague",
    "club": "Real Betis"
   },
   {
    "id": "q_a25672",
    "text": "VAR was introduced for 2019-20, two years after it was first trialled in the FA Cup and League Cup.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_30ff3a",
    "text": "Higuaín joined Napoli from Real Madrid in 2013 before his record move to Juventus three years later.",
    "cat": "Transfers",
    "club": "Napoli"
   },
   {
    "id": "q_577c4b",
    "text": "Ancelotti won the 2012-13 title, PSG's first league crown since 1994, before leaving for Real Madrid.",
    "cat": "Managers",
    "club": "Paris Saint-Germain"
   },
   {
    "id": "q_dd868e",
    "text": "Liverpool won the 1965 final 2-1 after extra time; it was Leeds' first appearance in an FA Cup final.",
    "cat": "History",
    "club": "Leeds United"
   },
   {
    "id": "q_e0d524",
    "text": "Emre Belözoğlu joined Başakşehir in 2019 and captained them to their first championship before retiring.",
    "cat": "SuperLig",
    "club": ""
   },
   {
    "id": "q_36bc04",
    "text": "Bergkamp joined Arsenal from Inter in 1995 for a club record fee, after a difficult two years in Serie A.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_89d488",
    "text": "Record scorer Ally McCoist stayed on to lead Rangers through the lower divisions after the 2012 demotion.",
    "cat": "Managers",
    "club": "Rangers"
   },
   {
    "id": "q_c7b147",
    "text": "Arne Slot won the league in his first season in charge after replacing Jurgen Klopp in the summer of 2024.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_4b3f68",
    "text": "Ronaldo left for Inter Milan in 1997 for a then world-record fee after one prolific campaign in Catalonia.",
    "cat": "Transfers",
    "club": "Barcelona"
   },
   {
    "id": "q_127455",
    "text": "Took over from Billy Davies in November 2007 but couldn't reverse the slide that ended in record-low points.",
    "cat": "Managers",
    "club": ""
   },
   {
    "id": "q_365e37",
    "text": "Famously nicknamed 'The Special One' at his first Chelsea press conference after arriving from Porto in 2004.",
    "cat": "Managers",
    "club": ""
   },
   {
    "id": "q_1ae6d6",
    "text": "John Charles starred for Leeds before a record 1957 move to Italy, and is regarded among the club's greatest.",
    "cat": "Legends",
    "club": "Leeds United"
   },
   {
    "id": "q_8d17c3",
    "text": "Betis reached the 2025 UEFA Conference League final, their first European final, but lost to an English side.",
    "cat": "ChampionsLeague",
    "club": "Real Betis"
   },
   {
    "id": "q_09d08c",
    "text": "Madrid claimed the 1931-32 championship, their first, a few seasons after the Spanish league launched in 1929.",
    "cat": "Records",
    "club": "Real Madrid"
   },
   {
    "id": "q_11d6b0",
    "text": "'I Bianconeri' means 'the black-and-whites', after the iconic black-and-white striped kit first adopted in 1903.",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_a37107",
    "text": "Guardiola won the Tercera División title with Barcelona B in 2007-08 before taking over the Barcelona first team.",
    "cat": "Managers",
    "club": ""
   },
   {
    "id": "q_2dfc82",
    "text": "Haaland's 36 goals in 2022-23 were not just the Golden Boot but a new single-season record for a 38-game campaign.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_27b9f4",
    "text": "Klopp's young team amassed 81 points in 2011-12, a Bundesliga record at the time before Bayern later surpassed it.",
    "cat": "Bundesliga",
    "club": "Borussia Dortmund"
   },
   {
    "id": "q_48df73",
    "text": "Neymar scored twice on 12 June 2014 after Marcelo had turned into his own net inside the first quarter of an hour.",
    "cat": "History",
    "club": "Corinthians"
   }
  ]
 },
 {
  "theme": "World Cup & internationals",
  "facts": [
   {
    "id": "q_db57b8",
    "text": "Porto's 2004 win was the last Intercontinental Cup before FIFA folded it into the Club World Cup.",
    "cat": "Primeira",
    "club": "Porto"
   },
   {
    "id": "q_c31705",
    "text": "Hakan Şükür struck after 10.8 seconds against South Korea in the 2002 World Cup third-place match, a record that still stands.",
    "cat": "Records",
    "club": "Galatasaray"
   },
   {
    "id": "q_40d668",
    "text": "Kylian Mbappé won the first-ever Kopa Trophy in 2018 after his breakout World Cup; the award honours the world's best player under 21.",
    "cat": "Records",
    "club": ""
   },
   {
    "id": "q_601d40",
    "text": "France hosted Euro 2016 but lost the final 1-0 to Portugal at the Stade de France; it was the tournament's first edition with 24 teams.",
    "cat": "Euros",
    "club": ""
   },
   {
    "id": "q_8291b6",
    "text": "Two years after their famous Euro 2016 quarter-final run. Curaçao (pop. ~156,000) took the smallest-nation record by qualifying for 2026.",
    "cat": "WorldCup",
    "club": ""
   },
   {
    "id": "q_0cfc6c",
    "text": "Michel Platini captained and dominated Euro 1984, scoring a record nine goals in five games before France beat Spain 2-0 in the Paris final.",
    "cat": "Euros",
    "club": ""
   },
   {
    "id": "q_dda8e7",
    "text": "Chelsea triggered Fernandez's Benfica release clause in January 2023, a British record fee months after he had won the World Cup with Argentina.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_869a64",
    "text": "Villarreal beat Manchester United 11-10 on penalties in the 2021 Europa League final in Gdansk after a 1-1 draw - their first major European trophy.",
    "cat": "LaLiga",
    "club": ""
   },
   {
    "id": "q_e951ee",
    "text": "Gianluigi Buffon was developed at Parma and broke into their first team as a teenager before winning the 2006 World Cup as Italy's first-choice keeper.",
    "cat": "SerieA",
    "club": "Parma"
   },
   {
    "id": "q_a1f6f5",
    "text": "Despite being widely regarded as the greatest Brazilian never to win the World Cup, the Flamengo legend captained the brilliant 1982 squad that fell to Italy.",
    "cat": "WorldCup",
    "club": ""
   },
   {
    "id": "q_10e27b",
    "text": "David Villa scored 59 goals for Spain, overtaking Raúl's 44 in 2011, and remains the country's record marksman after his 2008 Euro and 2010 World Cup triumphs.",
    "cat": "Records",
    "club": ""
   },
   {
    "id": "q_20e363",
    "text": "Fernando Hierro hit the bar first, but Miguel Nadal's decisive miss — saved by Seaman — sent England through 4-2. Stuart Pearce converted to exorcise his 1990 demons.",
    "cat": "Euros",
    "club": ""
   },
   {
    "id": "q_38fa8e",
    "text": "France hosted Euro 2016, the first expanded to 24 teams; Portugal won the final 1-0 at the Stade de France in Saint-Denis after extra time despite losing Ronaldo to injury.",
    "cat": "Euros",
    "club": ""
   },
   {
    "id": "q_106469",
    "text": "The Henri Delaunay Cup is named after the French administrator who first proposed a European championship; he died in 1955, five years before the inaugural 1960 tournament.",
    "cat": "Euros",
    "club": ""
   },
   {
    "id": "q_2ba2b5",
    "text": "Patrick Kluivert's late goal won Ajax the 1994-95 European Cup, completing an unbeaten campaign.",
    "cat": "UCL",
    "club": ""
   },
   {
    "id": "q_167fb0",
    "text": "Elvir Bolić scored the 1996 goal that ended United's unbeaten European home run at Old Trafford.",
    "cat": "SuperLig",
    "club": "Fenerbahçe"
   },
   {
    "id": "q_77bca7",
    "text": "Southgate's England reached the final of Euro 2020 only to lose on penalties to Italy at Wembley.",
    "cat": "Managers",
    "club": ""
   },
   {
    "id": "q_824beb",
    "text": "Celtic beat Inter 2-1 in Lisbon in 1967, becoming the first British club to win the European Cup.",
    "cat": "UCL",
    "club": "Inter Milan"
   },
   {
    "id": "q_2e23a6",
    "text": "Ronaldo scored 15 World Cup goals across three tournaments — a record until Klose broke it in 2014.",
    "cat": "Records",
    "club": ""
   },
   {
    "id": "q_28d40f",
    "text": "Real Madrid beat Maradona's Napoli 3-1 on aggregate in the first round of the 1987-88 European Cup.",
    "cat": "UCL",
    "club": "Napoli"
   }
  ]
 },
 {
  "theme": "European nights",
  "facts": [
   {
    "id": "q_e64614",
    "text": "A group stage was introduced in 1991-92, the last edition before the 'Champions League' rebrand in 1992-93.",
    "cat": "UCL",
    "club": ""
   },
   {
    "id": "q_3cae82",
    "text": "Zidane won two Serie A titles in Turin before his world-record transfer to Real Madrid in 2001 — where he scored that famous Champions League final volley a year later.",
    "cat": "Transfers",
    "club": "Juventus"
   },
   {
    "id": "q_bcec61",
    "text": "At 33, Ronaldo's €100m-plus move was meant to deliver the Champions League; it never came, but he did finish as Serie A's top scorer in 2020-21, winning the Capocannoniere.",
    "cat": "Transfers",
    "club": "Juventus"
   },
   {
    "id": "q_f92faa",
    "text": "Atalanta's first ever Champions League match ended in a 4-0 defeat at Maksimir in September 2019.",
    "cat": "ChampionsLeague",
    "club": "Dinamo Zagreb"
   },
   {
    "id": "q_4c4961",
    "text": "West Ham won the 1999 UEFA Intertoto Cup, beating Metz, to reach the UEFA Cup for the first time.",
    "cat": "ChampionsLeague",
    "club": "West Ham"
   },
   {
    "id": "q_01b4fa",
    "text": "Messi scored in 18 successive Champions League seasons (2005-06 to 2022-23), a competition record.",
    "cat": "UCL",
    "club": ""
   },
   {
    "id": "q_156eff",
    "text": "Falcao netted 17 goals in the 2010-11 Europa League, a single-season tournament record at the time.",
    "cat": "Primeira",
    "club": "Porto"
   },
   {
    "id": "q_a7e321",
    "text": "Falcao's 17 goals in 2010-11, including the final's winner against Braga, set a Europa League record.",
    "cat": "Primeira",
    "club": ""
   },
   {
    "id": "q_77d21e",
    "text": "Okan Buruk, a star of the 2000 UEFA Cup side, returned as coach and won the league in his first season.",
    "cat": "SuperLig",
    "club": "Galatasaray"
   },
   {
    "id": "q_44360a",
    "text": "Ancelotti has won the Champions League five times (2003, 2007, 2014, 2022, 2024) — a managerial record.",
    "cat": "Managers",
    "club": ""
   },
   {
    "id": "q_99bcf9",
    "text": "Alberto Malesani took charge in 1998 and won both the UEFA Cup and the Coppa Italia in his first season.",
    "cat": "SerieA",
    "club": "Parma"
   },
   {
    "id": "q_606b66",
    "text": "Javi Martínez joined Bayern Munich in a then club-record sale and won the Champions League there in 2013.",
    "cat": "Transfers",
    "club": "Athletic Bilbao"
   },
   {
    "id": "q_df738c",
    "text": "Francisco 'Paco' Gento won six European Cups between 1956 and 1966, an individual record for the competition.",
    "cat": "Records",
    "club": "Real Madrid"
   },
   {
    "id": "q_501eb8",
    "text": "Atalanta BC (founded 17 Oct 1907) is based in Bergamo. Won Europa League 2023-24 (first major European trophy).",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_8fbde7",
    "text": "Ronaldinho won his only Champions League title with Barcelona, who beat Arsenal 2-1 in the 2006 final in Paris.",
    "cat": "UCL",
    "club": ""
   },
   {
    "id": "q_54d82e",
    "text": "Ernst Happel won the European Cup with Feyenoord in 1970 and Hamburg in 1983, the first to do it with two clubs.",
    "cat": "Legends",
    "club": ""
   },
   {
    "id": "q_6bcfe9",
    "text": "Alfredo Di Stéfano scored in each of Real Madrid's first 5 European Cup finals (1956, 57, 58, 59, 60) — all wins.",
    "cat": "Legends",
    "club": ""
   },
   {
    "id": "q_7dd95e",
    "text": "Miguel Munoz played in Madrid's first European Cup triumphs, then coached the club to the trophy in 1960 and 1966.",
    "cat": "Managers",
    "club": "Real Madrid"
   },
   {
    "id": "q_295b7b",
    "text": "André Villas-Boas, aged 33, led Porto through 2010-11 unbeaten in the league while also winning the Europa League.",
    "cat": "Primeira",
    "club": ""
   },
   {
    "id": "q_cbf8b3",
    "text": "Brian Clough — two-time European Cup winner with Nottingham Forest (1979, 1980) and never afraid of a sharp one-liner.",
    "cat": "Legends",
    "club": ""
   }
  ]
 },
 {
  "theme": "Clubs & rivalries",
  "facts": [
   {
    "id": "q_c861b3",
    "text": "Frank Lampard came through at West Ham before joining Chelsea in 2001 and becoming their all-time top scorer.",
    "cat": "Legends",
    "club": "West Ham"
   },
   {
    "id": "q_6ea91a",
    "text": "Lens needed only a draw at Gerland to be champions, but Lyon won 3-1 to snatch the title on the last day of 2001-02.",
    "cat": "Ligue1",
    "club": "Olympique Lyonnais"
   },
   {
    "id": "q_f2ec53",
    "text": "Zidane cost roughly €75m from Juventus, a record fee, the summer before he scored his famous volley in the 2002 final.",
    "cat": "Transfers",
    "club": "Real Madrid"
   },
   {
    "id": "q_aa60d6",
    "text": "Galatasaray beat Real Madrid 3-2 in Istanbul on 9 April 2013, but a 3-0 first-leg defeat meant Madrid went through 5-3.",
    "cat": "ChampionsLeague",
    "club": "Galatasaray"
   },
   {
    "id": "q_e7562f",
    "text": "Gianfranco Zola scored seconds after coming on as a substitute in Stockholm; it was the same trophy Chelsea first won in 1971.",
    "cat": "UCL",
    "club": "Chelsea"
   },
   {
    "id": "q_a1abe7",
    "text": "After refusing to extend, Mbappé departed as a free agent in summer 2024 — leaving with 256 goals, a PSG record that still stands.",
    "cat": "Transfers",
    "club": "Paris Saint-Germain"
   },
   {
    "id": "q_a83384",
    "text": "The 1967-68 title, sealed by a 4-3 win at Newcastle, was their last before Aguero's QPR goal ended a 44-year wait for the championship.",
    "cat": "Legends",
    "club": "Manchester City"
   },
   {
    "id": "q_ae0f6e",
    "text": "İlkay Gündoğan scored both goals at Wembley on 3 June 2023, the first after just 12 seconds, in the first Manchester derby FA Cup final.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_af8581",
    "text": "The Swede arrived in 1997 and delivered the league and cup double, before leaving in January 2001 to become England's first foreign manager.",
    "cat": "Managers",
    "club": "Lazio"
   },
   {
    "id": "q_f27da0",
    "text": "Ballack moved to Bayern Munich in the summer of 2002 after three seasons at Leverkusen, and won the domestic double in his first year there.",
    "cat": "Bundesliga",
    "club": "Bayer Leverkusen"
   },
   {
    "id": "q_6f7028",
    "text": "Ronaldo became the second player after Maradona to break the world transfer record twice; he won the 1997 Ballon d'Or as Inter's new phenomenon.",
    "cat": "Transfers",
    "club": "Inter Milan"
   },
   {
    "id": "q_1f45af",
    "text": "Lehmann was dismissed after just 18 minutes of the 2006 final for hauling down Samuel Eto'o, becoming the first man red-carded in the showpiece.",
    "cat": "Legends",
    "club": "Arsenal"
   },
   {
    "id": "q_40804a",
    "text": "After a spell at Newell's Old Boys and a 15-month doping ban, he played on at La Bombonera until 1997 — a second stint following his first in 1981-82.",
    "cat": "History",
    "club": "Boca Juniors"
   },
   {
    "id": "q_5aec3d",
    "text": "Darko Kovačević first played for Real Sociedad from 1996 to 1999, then returned mid-way through the 2001-02 season after spells at Juventus and Lazio.",
    "cat": "LaLiga",
    "club": "Real Sociedad"
   },
   {
    "id": "q_e7e02a",
    "text": "\"93:20\" has entered City folklore as shorthand for the goal, scored seconds before the final whistle to clinch the club's first league title since 1968.",
    "cat": "PL",
    "club": "Manchester City"
   },
   {
    "id": "q_b1f3cd",
    "text": "Neal Maupay put Brentford ahead at the Gtech Community Stadium before Foden struck in first-half stoppage time and twice after the break on 5 February 2024.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_604e72",
    "text": "Journalist Gianni Brera coined 'Derby d'Italia' for Juventus v Inter, historically the only two clubs never relegated at the time (before Juve's 2006 demotion).",
    "cat": "Legends",
    "club": "Juventus"
   },
   {
    "id": "q_3c9c6a",
    "text": "Atalanta finished 18th in 2009-10 and went down, but won Serie B at the first attempt and have been a top-flight club ever since — the end of decades of yo-yoing.",
    "cat": "Legends",
    "club": "Atalanta"
   },
   {
    "id": "q_346500",
    "text": "Vic Watson scored 326 goals after joining in 1920 — the club's all-time record.",
    "cat": "Records",
    "club": "West Ham"
   },
   {
    "id": "q_20bfc1",
    "text": "HSV's first postwar German title came in 1960, before the Bundesliga era began.",
    "cat": "Records",
    "club": "Hamburger SV"
   }
  ]
 },
 {
  "theme": "Players & legends",
  "facts": [
   {
    "id": "q_150a91",
    "text": "Long scored after 7.69 seconds against Watford in April 2019, beating Ledley King's record by more than two seconds.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_15d058",
    "text": "Ferguson won 13 of the first 21 Premier League titles, the last of them in 2012-13, his final season before retiring.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_fb20a2",
    "text": "Shilton won 125 caps between 1970 and 1990, the England appearance record that stood for decades after his retirement.",
    "cat": "Records",
    "club": ""
   },
   {
    "id": "q_bd3e4b",
    "text": "Cech won four Golden Gloves at Chelsea and added another in 2015-16, his first season at Arsenal after crossing London.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_279a01",
    "text": "Kaká wore #22 at AC Milan. He won the Ballon d'Or in 2007 at Milan before his record €65m transfer to Real Madrid in 2009.",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_51d6f2",
    "text": "Pogba returned from Juventus in 2016 for a world record fee, four years after leaving Manchester United on a free transfer.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_c881cf",
    "text": "Ronaldo first did the 'Siu' after scoring for Real Madrid against Chelsea in a pre-season friendly in Miami in August 2013.",
    "cat": "Records",
    "club": ""
   },
   {
    "id": "q_f33641",
    "text": "Harry Kane scored 213 Premier League goals for Tottenham between 2011 and 2023 - a club record - before moving to Bayern Munich.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_d4381a",
    "text": "De Bruyne made only nine Chelsea appearances before leaving for Wolfsburg in 2014, returning to England with City 18 months later.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_2c4234",
    "text": "Lazio had only won the Scudetto once before (1974) and clinched it on the dramatic final day when Juventus slipped up against Perugia.",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_28237a",
    "text": "Owen joined Newcastle for a club record fee in 2005 after a single season at Real Madrid, with Liverpool unwilling to match the price.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_0462d3",
    "text": "The North London side dominated the early WSL era, winning the first two editions in 2011 and 2012 before Liverpool took the next two.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_df98cf",
    "text": "United paid Juventus around 89 million pounds for Pogba in 2016, a world record at the time, four years after letting him leave for nothing.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_a7a4bd",
    "text": "Aguero joined Barcelona on a free in 2021 as City's all-time leading scorer, but retired within months after a heart condition was diagnosed.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_2658f6",
    "text": "Thomas Muller holds the all-time Bundesliga assist record with 178 assists for Bayern Munich, a mark frozen after his 2025 departure for MLS.",
    "cat": "Bundesliga",
    "club": ""
   },
   {
    "id": "q_9f5b64",
    "text": "Chelsea re-signed Lukaku from Inter in 2021 for a club record fee, a decade after first buying him as a teenager; he was loaned out again within a year.",
    "cat": "PL",
    "club": ""
   },
   {
    "id": "q_7f9bce",
    "text": "Canada hosts the men's WC for the first time in 2026, even though they played as a team in Mexico 1986. Only Toronto and Vancouver will host matches in Canada.",
    "cat": "WorldCup",
    "club": ""
   },
   {
    "id": "q_059db8",
    "text": "Napoli sealed their first-ever Scudetto with a 1-1 draw against Fiorentina at the San Paolo in 1986-87, 61 years after the club's founding, with Maradona as captain.",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_f3b13c",
    "text": "Totti scored the last-minute PK vs Australia (R16, Kaiserslautern) on 26 June 2006 after Grosso was 'fouled'. It was a regular low penalty to the corner, NOT a Panenka.",
    "cat": "SerieA",
    "club": ""
   },
   {
    "id": "q_9fe15f",
    "text": "Ryan Giggs took caretaker charge for United's last four games of 2013-14 after Moyes was sacked in April 2014; Louis van Gaal was appointed permanent manager that summer.",
    "cat": "PL",
    "club": ""
   }
  ]
 }
];
