// ─────────────────────────────────────────────────────────────────────────────
// CLUBS DIRECTORY DATA — league rosters, codes and colours for /quiz/clubs/.
//
// FORGE-VERIFIED (2026-07-21): each league independently re-derived from the web
// (season articles / league sites) by the clubs-directory-roster-verify
// workflow, correcting the Claude Design draft (which the designer flagged as
// "best guesses"). Per-league season + change-log in the workflow output.
//
//   - name  → short display name (matches CLUBS.name or DIR_ALIAS in the
//             generator; a built club renders as a live /quiz/<slug>/ link)
//   - code  → 2-4 char code, unique WITHIN its league (not globally)
//   - color → decorative identification dot only — never crests/kits
//
// SEASONAL: refresh every May–June with promotion/relegation (same cadence as
// the /lists refresh — see task #52).
// ─────────────────────────────────────────────────────────────────────────────

export const LEAGUES = [
  {
    league: "Premier League", country: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", season: "2026-27",
    clubs: [
    { code: "ARS", name: "Arsenal", color: "#ef0107" },
    { code: "AVL", name: "Aston Villa", color: "#670e36" },
    { code: "BOU", name: "Bournemouth", color: "#da291c" },
    { code: "BRE", name: "Brentford", color: "#e30613" },
    { code: "BHA", name: "Brighton", color: "#2e7dd1" },
    { code: "CHE", name: "Chelsea", color: "#2f6bd6" },
    { code: "COV", name: "Coventry", color: "#059dd9" },
    { code: "CRY", name: "Crystal Palace", color: "#4667b8" },
    { code: "EVE", name: "Everton", color: "#2d62c6" },
    { code: "FUL", name: "Fulham", color: "#e6e6e6" },
    { code: "HUL", name: "Hull City", color: "#f18a01" },
    { code: "IPS", name: "Ipswich", color: "#3a64a3" },
    { code: "LEE", name: "Leeds United", color: "#f5c400" },
    { code: "LIV", name: "Liverpool", color: "#c8102e" },
    { code: "MCI", name: "Man City", color: "#6cabdd" },
    { code: "MUN", name: "Man United", color: "#da291c" },
    { code: "NEW", name: "Newcastle", color: "#d7d7d7" },
    { code: "NFO", name: "Nott'm Forest", color: "#e11b22" },
    { code: "SUN", name: "Sunderland", color: "#eb172b" },
    { code: "TOT", name: "Tottenham", color: "#aeb9d6" },
    ],
  },
  {
    league: "Championship", country: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", season: "2026-27",
    clubs: [
    { code: "NOR", name: "Norwich City", color: "#f0e14a" },
    { code: "MID", name: "Middlesbrough", color: "#e21a23" },
    { code: "WBA", name: "West Brom", color: "#5c7bc0" },
    { code: "STK", name: "Stoke City", color: "#e03a3e" },
    { code: "PNE", name: "Preston", color: "#dce6f5" },
    { code: "QPR", name: "QPR", color: "#1d5ba4" },
    { code: "WAT", name: "Watford", color: "#f2e23a" },
    { code: "MLW", name: "Millwall", color: "#3d63c9" },
    { code: "BLB", name: "Blackburn", color: "#009ee0" },
    { code: "SHU", name: "Sheffield Utd", color: "#ee2737" },
    { code: "BRC", name: "Bristol City", color: "#e21a23" },
    { code: "SWA", name: "Swansea City", color: "#ececec" },
    { code: "CAR", name: "Cardiff City", color: "#0070b5" },
    { code: "DER", name: "Derby County", color: "#e6e6e6" },
    { code: "POM", name: "Portsmouth", color: "#1e63c4" },
    { code: "SOU", name: "Southampton", color: "#d71920" },
    { code: "WRX", name: "Wrexham", color: "#e21a23" },
    { code: "BIR", name: "Birmingham City", color: "#2c5ea9" },
    { code: "CHA", name: "Charlton", color: "#e31b23" },
    { code: "WHU", name: "West Ham", color: "#7a263a" },
    { code: "BUR", name: "Burnley", color: "#6c1d45" },
    { code: "WOL", name: "Wolves", color: "#fdb913" },
    { code: "BOL", name: "Bolton", color: "#e6e6e6" },
    { code: "LIN", name: "Lincoln City", color: "#d92c2c" },
    ],
  },
  {
    league: "La Liga", country: "Spain", flag: "🇪🇸", season: "2026-27",
    clubs: [
    { code: "RMA", name: "Real Madrid", color: "#ececec" },
    { code: "BAR", name: "Barcelona", color: "#a50044" },
    { code: "ATM", name: "Atlético Madrid", color: "#cb3524" },
    { code: "ATH", name: "Athletic Club", color: "#ee2523" },
    { code: "SEV", name: "Sevilla", color: "#d8d8d8" },
    { code: "BET", name: "Real Betis", color: "#00954c" },
    { code: "RSO", name: "Real Sociedad", color: "#0067b1" },
    { code: "VAL", name: "Valencia", color: "#f18e00" },
    { code: "VIL", name: "Villarreal", color: "#f2d53c" },
    { code: "CEL", name: "Celta Vigo", color: "#6cafe0" },
    { code: "OSA", name: "Osasuna", color: "#d0021b" },
    { code: "GET", name: "Getafe", color: "#1e63c4" },
    { code: "ALA", name: "Alavés", color: "#3d74c4" },
    { code: "ESP", name: "Espanyol", color: "#2e7dd1" },
    { code: "RAY", name: "Rayo Vallecano", color: "#d0021b" },
    { code: "LEV", name: "Levante", color: "#3d63c9" },
    { code: "ELC", name: "Elche", color: "#e6e6e6" },
    { code: "RAC", name: "Racing Santander", color: "#00a651" },
    { code: "DEP", name: "Deportivo", color: "#0068b3" },
    { code: "MAL", name: "Málaga", color: "#005ca9" },
    ],
  },
  {
    league: "Bundesliga", country: "Germany", flag: "🇩🇪", season: "2026-27",
    clubs: [
    { code: "BAY", name: "Bayern Munich", color: "#dc052d" },
    { code: "BVB", name: "Dortmund", color: "#f5d800" },
    { code: "B04", name: "Leverkusen", color: "#e32221" },
    { code: "RBL", name: "RB Leipzig", color: "#d8123c" },
    { code: "SGE", name: "Frankfurt", color: "#e1000f" },
    { code: "VFB", name: "Stuttgart", color: "#da1f26" },
    { code: "BMG", name: "Gladbach", color: "#18a05a" },
    { code: "SCF", name: "Freiburg", color: "#d0021b" },
    { code: "TSG", name: "Hoffenheim", color: "#1c63b7" },
    { code: "M05", name: "Mainz 05", color: "#ed1c24" },
    { code: "FCA", name: "Augsburg", color: "#ba3733" },
    { code: "SVW", name: "Werder Bremen", color: "#1d9053" },
    { code: "FCU", name: "Union Berlin", color: "#eb1923" },
    { code: "KOE", name: "Köln", color: "#ed1c24" },
    { code: "HSV", name: "Hamburger SV", color: "#1e63c4" },
    { code: "S04", name: "Schalke", color: "#004d9d" },
    { code: "ELV", name: "Elversberg", color: "#1a1a1a" },
    { code: "SCP", name: "Paderborn", color: "#005ca8" },
    ],
  },
  {
    league: "Serie A", country: "Italy", flag: "🇮🇹", season: "2026-27",
    clubs: [
    { code: "INT", name: "Inter Milan", color: "#0068a8" },
    { code: "MIL", name: "AC Milan", color: "#fb090b" },
    { code: "JUV", name: "Juventus", color: "#e8e8e8" },
    { code: "NAP", name: "Napoli", color: "#199fda" },
    { code: "ROM", name: "Roma", color: "#a32638" },
    { code: "LAZ", name: "Lazio", color: "#87d8f7" },
    { code: "ATA", name: "Atalanta", color: "#1e71b8" },
    { code: "FIO", name: "Fiorentina", color: "#7b4fa0" },
    { code: "BOL", name: "Bologna", color: "#b0242f" },
    { code: "TOR", name: "Torino", color: "#9e2b24" },
    { code: "UDI", name: "Udinese", color: "#ececec" },
    { code: "GEN", name: "Genoa", color: "#c8102e" },
    { code: "COM", name: "Como", color: "#1e63c4" },
    { code: "CAG", name: "Cagliari", color: "#c00e37" },
    { code: "PAR", name: "Parma", color: "#f5d800" },
    { code: "LEC", name: "Lecce", color: "#f5c400" },
    { code: "SAS", name: "Sassuolo", color: "#00a752" },
    { code: "VEN", name: "Venezia", color: "#1f1f1f" },
    { code: "FRO", name: "Frosinone", color: "#ffd500" },
    { code: "MON", name: "Monza", color: "#e30613" },
    ],
  },
  {
    league: "Ligue 1", country: "France", flag: "🇫🇷", season: "2026-27",
    clubs: [
    { code: "PSG", name: "PSG", color: "#2758a5" },
    { code: "OM", name: "Marseille", color: "#2faee0" },
    { code: "OL", name: "Lyon", color: "#3d74c4" },
    { code: "MON", name: "Monaco", color: "#da291c" },
    { code: "LIL", name: "Lille", color: "#e01e13" },
    { code: "NIC", name: "Nice", color: "#c8102e" },
    { code: "LEN", name: "Lens", color: "#f0c420" },
    { code: "REN", name: "Rennes", color: "#e13327" },
    { code: "STR", name: "Strasbourg", color: "#2e7dd1" },
    { code: "TOU", name: "Toulouse", color: "#7b4fa0" },
    { code: "BST", name: "Brest", color: "#da291c" },
    { code: "AUX", name: "Auxerre", color: "#ececec" },
    { code: "ANG", name: "Angers", color: "#d7d7d7" },
    { code: "LEH", name: "Le Havre", color: "#6cafe0" },
    { code: "LOR", name: "Lorient", color: "#f36f21" },
    { code: "PFC", name: "Paris FC", color: "#3d63c9" },
    { code: "TRO", name: "Troyes", color: "#1e5cae" },
    { code: "LEM", name: "Le Mans", color: "#d52b1e" },
    ],
  },
  {
    league: "Eredivisie", country: "Netherlands", flag: "🇳🇱", season: "2026-27",
    clubs: [
    { code: "AJA", name: "Ajax", color: "#d2122e" },
    { code: "PSV", name: "PSV", color: "#ed1c24" },
    { code: "FEY", name: "Feyenoord", color: "#e2231a" },
    { code: "AZ", name: "AZ Alkmaar", color: "#e11b22" },
    { code: "TWE", name: "Twente", color: "#c8102e" },
    { code: "UTR", name: "Utrecht", color: "#d0021b" },
    { code: "SPR", name: "Sparta Rotterdam", color: "#da291c" },
    { code: "NEC", name: "NEC Nijmegen", color: "#1d9053" },
    { code: "GAE", name: "Go Ahead Eagles", color: "#f0c420" },
    { code: "HEE", name: "Heerenveen", color: "#2e7dd1" },
    { code: "FOR", name: "Fortuna Sittard", color: "#f5c400" },
    { code: "PEC", name: "PEC Zwolle", color: "#3d74c4" },
    { code: "GRO", name: "Groningen", color: "#18a05a" },
    { code: "EXC", name: "Excelsior", color: "#da291c" },
    { code: "TEL", name: "Telstar", color: "#ececec" },
    { code: "ADO", name: "ADO Den Haag", color: "#007a3d" },
    { code: "CAM", name: "Cambuur", color: "#f5d000" },
    { code: "WIL", name: "Willem II", color: "#2456a4" },
    ],
  },
  {
    league: "Primeira Liga", country: "Portugal", flag: "🇵🇹", season: "2026-27",
    clubs: [
    { code: "SLB", name: "Benfica", color: "#e30613" },
    { code: "POR", name: "Porto", color: "#2e7dd1" },
    { code: "SCP", name: "Sporting CP", color: "#18a05a" },
    { code: "BRA", name: "Braga", color: "#da291c" },
    { code: "VSC", name: "Vitória SC", color: "#ececec" },
    { code: "FAM", name: "Famalicão", color: "#1e63c4" },
    { code: "RAV", name: "Rio Ave", color: "#1d9053" },
    { code: "GIL", name: "Gil Vicente", color: "#c8102e" },
    { code: "EST", name: "Estoril", color: "#f5c400" },
    { code: "ARO", name: "Arouca", color: "#f5d800" },
    { code: "CAS", name: "Casa Pia", color: "#d7d7d7" },
    { code: "MOR", name: "Moreirense", color: "#18a05a" },
    { code: "NAC", name: "Nacional", color: "#1f1f1f" },
    { code: "SCL", name: "Santa Clara", color: "#d5202f" },
    { code: "ALV", name: "Alverca", color: "#d2232a" },
    { code: "EAM", name: "Estrela Amadora", color: "#e2231a" },
    { code: "MAR", name: "Marítimo", color: "#0f7d3f" },
    { code: "AVI", name: "Académico Viseu", color: "#e6e6e6" },
    ],
  },
  {
    league: "Süper Lig", country: "Türkiye", flag: "🇹🇷", season: "2026-27",
    clubs: [
    { code: "GAL", name: "Galatasaray", color: "#f5a623" },
    { code: "FEN", name: "Fenerbahçe", color: "#f0c420" },
    { code: "BJK", name: "Beşiktaş", color: "#ececec" },
    { code: "TRA", name: "Trabzonspor", color: "#8a2a44" },
    { code: "BAS", name: "Başakşehir", color: "#f36f21" },
    { code: "SAM", name: "Samsunspor", color: "#da291c" },
    { code: "KON", name: "Konyaspor", color: "#18a05a" },
    { code: "ALN", name: "Alanyaspor", color: "#e96d1f" },
    { code: "KAS", name: "Kasımpaşa", color: "#3d74c4" },
    { code: "RIZ", name: "Rizespor", color: "#1d9053" },
    { code: "EYU", name: "Eyüpspor", color: "#6f2c91" },
    { code: "GAZ", name: "Gaziantep FK", color: "#e30613" },
    { code: "GEN", name: "Gençlerbirliği", color: "#d1202b" },
    { code: "GOZ", name: "Göztepe", color: "#f4c20d" },
    { code: "KOC", name: "Kocaelispor", color: "#00703c" },
    { code: "ERZ", name: "Erzurumspor", color: "#1d64b0" },
    { code: "AMD", name: "Amedspor", color: "#0c8a4a" },
    { code: "COR", name: "Çorum FK", color: "#d21f2a" },
    ],
  },
  {
    league: "Premiership", country: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", season: "2026-27",
    clubs: [
    { code: "CEL", name: "Celtic", color: "#18a05a" },
    { code: "RAN", name: "Rangers", color: "#2e7dd1" },
    { code: "HEA", name: "Hearts", color: "#8a2a44" },
    { code: "HIB", name: "Hibernian", color: "#1d9053" },
    { code: "ABE", name: "Aberdeen", color: "#d0021b" },
    { code: "DUN", name: "Dundee United", color: "#f36f21" },
    { code: "DEE", name: "Dundee", color: "#3d63c9" },
    { code: "MOT", name: "Motherwell", color: "#f0d51f" },
    { code: "STM", name: "St Mirren", color: "#d7d7d7" },
    { code: "KIL", name: "Kilmarnock", color: "#2e7dd1" },
    { code: "FAL", name: "Falkirk", color: "#3d74c4" },
    { code: "STJ", name: "St Johnstone", color: "#2b64b8" },
    ],
  },
  {
    league: "Eliteserien", country: "Norway", flag: "🇳🇴", season: "2026",
    clubs: [
    { code: "BOD", name: "Bodø/Glimt", color: "#f5d800" },
    { code: "MOL", name: "Molde", color: "#2e7dd1" },
    { code: "RBK", name: "Rosenborg", color: "#d7d7d7" },
    { code: "BRN", name: "Brann", color: "#d0021b" },
    { code: "VIK", name: "Viking", color: "#3d63c9" },
    { code: "VIF", name: "Vålerenga", color: "#4667b8" },
    { code: "LSK", name: "Lillestrøm", color: "#f0d51f" },
    { code: "TIL", name: "Tromsø", color: "#da291c" },
    { code: "S08", name: "Sarpsborg 08", color: "#3d74c4" },
    { code: "KBK", name: "Kristiansund", color: "#c8102e" },
    { code: "HAM", name: "HamKam", color: "#18a05a" },
    { code: "SAN", name: "Sandefjord", color: "#6cafe0" },
    { code: "FFK", name: "Fredrikstad", color: "#d0021b" },
    { code: "KFUM", name: "KFUM Oslo", color: "#e03131" },
    { code: "STA", name: "Start", color: "#ffd500" },
    { code: "AAFK", name: "Aalesund", color: "#f58220" },
    ],
  },
  {
    league: "Allsvenskan", country: "Sweden", flag: "🇸🇪", season: "2026",
    clubs: [
    { code: "MFF", name: "Malmö FF", color: "#6cafe0" },
    { code: "AIK", name: "AIK", color: "#1f1f1f" },
    { code: "DIF", name: "Djurgården", color: "#3d74c4" },
    { code: "HAM", name: "Hammarby", color: "#18a05a" },
    { code: "IFK", name: "IFK Göteborg", color: "#2e7dd1" },
    { code: "HAC", name: "Häcken", color: "#f0d51f" },
    { code: "ELF", name: "Elfsborg", color: "#f5d800" },
    { code: "SIR", name: "Sirius", color: "#1e63c4" },
    { code: "MJA", name: "Mjällby", color: "#f5c400" },
    { code: "GAIS", name: "GAIS", color: "#0b7d4e" },
    { code: "HBK", name: "Halmstad", color: "#1259a9" },
    { code: "BP", name: "Brommapojkarna", color: "#d81e2a" },
    { code: "DEG", name: "Degerfors", color: "#e01e26" },
    { code: "KFF", name: "Kalmar", color: "#d71920" },
    { code: "VSK", name: "Västerås SK", color: "#0e7a3c" },
    { code: "OIS", name: "Örgryte", color: "#c8102e" },
    ],
  },
  {
    league: "Superliga", country: "Denmark", flag: "🇩🇰", season: "2026-27",
    clubs: [
    { code: "FCK", name: "Copenhagen", color: "#002f6c" },
    { code: "FCM", name: "Midtjylland", color: "#d0021b" },
    { code: "BIF", name: "Brøndby", color: "#f0c420" },
    { code: "AGF", name: "AGF Aarhus", color: "#e6e6e6" },
    { code: "FCN", name: "Nordsjælland", color: "#f5c400" },
    { code: "SIL", name: "Silkeborg", color: "#da291c" },
    { code: "RFC", name: "Randers", color: "#6cafe0" },
    { code: "VFF", name: "Viborg", color: "#1d9053" },
    { code: "OB", name: "OB Odense", color: "#3d74c4" },
    { code: "SDR", name: "Sønderjyske", color: "#6cafe0" },
    { code: "LBK", name: "Lyngby", color: "#1a4fa0" },
    { code: "ACH", name: "AC Horsens", color: "#ffd100" },
    ],
  },
  {
    league: "HNL", country: "Croatia", flag: "🇭🇷", season: "2026-27",
    clubs: [
    { code: "DIN", name: "Dinamo Zagreb", color: "#2e7dd1" },
    { code: "HAJ", name: "Hajduk Split", color: "#e6e6e6" },
    { code: "RIJ", name: "Rijeka", color: "#d7d7d7" },
    { code: "OSI", name: "Osijek", color: "#3d74c4" },
    { code: "LOK", name: "Lokomotiva", color: "#2456a4" },
    { code: "GOR", name: "Gorica", color: "#c8102e" },
    { code: "IST", name: "Istra 1961", color: "#18a05a" },
    { code: "SLA", name: "Slaven Belupo", color: "#e6e6e6" },
    { code: "VAR", name: "Varaždin", color: "#004194" },
    { code: "RUD", name: "Rudeš", color: "#d0021b" },
    ],
  },
  {
    league: "Pro League", country: "Belgium", flag: "🇧🇪", season: "2026-27",
    clubs: [
    { code: "CLU", name: "Club Brugge", color: "#2e7dd1" },
    { code: "AND", name: "Anderlecht", color: "#7b4fa0" },
    { code: "GNK", name: "Genk", color: "#3d74c4" },
    { code: "GNT", name: "Gent", color: "#6cafe0" },
    { code: "STA", name: "Standard Liège", color: "#d0021b" },
    { code: "ANR", name: "Antwerp", color: "#c8102e" },
    { code: "USG", name: "Union SG", color: "#f0c420" },
    { code: "CHA", name: "Charleroi", color: "#d7d7d7" },
    { code: "MEC", name: "Mechelen", color: "#f5a623" },
    { code: "WES", name: "Westerlo", color: "#f0d51f" },
    { code: "CER", name: "Cercle Brugge", color: "#009344" },
    { code: "OHL", name: "OH Leuven", color: "#e6e6e6" },
    { code: "STVV", name: "Sint-Truiden", color: "#ffdd00" },
    { code: "LOU", name: "La Louvière", color: "#006b3f" },
    { code: "ZWA", name: "Zulte Waregem", color: "#d71920" },
    { code: "BEV", name: "Beveren", color: "#ffd100" },
    { code: "KOR", name: "Kortrijk", color: "#e30613" },
    { code: "LOM", name: "Lommel", color: "#37a34a" },
    ],
  },
  {
    league: "MLS", country: "USA", flag: "🇺🇸", season: "2026",
    clubs: [
    { code: "ATL", name: "Atlanta United", color: "#b0242f" },
    { code: "ATX", name: "Austin FC", color: "#65b32e" },
    { code: "CLT", name: "Charlotte FC", color: "#1a85c8" },
    { code: "CHI", name: "Chicago Fire", color: "#d0021b" },
    { code: "CIN", name: "FC Cincinnati", color: "#f36f21" },
    { code: "COL", name: "Colorado Rapids", color: "#960a2c" },
    { code: "CLB", name: "Columbus Crew", color: "#f5d800" },
    { code: "DAL", name: "FC Dallas", color: "#bf0d3e" },
    { code: "DCU", name: "D.C. United", color: "#231f20" },
    { code: "HOU", name: "Houston Dynamo", color: "#ff6b00" },
    { code: "SKC", name: "Sporting KC", color: "#93b1d7" },
    { code: "LAG", name: "LA Galaxy", color: "#3d74c4" },
    { code: "LAF", name: "LAFC", color: "#f0c420" },
    { code: "MIA", name: "Inter Miami", color: "#f5a9c4" },
    { code: "MIN", name: "Minnesota United", color: "#8cd2f4" },
    { code: "MTL", name: "CF Montréal", color: "#0033a1" },
    { code: "NSH", name: "Nashville SC", color: "#ece83a" },
    { code: "NER", name: "NE Revolution", color: "#0a2240" },
    { code: "NYC", name: "NYCFC", color: "#6cafe0" },
    { code: "RBN", name: "NY Red Bulls", color: "#da291c" },
    { code: "ORL", name: "Orlando City", color: "#633492" },
    { code: "PHI", name: "Philadelphia Union", color: "#002855" },
    { code: "PTF", name: "Portland Timbers", color: "#1d9053" },
    { code: "RSL", name: "Real Salt Lake", color: "#b30838" },
    { code: "SDG", name: "San Diego FC", color: "#051c2c" },
    { code: "SJE", name: "San Jose Earthquakes", color: "#0067b1" },
    { code: "SEA", name: "Seattle Sounders", color: "#18a05a" },
    { code: "STL", name: "St. Louis City", color: "#e4002b" },
    { code: "TOR", name: "Toronto FC", color: "#b81137" },
    { code: "VAN", name: "Vancouver Whitecaps", color: "#002a5c" },
    ],
  },
  {
    league: "Brasileirão", country: "Brazil", flag: "🇧🇷", season: "2026",
    clubs: [
    { code: "FLA", name: "Flamengo", color: "#d0021b" },
    { code: "PAL", name: "Palmeiras", color: "#18a05a" },
    { code: "COR", name: "Corinthians", color: "#e6e6e6" },
    { code: "SAO", name: "São Paulo", color: "#c8102e" },
    { code: "SFC", name: "Santos", color: "#d7d7d7" },
    { code: "FLU", name: "Fluminense", color: "#8a2a44" },
    { code: "BOT", name: "Botafogo", color: "#e6e6e6" },
    { code: "GRE", name: "Grêmio", color: "#6cafe0" },
    { code: "INT", name: "Internacional", color: "#da291c" },
    { code: "CAM", name: "Atlético Mineiro", color: "#d7d7d7" },
    { code: "CRU", name: "Cruzeiro", color: "#3d74c4" },
    { code: "VAS", name: "Vasco da Gama", color: "#e6e6e6" },
    { code: "BAH", name: "Bahia", color: "#0066b3" },
    { code: "MIR", name: "Mirassol", color: "#f4c20d" },
    { code: "BGT", name: "Bragantino", color: "#e6e6e6" },
    { code: "VIT", name: "Vitória", color: "#e31837" },
    { code: "CTB", name: "Coritiba", color: "#00694e" },
    { code: "CAP", name: "Athletico-PR", color: "#ce181e" },
    { code: "CHA", name: "Chapecoense", color: "#009846" },
    { code: "REM", name: "Remo", color: "#002d72" },
    ],
  },
  {
    league: "Primera División", country: "Argentina", flag: "🇦🇷", season: "2026",
    clubs: [
    { code: "BOC", name: "Boca Juniors", color: "#f0c420" },
    { code: "RIV", name: "River Plate", color: "#d0021b" },
    { code: "RAC", name: "Racing Club", color: "#6cafe0" },
    { code: "IND", name: "Independiente", color: "#da291c" },
    { code: "SLO", name: "San Lorenzo", color: "#3d63c9" },
    { code: "EDL", name: "Estudiantes LP", color: "#c8102e" },
    { code: "VEL", name: "Vélez", color: "#e6e6e6" },
    { code: "NOB", name: "Newell's", color: "#d0021b" },
    { code: "RCE", name: "Rosario Central", color: "#f5c400" },
    { code: "TAL", name: "Talleres", color: "#2e7dd1" },
    { code: "ALD", name: "Aldosivi", color: "#f2c500" },
    { code: "ARG", name: "Argentinos Jrs", color: "#d7282f" },
    { code: "ATU", name: "Atlético Tucumán", color: "#75aadb" },
    { code: "BAN", name: "Banfield", color: "#0a8f4e" },
    { code: "BAR", name: "Barracas Central", color: "#d22630" },
    { code: "BEL", name: "Belgrano", color: "#62b5e5" },
    { code: "CCO", name: "Central Córdoba", color: "#2e2e2e" },
    { code: "DYJ", name: "Defensa y Justicia", color: "#16a34a" },
    { code: "RIE", name: "Dep. Riestra", color: "#1f1f1f" },
    { code: "ERC", name: "Estudiantes RC", color: "#5fa8d8" },
    { code: "GLP", name: "Gimnasia LP", color: "#123a75" },
    { code: "GMZ", name: "Gimnasia Mendoza", color: "#e0e0e0" },
    { code: "HUR", name: "Huracán", color: "#ececec" },
    { code: "IRV", name: "Indep. Rivadavia", color: "#1a4f9e" },
    { code: "INS", name: "Instituto", color: "#d81e2c" },
    { code: "LAN", name: "Lanús", color: "#7a1f3d" },
    { code: "PLA", name: "Platense", color: "#6d4c33" },
    { code: "SAR", name: "Sarmiento", color: "#1e8449" },
    { code: "TIG", name: "Tigre", color: "#1d3f94" },
    { code: "UNI", name: "Unión", color: "#cb2231" },
    ],
  },
  {
    league: "Saudi Pro League", country: "Saudi Arabia", flag: "🇸🇦", season: "2026-27",
    clubs: [
    { code: "HIL", name: "Al Hilal", color: "#2e7dd1" },
    { code: "NAS", name: "Al Nassr", color: "#f0c420" },
    { code: "ITT", name: "Al Ittihad", color: "#f5d800" },
    { code: "AHL", name: "Al Ahli", color: "#18a05a" },
    { code: "SHB", name: "Al Shabab", color: "#d7d7d7" },
    { code: "ETT", name: "Al Ettifaq", color: "#1d9053" },
    { code: "TAA", name: "Al Taawoun", color: "#f5a623" },
    { code: "FAT", name: "Al Fateh", color: "#6cafe0" },
    { code: "QAD", name: "Al Qadsiah", color: "#f0d51f" },
    { code: "KHA", name: "Al Khaleej", color: "#27a05d" },
    { code: "FAY", name: "Al Fayha", color: "#ef7f1a" },
    { code: "RIY", name: "Al Riyadh", color: "#a3282e" },
    { code: "KHO", name: "Al Kholood", color: "#b8322f" },
    { code: "HAZ", name: "Al Hazem", color: "#cf3339" },
    { code: "NEOM", name: "NEOM", color: "#189fe0" },
    { code: "ABH", name: "Abha", color: "#e6e6e6" },
    { code: "FSL", name: "Al Faisaly", color: "#8a1f3d" },
    { code: "DIR", name: "Al Diriyah", color: "#c2a06b" },
    ],
  },
];
