// Ball IQ card calibration — turns a measured population into the rating scale.
//
// WHY THIS EXISTS. Until 2026-09-09 the card mapped accuracy to 40-99 with a
// straight line (40 + 59·acc). Against the real population — 104 rated
// accounts — that put the MEDIAN player at 74 and a third of everyone in gold,
// with 80% of players squeezed between 64 and 82. The number could not tell
// good from great, which is the complaint "it doesn't reflect my level" seen
// from the other side. A rating only means something against other players,
// so the scale is anchored to measured percentiles and regenerated from data,
// never typed by hand.
//
// HOW TO REFRESH (quarterly, or when the rated population doubles):
//   1. Run the SQL below against prod (read-only) and save the percentiles as
//      scripts/data/card-calibration-<date>.json (see the 2026-09-09 file).
//   2. node scripts/calibrate-card.mjs scripts/data/card-calibration-<date>.json
//   3. Commit both. tests/unit/card-calibration.test.js pins the invariants.
//
// THE SQL (weighted c/a per account, exactly what computeCard consumes):
//   with p as (select id, stats->'catStats' cs from public.profiles where stats ? 'catStats'),
//   agg as (select id, sum((v->>'c')::float) c, sum((v->>'a')::float) a
//           from p, jsonb_each(cs) e(k,v) group by id),
//   lvl as (select c/a acc from agg where a >= 10)
//   select count(*) n,
//     percentile_cont(0.10) within group (order by acc) p10,
//     percentile_cont(0.25) within group (order by acc) p25,
//     percentile_cont(0.50) within group (order by acc) p50,
//     percentile_cont(0.75) within group (order by acc) p75,
//     percentile_cont(0.90) within group (order by acc) p90,
//     percentile_cont(0.97) within group (order by acc) p97
//   from lvl;
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: node scripts/calibrate-card.mjs <calibration.json>'); process.exit(1); }
const cal = JSON.parse(readFileSync(src, 'utf8'));
const p = cal.percentiles;
for (const k of ['10', '25', '50', '75', '90', '97']) {
  if (typeof p[k] !== 'number' || p[k] <= 0 || p[k] >= 1) { console.error(`[calibrate-card] percentile ${k} missing or out of (0,1)`); process.exit(1); }
}
if (!(p['10'] < p['25'] && p['25'] < p['50'] && p['50'] < p['75'] && p['75'] < p['90'] && p['90'] < p['97'])) {
  console.error('[calibrate-card] percentiles are not strictly increasing'); process.exit(1);
}
if (!(cal.n >= 50)) { console.error(`[calibrate-card] n=${cal.n} — too few rated accounts to anchor a scale`); process.exit(1); }

// The scale. Rating targets per percentile — THIS is the product decision:
//   p10 → 50   bottom decile, bronze
//   p50 → 65   the median player is a mid-silver
//   p75 → 75   the gold line: gold means TOP QUARTER
//   p90 → 84
//   p97 → 93
//   1.0 → 99   perfect, nobody
// Tiers stay bronze <60 / silver 60-74 / gold 75+, so bronze ≈ the bottom third.
const anchors = [
  [0, 40],
  [p['10'], 50], [p['50'], 65], [p['75'], 75], [p['90'], 84], [p['97'], 93],
  [1, 99],
];

// ── EXPECTED SCORE PER DIFFICULTY ──────────────────────────────────────────
// The rating is not accuracy. Each answer is scored against how often the
// population gets a question OF THAT DIFFICULTY right: a hard question
// answered correctly earns (1 - 0.45); an easy one missed costs 0.80. A player
// who is exactly median at every difficulty scores 0. Until 2026-09-09 the
// weights (1.3 / 0.8 / 1.15 / 0.85) were tuned to keep the AVERAGE weight ≈ 1
// "so nobody's rating jumps on upgrade" — and under them 80% on easy
// questions out-rated 50% on hard ones, though the first is below par and
// the second above it. Alex, 2026-09-09: "you should be rewarded slightly more
// for getting hard questions correct" — he was right, and by more than
// slightly.
//
// The values are BLENDED from two measurements and are the weakest number in
// this file: web club rounds (1,057 rounds, 60d): easy .84 / medium .65 /
// hard .49; in-app Daily 7 since answers carry `diff` (385 answers, 25
// players): medium .51 / hard .44, no easy in that mode. The writer now
// stores raw per-difficulty counts (`d`) so the next refresh can MEASURE
// these in-app across every mode and replace the blend.
const expected = cal.expected || { easy: 0.80, medium: 0.60, hard: 0.45 };
// Bank mix (easy 25% / medium 48% / hard 27%) → the expected score of an
// average question. Legacy {c,a} records with no per-answer scoring convert
// as s = c - PBAR·a, which is exact for a record of average difficulty.
const PBAR = +(0.25 * expected.easy + 0.48 * expected.medium + 0.27 * expected.hard).toFixed(3);
// Skill anchors are the accuracy anchors shifted by PBAR: for the measured
// population (all legacy records) skill = acc - PBAR exactly, so the
// percentiles carry over unchanged.
const skillAnchors = anchors.map(([acc, r]) => [+(acc - PBAR).toFixed(3), r]);

const body = `// GENERATED by scripts/calibrate-card.mjs — do not edit.
// Measured ${cal.measured} from ${cal.n} rated accounts (${cal.source}).
// Refresh: see the header of scripts/calibrate-card.mjs.
//
// ANCHORS: [weighted accuracy, rating]. ratingFromAccuracy() interpolates
// linearly between them. MEDIAN is the population's median accuracy and is the
// prior every new player's overall starts from (weight PRIOR_WEIGHT answers).
export const CALIBRATION = {
  measured: ${JSON.stringify(cal.measured)},
  n: ${cal.n},
  median: ${p['50']},
  anchors: ${JSON.stringify(anchors)},
  // Expected score per difficulty, the bank-mix average, and the anchors in
  // SKILL units (score above expectation). See scripts/calibrate-card.mjs.
  expected: ${JSON.stringify(expected)},
  pbar: ${PBAR},
  skillAnchors: ${JSON.stringify(skillAnchors)},
};
`;
const OUT = 'src/data/cardCalibration.js';
writeFileSync(OUT, body);
console.log(`[calibrate-card] wrote ${OUT}: n=${cal.n}, median=${p['50']}, gold line at acc ${p['75']} (skill ${(p['75'] - PBAR).toFixed(3)}), pbar=${PBAR}`);
