// Ball IQ card calibration — turns a measured population into the rating scale.
//
// WHY THIS EXISTS. Until 2026-09-09 the card mapped accuracy to 40-99 with a
// straight line (40 + 59·acc). Against the real population — 104 rated
// accounts — that put the MEDIAN player at 74 and a third of everyone in gold,
// with 80% of players squeezed between 64 and 82. The number could not tell
// good from great, which is the complaint "it doesn't reflect my level" seen
// from the other side. A rating only means something against other players,
// so the scale is anchored to measured percentiles and regenerated from data,
// never typed by hand.
//
// HOW TO REFRESH (quarterly, or when the rated population doubles):
//   1. Run the SQL below against prod (read-only) and save the percentiles as
//      scripts/data/card-calibration-<date>.json (see the 2026-09-09 file).
//   2. node scripts/calibrate-card.mjs scripts/data/card-calibration-<date>.json
//   3. Commit both. tests/unit/card-calibration.test.js pins the invariants.
//
// THE SQL (weighted c/a per account, exactly what computeCard consumes):
//   with p as (select id, stats->'catStats' cs from public.profiles where stats ? 'catStats'),
//   agg as (select id, sum((v->>'c')::float) c, sum((v->>'a')::float) a
//           from p, jsonb_each(cs) e(k,v) group by id),
//   lvl as (select c/a acc from agg where a >= 10)
//   select count(*) n,
//     percentile_cont(0.10) within group (order by acc) p10,
//     percentile_cont(0.25) within group (order by acc) p25,
//     percentile_cont(0.50) within group (order by acc) p50,
//     percentile_cont(0.75) within group (order by acc) p75,
//     percentile_cont(0.90) within group (order by acc) p90,
//     percentile_cont(0.97) within group (order by acc) p97
//   from lvl;
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: node scripts/calibrate-card.mjs <calibration.json>'); process.exit(1); }
const cal = JSON.parse(readFileSync(src, 'utf8'));
const p = cal.percentiles;
for (const k of ['10', '25', '50', '75', '90', '97']) {
  if (typeof p[k] !== 'number' || p[k] <= 0 || p[k] >= 1) { console.error(`[calibrate-card] percentile ${k} missing or out of (0,1)`); process.exit(1); }
}
if (!(p['10'] < p['25'] && p['25'] < p['50'] && p['50'] < p['75'] && p['75'] < p['90'] && p['90'] < p['97'])) {
  console.error('[calibrate-card] percentiles are not strictly increasing'); process.exit(1);
}
if (!(cal.n >= 50)) { console.error(`[calibrate-card] n=${cal.n} — too few rated accounts to anchor a scale`); process.exit(1); }

// The scale. Rating targets per percentile — THIS is the product decision:
//   p10 → 50   bottom decile, bronze
//   p50 → 65   the median player is a mid-silver
//   p75 → 75   the gold line: gold means TOP QUARTER
//   p90 → 84
//   p97 → 93
//   1.0 → 99   perfect, nobody
// Tiers stay bronze <60 / silver 60-74 / gold 75+, so bronze ≈ the bottom third.
const anchors = [
  [0, 40],
  [p['10'], 50], [p['50'], 65], [p['75'], 75], [p['90'], 84], [p['97'], 93],
  [1, 99],
];

// ── DIFFICULTY MULTIPLIERS (Alex, 2026-09-09) ────────────────────────────────
// "61% accuracy on easy questions equals 61; 61% at medium should be 10% more
// rewarding, hard 20% more." A correct answer is worth MULT[diff]; a miss is
// worth 0; the rating is 100 × the mean, shrunk toward the population baseline.
// It replaced a percentile-calibrated "score above expectation" model the same
// day — that one was statistically right and impossible to explain on a card.
// A player can verify this one with a calculator.
// ⚠️ 1.15 / 1.25 since 2026-09-10 (Alex): "the 10 and 20% number i am not even
// sure is right, maybe it should be 15% and 25%". Every one of the 7,078 bank
// questions carries a difficulty grade — zero ungraded — so the weight is
// applied from the ANSWER's own difficulty, not guessed.
const MULT = { easy: 1.0, medium: 1.15, hard: 1.25 };
// Bank mix, re-counted 2026-09-10 across all 7,078 questions: easy 24.9% /
// medium 48.1% / hard 27.0%. This is the multiplier of an average question and
// the ONLY weight a record without per-answer difficulty can be given.
const AVG_MULT = +(0.249 * MULT.easy + 0.481 * MULT.medium + 0.270 * MULT.hard).toFixed(4);
// Where a card with no evidence starts: the measured median player's rating.
// ⚠️ RE-MEASURED FROM REAL ANSWERS 2026-09-10. The previous median (0.58) came
// from the DECAYED c/a totals, which overstated both level and spread: against
// 4,180 actual per-question records the median player is 0.5306, p25 0.486 and
// p90 0.660, not 0.51-0.72. Calibrating a scale on a quantity nobody can verify
// is how the card ended up disagreeing with the answer log.
const BASELINE = +(p['50'] * AVG_MULT).toFixed(4);

const body = `// GENERATED by scripts/calibrate-card.mjs — do not edit.
// Measured ${cal.measured} from ${cal.n} rated accounts (${cal.source}).
// Refresh: see the header of scripts/calibrate-card.mjs.
//
// ANCHORS: [weighted accuracy, rating]. ratingFromAccuracy() interpolates
// linearly between them. MEDIAN is the population's median accuracy and is the
// prior every new player's overall starts from (weight PRIOR_WEIGHT answers).
export const CALIBRATION = {
  measured: ${JSON.stringify(cal.measured)},
  n: ${cal.n},
  median: ${p['50']},
  anchors: ${JSON.stringify(anchors)},
  // The model (Alex, 2026-09-09): rating = 100 × mean(correct ? MULT[diff] : 0),
  // shrunk toward BASELINE. The anchors above are the measured population in
  // plain accuracy, kept for reference and for the calibration tests.
  mult: ${JSON.stringify(MULT)},
  avgMult: ${AVG_MULT},
  baseline: ${BASELINE},
};
`;
const OUT = 'src/data/cardCalibration.js';
writeFileSync(OUT, body);
console.log(`[calibrate-card] wrote ${OUT}: n=${cal.n}, median acc=${p['50']} → baseline ${BASELINE} (${Math.round(BASELINE * 100)}), avgMult=${AVG_MULT}`);
